/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is the confidential and proprietary information of Nodics ("Confidential Information").
    You shall not disclose such Confidential Information and shall use it only in accordance with the
    terms of the license agreement you entered into with Nodics.

 */

const crypto = require('crypto');
/** @module product/service/projection/DefaultProductProjectionOrchestrationService @description Persists restart-safe cache/search projection jobs and retries them independently after successful Online activation. @layer service @owner product */
module.exports = {
    /** Initializes Product projection orchestration. */ init: function () { return Promise.resolve(true); },
    /** Completes projection initialization. */ postInit: function () { return Promise.resolve(true); },
    /** Returns projection policy. */ policy: function () { return (CONFIG.get('product') || {}).projection || {}; },
    /** Extracts generated-service items. */ items: function (response) { return response && Array.isArray(response.result) ? response.result : []; },
    /** Creates a deterministic job identity for an operation and manifest. */ code: function (operation, manifestCode) { return crypto.createHash('sha256').update(operation + '|' + manifestCode).digest('hex'); },
    /** Loads an integrity-checked accepted manifest. */ manifest: async function (code, request) { let items = this.items(await SERVICE.DefaultProductReleaseManifestService.get({ tenant: request.tenant, authData: request.authData, query: { code: code }, searchOptions: { limit: 2 } })); if (items.length !== 1) throw new CLASSES.NodicsError('ERR_PRODUCT_00065', 'Product projection manifest is unavailable'); SERVICE.DefaultProductPublicationManifestService.verify(items[0]); return items[0]; },
    /** Creates or returns one durable projection job. */ ensure: async function (operation, manifest, request) { let code = this.code(operation, manifest.code), existing = this.items(await SERVICE.DefaultProductProjectionJobService.get({ tenant: request.tenant, authData: request.authData, query: { code: code }, searchOptions: { limit: 1 } }))[0]; if (existing) return existing; let model = { code: code, active: true, enterpriseCode: manifest.snapshot.enterpriseCode, catalogCode: manifest.snapshot.catalogCode, manifestCode: manifest.code, operation: operation, state: 'PENDING', cacheState: 'PENDING', searchState: 'PENDING', attempts: 0, correlationId: request.correlationId || request.requestId }, response = await SERVICE.DefaultProductProjectionJobService.save({ tenant: request.tenant, authData: request.authData, model: model }); return this.items(response)[0] || response.result || model; },
    /** Persists one compare-by-code job patch. */ update: function (job, patch, request) { return SERVICE.DefaultProductProjectionJobService.update({ tenant: request.tenant, authData: request.authData, query: { code: job.code }, model: patch }); },
    /** Executes cache and search projections independently and records partial failure. */ process: async function (job, manifest, request) { let policy = this.policy(), attempts = Number(job.attempts || 0) + 1; if (attempts > Number(policy.maximumAttempts || 10)) { await this.update(job, { state: 'FAILED', attempts: attempts, lastErrorCode: 'MAX_ATTEMPTS', lastAttemptAt: new Date() }, request); return Object.assign({}, job, { state: 'FAILED', attempts: attempts, lastErrorCode: 'MAX_ATTEMPTS' }); } let cacheState = job.cacheState, searchState = job.searchState, errors = [];
        if (!['COMPLETE', 'SKIPPED'].includes(cacheState)) { try { await SERVICE.DefaultProductDeliveryCacheService.invalidate(request); cacheState = 'COMPLETE'; } catch (error) { cacheState = 'FAILED'; errors.push(error); } }
        if (!['COMPLETE', 'SKIPPED'].includes(searchState)) { try { let policySearch = (CONFIG.get('product') || {}).searchProjection || {}, provider = policySearch.provider && SERVICE[policySearch.provider]; if (policySearch.enabled === false) searchState = 'SKIPPED'; else if (!provider || typeof provider.project !== 'function') throw new CLASSES.NodicsError('ERR_PRODUCT_00066', 'Product search projection provider is unavailable'); else searchState = (await provider.project(manifest, request)).state || 'COMPLETE'; } catch (error) { searchState = 'FAILED'; errors.push(error); } }
        let state = errors.length ? 'PARTIAL' : 'COMPLETE', patch = { state: state, cacheState: cacheState, searchState: searchState, attempts: attempts, lastAttemptAt: new Date(), lastErrorCode: errors[0] && (errors[0].code || errors[0].name), completedAt: state === 'COMPLETE' ? new Date() : undefined }; await this.update(job, patch, request); return Object.assign({}, job, patch); },
    /** Enqueues and attempts projection work without undoing successful Online activation. */ afterActivation: async function (operation, manifestCode, request) { if (this.policy().enabled === false) return { state: 'SKIPPED' }; try { let manifest = await this.manifest(manifestCode, request), job = await this.ensure(operation, manifest, request); if (job.state === 'COMPLETE') return job; return await this.process(job, manifest, request); } catch (error) { return { state: 'FAILED', errorCode: error.code || error.name }; } },
    /** Reconciles one bounded set of incomplete Product projection jobs. */ reconcile: async function (request) { let policy = this.policy(), enterpriseCode = SERVICE.DefaultProductEnterpriseScopeService.resolveEnterpriseCode(request), catalogCode = request.catalogCode, response = await SERVICE.DefaultProductProjectionJobService.get({ tenant: request.tenant, authData: request.authData, query: { enterpriseCode: enterpriseCode, catalogCode: catalogCode, state: { $in: policy.retryStates || ['PENDING', 'PARTIAL', 'FAILED'] } }, searchOptions: { limit: Number(policy.reconciliationBatchSize || 100), sort: { lastAttemptAt: 1 } } }), jobs = this.items(response), results = []; for (let job of jobs) { let manifest = await this.manifest(job.manifestCode, request); results.push(await this.process(job, manifest, request)); } return { scanned: jobs.length, completed: results.filter(item => item.state === 'COMPLETE').length, remaining: results.filter(item => item.state !== 'COMPLETE').length, results: results.map(item => ({ code: item.code, manifestCode: item.manifestCode, state: item.state, cacheState: item.cacheState, searchState: item.searchState, attempts: item.attempts, lastErrorCode: item.lastErrorCode })) }; }
};
