/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is the confidential and proprietary information of Nodics ("Confidential Information").
    You shall not disclose such Confidential Information and shall use it only in accordance with the
    terms of the license agreement you entered into with Nodics.

 */

/** @module pricing/service/publication/DefaultPricingPublicationWorkflowService @description Submits Price List releases to configurable manual or automatic Workflow actions and publishes only approved carriers through nPublish. @layer service @owner pricing */
module.exports = {
    /** Initializes the workflow bridge. */ init: function () { return Promise.resolve(true); },
    /** Completes initialization. */ postInit: function () { return Promise.resolve(true); },
    /** Returns layered Pricing workflow policy. */ policy: function () { return (CONFIG.get('pricing') || {}).workflow || {}; },
    /** Returns a stable Pricing workflow error. */ error: function (code, message) { return SERVICE.DefaultPricingEnterpriseScopeService.error(code, message); },
    /** Resolves one configured manual or automatic mode. */ mode: function (value) { let policy = this.policy(), mode = value || policy.defaultMode || 'MANUAL'; if (!(policy.modes || ['MANUAL', 'AUTOMATIC']).includes(mode)) throw this.error('ERR_PRICE_00026', 'Pricing workflow mode is unsupported'); return mode; },
    /** Extracts workflow-governed publication data and associated item identities. */ publication: function (carrier) { carrier = carrier || {}; let publication = carrier.sourceDetail && carrier.sourceDetail.publication; if (!carrier.code || !publication || publication.domain !== 'pricing' || publication.rootType !== 'PRICE_LIST' || !publication.rootCode || !Number.isInteger(Number(publication.sourceVersion)) || Number(publication.sourceVersion) < 0 || !Array.isArray(carrier.items) || !carrier.items.length) throw this.error('ERR_PRICE_00026', 'Pricing workflow carrier is incomplete'); return Object.assign({}, publication, { workflowRef: carrier.code, associatedItems: carrier.items.map(item => ({ schema: item.schemaName, code: item.code, version: item.versionId === undefined ? undefined : String(item.versionId), refId: item.refId })) }); },
    /** Creates and releases an idempotently identified Workflow carrier for one Price List release. */ submit: async function (request) { let policy = this.policy(), body = request.body || {}; if (policy.enabled === false || !SERVICE.DefaultWorkflowService) throw this.error('ERR_PRICE_00027', 'Pricing publication Workflow is unavailable'); let enterpriseCode = SERVICE.DefaultPricingEnterpriseScopeService.resolveEnterpriseCode(request), priceListCode = SERVICE.DefaultPricingEnterpriseScopeService.validateBusinessCode(body.priceListCode, 'Price List'), submissionCode = SERVICE.DefaultPricingEnterpriseScopeService.validateBusinessCode(body.submissionCode, 'Submission'), sourceVersion = Number(body.sourceVersion), mode = this.mode(body.approvalMode), items = body.items, allowedSchemas = policy.allowedAssociatedSchemas || [], rootCode = SERVICE.DefaultPricingEnterpriseScopeService.buildIdentity(enterpriseCode, 'priceList', [priceListCode]); if (!Number.isInteger(sourceVersion) || sourceVersion < 0 || !Array.isArray(items) || !items.length || items.length > Number(policy.maximumAssociatedItems || 10000) || items.some(item => !item || !allowedSchemas.includes(item.schemaName) || !item.code || !Number.isInteger(Number(item.versionId)) || Number(item.versionId) < 0) || !items.some(item => item.schemaName === 'priceList' && item.code === rootCode && Number(item.versionId) === sourceVersion)) throw this.error('ERR_PRICE_00026', 'Pricing publication version or associated items are invalid'); let carrierCode = SERVICE.DefaultPricingEnterpriseScopeService.buildIdentity(enterpriseCode, 'pricingPublication', [submissionCode]); if (SERVICE.DefaultWorkflowCarrierService && await SERVICE.DefaultWorkflowCarrierService.isCarrierAvailable({ tenant: request.tenant, authData: request.authData, carrierCode: carrierCode })) return { carrierCode: carrierCode, approvalMode: mode, idempotent: true }; let workflowCode = mode === 'AUTOMATIC' ? policy.automaticWorkflowCode : policy.manualWorkflowCode, publication = { code: carrierCode, domain: 'pricing', rootType: 'PRICE_LIST', rootCode: rootCode, sourceVersion: String(sourceVersion) }; await SERVICE.DefaultWorkflowService.initCarrier({ tenant: request.tenant, authData: request.authData, workflowCode: workflowCode, releaseCarrier: true, carrier: { code: carrierCode, event: { enabled: true }, sourceDetail: { enterpriseCode: enterpriseCode, approvalMode: mode, publication: publication }, items: items.map(item => ({ active: true, schemaName: item.schemaName, code: item.code, versionId: Number(item.versionId), refId: item.refId || item.code, itemDetail: { schemaName: item.schemaName, code: item.code, versionId: Number(item.versionId) } })) } }); return { carrierCode: carrierCode, workflowCode: workflowCode, approvalMode: mode, state: 'SUBMITTED', idempotent: false }; },
    /** Publishes an approved manual or automatic Workflow carrier through the existing nPublish lifecycle. */ publish: async function (request) { let carrier = request.workflowCarrier || {}, publication = this.publication(carrier), context = { tenant: request.tenant, authData: request.authData, correlationId: request.correlationId || carrier.code, reason: 'Approved by Pricing workflow ' + carrier.code, publication: publication }, online = await SERVICE.DefaultPublicationLifecycleService.publishApproved(context); return { decision: 'SUCCESS', type: 'SUCCESS', feedback: { publicationCode: online.code, targetVersion: online.targetVersion, state: online.state, workflowRef: carrier.code, approvalMode: carrier.sourceDetail.approvalMode } }; }
};
