/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */

/** @module kycCore/config/properties @description Configuration-first KYC defaults. Later layers override only owned differences. */
module.exports = {
    token: { OTP: { validUpTo: 600, attemptLimit: 5, singleUseToken: true } },
    backofficeCapabilities: {
        kyc: {
            enabled: true,
            capabilityId: 'compliance-kyc',
            displayName: 'KYC Management',
            category: 'governance',
            icon: 'compliance',
            contractVersion: 1,
            minimumClientContractVersion: 1,
            roles: ['FUNCTIONAL_CAPABILITY_PROVIDER'],
            discovery: { openApiPath: '/nodics/kyc/v0/contract/openapi', contractVersion: 1 },
            requiredPermissions: ['kyc.case.read'],
            navigation: [
                { id: 'kyc-cases', parentId: 'compliance-management', parentModuleName: 'complianceCore', label: 'KYC Cases', route: '/compliance-management/kyc/cases', icon: 'case', order: 110, group: { id: 'compliance-management', label: 'Compliance Management', order: 220 }, perspectives: ['operations'], contexts: ['tenant', 'enterprise'], workbenchTarget: { moduleName: 'kycSchema', schemaName: 'kycVerificationCase' }, workbenchPresentation: { defaultColumns: ['caseCode', 'subjectType', 'verificationLevel', 'status', 'providerCode', 'submittedAt', 'expiresAt'], forbiddenFields: ['submissionIdentityHash'], quickFilters: [{ id: 'needs-review', label: 'Needs review', field: 'status', values: ['MANUAL_REVIEW_REQUIRED', 'ESCALATED'] }, { id: 'failed', label: 'Recovery required', field: 'status', values: ['FAILED', 'SUBMISSION_FAILED'] }] }, detailPanels: [{ id: 'checks', label: 'Check evidence', summary: 'Normalized provider and manual checks.', order: 10, target: { moduleName: 'kycSchema', schemaName: 'kycCheck' }, relation: { sourceField: 'caseCode', targetField: 'caseCode' } }, { id: 'documents', label: 'Documents', summary: 'Masked metadata and nMedia references only.', order: 20, target: { moduleName: 'kycSchema', schemaName: 'kycDocument' }, relation: { sourceField: 'caseCode', targetField: 'caseCode' } }, { id: 'reviews', label: 'Review timeline', summary: 'Assignment, SLA, maker-checker, and recovery state.', order: 30, target: { moduleName: 'kycSchema', schemaName: 'kycReviewTask' }, relation: { sourceField: 'caseCode', targetField: 'caseCode' } }, { id: 'decisions', label: 'Decisions', summary: 'Append-only decision evidence.', order: 40, target: { moduleName: 'kycSchema', schemaName: 'kycDecision' }, relation: { sourceField: 'caseCode', targetField: 'caseCode' } }, { id: 'provider-attempts', label: 'Provider diagnostics', summary: 'Safe attempts, retries, reconciliation, and failure codes.', order: 50, target: { moduleName: 'kycSchema', schemaName: 'kycProviderExecutionAttempt' }, relation: { sourceField: 'caseCode', targetField: 'caseCode' } }, { id: 'audit', label: 'Audit timeline', summary: 'Redacted immutable operation evidence.', order: 60, target: { moduleName: 'kycSchema', schemaName: 'kycAuditEvent' }, relation: { sourceField: 'caseCode', targetField: 'caseCode' } }], lifecycleActions: [
                    { id: 'request-more-information', label: 'Request more information', intent: 'OTHER', permission: 'kyc.review.request-information', ownerModule: 'kycApi', operationRoute: '/nodics/kyc/v0/cases/{caseCode}/actions/REQUEST_MORE_INFORMATION', targetStatuses: ['MANUAL_REVIEW_REQUIRED', 'ESCALATED'], order: 10, inputFields: [{ name: 'reasonCode', label: 'Reason code', type: 'TEXT', required: true, maximumLength: 100 }, { name: 'safeReason', label: 'Safe explanation', type: 'MULTILINE', required: true, maximumLength: 1000 }] },
                    { id: 'approve', label: 'Approve', intent: 'APPROVE', permission: 'kyc.review.approve', ownerModule: 'kycApi', operationRoute: '/nodics/kyc/v0/cases/{caseCode}/actions/APPROVE', targetStatuses: ['MANUAL_REVIEW_REQUIRED', 'ESCALATED'], order: 20, inputFields: [{ name: 'reasonCode', label: 'Reason code', type: 'TEXT', required: true, maximumLength: 100 }, { name: 'safeReason', label: 'Safe explanation', type: 'MULTILINE', required: true, maximumLength: 1000 }] },
                    { id: 'reject', label: 'Reject', intent: 'REJECT', permission: 'kyc.review.reject', ownerModule: 'kycApi', operationRoute: '/nodics/kyc/v0/cases/{caseCode}/actions/REJECT', targetStatuses: ['MANUAL_REVIEW_REQUIRED', 'ESCALATED'], order: 30, inputFields: [{ name: 'reasonCode', label: 'Reason code', type: 'TEXT', required: true, maximumLength: 100 }, { name: 'safeReason', label: 'Safe explanation', type: 'MULTILINE', required: true, maximumLength: 1000 }] },
                    { id: 'escalate', label: 'Escalate', intent: 'OTHER', permission: 'kyc.review.escalate', ownerModule: 'kycApi', operationRoute: '/nodics/kyc/v0/cases/{caseCode}/actions/ESCALATE', targetStatuses: ['MANUAL_REVIEW_REQUIRED'], order: 40, inputFields: [{ name: 'reasonCode', label: 'Reason code', type: 'TEXT', required: true, maximumLength: 100 }] }
                ], help: { summary: 'Inspect verification attempts and invoke only backend-authorized intent actions.', documentationRoute: '/docs/reference/compliance-kyc', documentationFragment: 'case-lifecycle' }, featureState: 'ACTIVE', requiredPermissions: ['kyc.case.read'] },
                { id: 'kyc-reviews', parentId: 'compliance-management', parentModuleName: 'complianceCore', label: 'Review Queue', route: '/compliance-management/kyc/reviews', icon: 'review', order: 120, group: { id: 'compliance-management', label: 'Compliance Management', order: 220 }, perspectives: ['operations'], contexts: ['tenant', 'enterprise'], workbenchTarget: { moduleName: 'kycSchema', schemaName: 'kycReviewTask' }, lifecycleActions: [
                    { id: 'claim', label: 'Claim', intent: 'OTHER', permission: 'kyc.review.claim', ownerModule: 'kycApi', operationRoute: '/nodics/kyc/v0/reviews/{reviewTaskCode}/actions/CLAIM', targetStatuses: ['OPEN'], order: 10 },
                    { id: 'takeover', label: 'Take over', intent: 'OTHER', permission: 'kyc.review.takeover', ownerModule: 'kycApi', operationRoute: '/nodics/kyc/v0/reviews/{reviewTaskCode}/actions/TAKEOVER', targetStatuses: ['OPEN', 'CLAIMED'], order: 20, inputFields: [{ name: 'reasonCode', label: 'Reason code', type: 'TEXT', required: true, maximumLength: 100 }] },
                    { id: 'request-information', label: 'Request information', intent: 'OTHER', permission: 'kyc.review.request-information', ownerModule: 'kycApi', operationRoute: '/nodics/kyc/v0/reviews/{reviewTaskCode}/actions/REQUEST_MORE_INFORMATION', targetStatuses: ['OPEN', 'CLAIMED', 'ESCALATED'], order: 30, inputFields: [{ name: 'reasonCode', label: 'Reason code', type: 'TEXT', required: true, maximumLength: 100 }, { name: 'safeNote', label: 'Safe note', type: 'MULTILINE', required: true, maximumLength: 1000 }] },
                    { id: 'escalate', label: 'Escalate', intent: 'OTHER', permission: 'kyc.review.escalate', ownerModule: 'kycApi', operationRoute: '/nodics/kyc/v0/reviews/{reviewTaskCode}/actions/ESCALATE', targetStatuses: ['OPEN', 'CLAIMED'], order: 40, inputFields: [{ name: 'reasonCode', label: 'Reason code', type: 'TEXT', required: true, maximumLength: 100 }] },
                    { id: 'request-checker', label: 'Request checker', intent: 'SUBMIT', permission: 'kyc.review.request-checker', ownerModule: 'kycApi', operationRoute: '/nodics/kyc/v0/reviews/{reviewTaskCode}/actions/REQUEST_CHECKER', targetStatuses: ['CLAIMED', 'ESCALATED'], order: 50, inputFields: [{ name: 'requestedAction', label: 'Requested action', type: 'SELECT', required: true, options: ['APPROVE', 'REJECT'] }, { name: 'reasonCode', label: 'Reason code', type: 'TEXT', required: true, maximumLength: 100 }] },
                    { id: 'approve', label: 'Approve', intent: 'APPROVE', permission: 'kyc.review.approve', ownerModule: 'kycApi', operationRoute: '/nodics/kyc/v0/reviews/{reviewTaskCode}/actions/APPROVE', targetStatuses: ['CHECKER_PENDING'], order: 60, inputFields: [{ name: 'reasonCode', label: 'Reason code', type: 'TEXT', required: true, maximumLength: 100 }] },
                    { id: 'reject', label: 'Reject', intent: 'REJECT', permission: 'kyc.review.reject', ownerModule: 'kycApi', operationRoute: '/nodics/kyc/v0/reviews/{reviewTaskCode}/actions/REJECT', targetStatuses: ['CHECKER_PENDING'], order: 70, inputFields: [{ name: 'reasonCode', label: 'Reason code', type: 'TEXT', required: true, maximumLength: 100 }] }
                ], help: { summary: 'Assign, claim, request information, escalate, and complete persisted maker-checker review tasks.', documentationRoute: '/docs/reference/compliance-kyc', documentationFragment: 'manual-review' }, featureState: 'ACTIVE', requiredPermissions: ['kyc.review.read'] },
                { id: 'kyc-profiles', parentId: 'compliance-management', parentModuleName: 'complianceCore', label: 'Subject Status', route: '/compliance-management/kyc/profiles', icon: 'profile', order: 130, group: { id: 'compliance-management', label: 'Compliance Management', order: 220 }, perspectives: ['operations'], contexts: ['tenant', 'enterprise'], workbenchTarget: { moduleName: 'kycSchema', schemaName: 'kycProfile' }, help: { summary: 'View reference-only subject verification status and expiry.', documentationRoute: '/docs/reference/compliance-kyc', documentationFragment: 'profile-versus-kyc' }, featureState: 'ACTIVE', requiredPermissions: ['kyc.profile.read'] },
                { id: 'kyc-documents', parentId: 'compliance-management', parentModuleName: 'complianceCore', label: 'Document Review', route: '/compliance-management/kyc/documents', icon: 'document', order: 140, group: { id: 'compliance-management', label: 'Compliance Management', order: 220 }, perspectives: ['operations'], contexts: ['tenant', 'enterprise'], workbenchTarget: { moduleName: 'kycSchema', schemaName: 'kycDocument' }, help: { summary: 'Review masked document metadata and request purpose-bound nMedia delivery.', documentationRoute: '/docs/reference/compliance-kyc', documentationFragment: 'document-security' }, featureState: 'ACTIVE', requiredPermissions: ['kyc.document.metadata.read'] },
                { id: 'kyc-policies', parentId: 'compliance-management', parentModuleName: 'complianceCore', label: 'Policies & Requirements', route: '/compliance-management/kyc/policies', icon: 'policy', order: 150, group: { id: 'compliance-management', label: 'Compliance Management', order: 220 }, perspectives: ['configuration'], contexts: ['tenant', 'enterprise'], workbenchTarget: { moduleName: 'kycSchema', schemaName: 'kycDocumentRequirement' }, help: { summary: 'Inspect effective verification levels, document requirements, retention, and masking policy.', documentationRoute: '/docs/reference/compliance-kyc', documentationFragment: 'configuration' }, featureState: 'ACTIVE', requiredPermissions: ['kyc.policy.read'] },
                { id: 'kyc-providers', parentId: 'compliance-management', parentModuleName: 'complianceCore', label: 'Providers', route: '/compliance-management/kyc/providers', icon: 'provider', order: 160, group: { id: 'compliance-management', label: 'Compliance Management', order: 220 }, perspectives: ['configuration', 'operations'], contexts: ['tenant', 'enterprise'], workbenchTarget: { moduleName: 'kycSchema', schemaName: 'kycProvider' }, workbenchPresentation: { defaultColumns: ['providerCode', 'label', 'healthStatus', 'sandboxSupported', 'productionReady', 'status'], forbiddenFields: ['secretReference'] }, lifecycleActions: [{ id: 'update-provider', label: 'Update provider', intent: 'UPDATE', permission: 'kyc.provider.manage', ownerModule: 'kycApi', operationRoute: '/nodics/kyc/v0/providers/{providerCode}/actions/UPDATE', targetStatuses: ['ACTIVE', 'INACTIVE'], order: 10, inputFields: [{ name: 'expectedVersion', label: 'Expected version', type: 'TEXT', required: true }, { name: 'reasonCode', label: 'Reason code', type: 'TEXT', required: true }, { name: 'healthStatus', label: 'Health status', type: 'SELECT', required: false, options: ['READY', 'DEGRADED', 'UNAVAILABLE'] }] }], detailPanels: [{ id: 'provider-policy', label: 'Execution Policy', summary: 'Inspect live-call, timeout, retry, failover, and callback governance.', order: 10, target: { moduleName: 'kycSchema', schemaName: 'kycProviderExecutionPolicy' }, relation: { sourceField: 'providerCode', targetField: 'providerCode' } }, { id: 'provider-accounts', label: 'Accounts', summary: 'Scoped account readiness; credentials remain secret references.', order: 20, target: { moduleName: 'kycSchema', schemaName: 'kycProviderAccount' }, relation: { sourceField: 'providerCode', targetField: 'providerCode' } }], help: { summary: 'Inspect and govern provider readiness without exposing credentials.', documentationRoute: '/docs/reference/compliance-kyc', documentationFragment: 'providers' }, featureState: 'ACTIVE', requiredPermissions: ['kyc.provider.read'] },
                { id: 'kyc-provider-policies', parentId: 'compliance-management', parentModuleName: 'complianceCore', label: 'Provider Policies', route: '/compliance-management/kyc/provider-policies', icon: 'policy', order: 165, group: { id: 'compliance-management', label: 'Compliance Management', order: 220 }, perspectives: ['configuration'], contexts: ['tenant', 'enterprise'], workbenchTarget: { moduleName: 'kycSchema', schemaName: 'kycProviderExecutionPolicy' }, workbenchPresentation: { defaultColumns: ['providerPolicyCode', 'providerCode', 'liveCallsEnabled', 'timeoutMs', 'maxAttempts', 'circuitOpenUntil', 'status'] }, lifecycleActions: [{ id: 'update-policy', label: 'Update policy', intent: 'UPDATE', permission: 'kyc.policy.manage', ownerModule: 'kycApi', operationRoute: '/nodics/kyc/v0/provider-policies/{providerPolicyCode}/actions/UPDATE', targetStatuses: ['ACTIVE', 'INACTIVE'], order: 10, inputFields: [{ name: 'expectedVersion', label: 'Expected version', type: 'TEXT', required: true }, { name: 'reasonCode', label: 'Reason code', type: 'TEXT', required: true }, { name: 'timeoutMs', label: 'Timeout milliseconds', type: 'TEXT', required: false }, { name: 'maxAttempts', label: 'Maximum attempts', type: 'TEXT', required: false }] }], help: { summary: 'Govern timeout, retry, failover, circuit, callback, and live-call policy through audited actions.', documentationRoute: '/docs/reference/compliance-kyc', documentationFragment: 'provider-governance' }, featureState: 'ACTIVE', requiredPermissions: ['kyc.policy.read'] },
                { id: 'kyc-audit', parentId: 'compliance-management', parentModuleName: 'complianceCore', label: 'Compliance Audit', route: '/compliance-management/kyc/audit', icon: 'audit', order: 170, group: { id: 'compliance-management', label: 'Compliance Management', order: 220 }, perspectives: ['audit'], contexts: ['tenant', 'enterprise'], workbenchTarget: { moduleName: 'kycSchema', schemaName: 'kycAuditEvent' }, workbenchPresentation: { defaultColumns: ['occurredAt', 'operation', 'outcome', 'caseCode', 'actorReference', 'permissionCode', 'correlationId'], forbiddenFields: ['subjectCodeHash'] }, help: { summary: 'Inspect append-only, redacted KYC operation evidence.', documentationRoute: '/docs/reference/compliance-kyc', documentationFragment: 'audit-and-operations' }, featureState: 'ACTIVE', requiredPermissions: ['kyc.audit.read'] }
            ]
        }
    },
    kyc: {
        policy: {
            defaultPolicyCode: 'individual-basic-v1',
            defaultCaseType: 'INDIVIDUAL_KYC',
            supportedSubjectTypes: ['CUSTOMER', 'EMPLOYEE'],
            entryPoints: ['ONBOARDING', 'CHECKOUT', 'PAYMENT', 'REFUND', 'ORDER'],
            verificationLevels: {
                BASIC: { checkTypes: ['DOCUMENT_AUTHENTICITY'], requiredDocumentTypes: ['NATIONAL_ID'], manualReviewOnInconclusive: true },
                ENHANCED: { checkTypes: ['DOCUMENT_AUTHENTICITY', 'FACE_MATCH', 'LIVENESS', 'ADDRESS_VERIFICATION'], requiredDocumentTypes: ['NATIONAL_ID', 'PROOF_OF_ADDRESS', 'SELFIE'], manualReviewOnInconclusive: true }
            },
            defaultVerificationLevel: 'BASIC',
            highValueThresholds: { defaultCurrency: 'USD', checkoutMinorUnits: '100000', refundMinorUnits: '50000' },
            expiryDays: 365,
            retention: { documentDays: 2555, evidenceDays: 2555, auditDays: 3650, legalHoldOverridesDeletion: true },
            masking: { documentNumberVisibleSuffix: 4, subjectCodeHashAlgorithm: 'sha256', rawProviderPayloadAllowed: false },
            consent: { required: true, type: 'IDENTITY_VERIFICATION', activeVersion: '1.0', biometricConsentRequired: true },
            makerChecker: { enabled: true, actions: ['OVERRIDE', 'REJECTION_REVERSAL', 'HIGH_RISK_APPROVAL', 'POLICY_EXCEPTION'] },
            actionPermissions: { APPROVE: 'kyc.review.approve', REJECT: 'kyc.review.reject', REQUEST_MORE_INFORMATION: 'kyc.review.request-information', ESCALATE: 'kyc.review.escalate', CANCEL: 'kyc.case.cancel', EXPIRE: 'kyc.case.expire', REVERIFY: 'kyc.case.reverify', OVERRIDE: 'kyc.review.override', REJECTION_REVERSAL: 'kyc.review.rejection-reversal', HIGH_RISK_APPROVAL: 'kyc.review.high-risk-approve', POLICY_EXCEPTION: 'kyc.review.policy-exception' },
            reusableDecision: { enabled: true, requireSameTenant: true, requireSameEnterprise: true, requireUnexpired: true, allowedEntryPoints: ['CHECKOUT', 'PAYMENT', 'REFUND', 'ORDER'] }
            ,rules: [
                { ruleCode: 'HIGH_VALUE_CHECKOUT', enabled: true, priority: 100, reasonCode: 'HIGH_VALUE', when: { minimumOrderMinorUnits: '100000' }, apply: { verificationLevel: 'ENHANCED', manualReviewRequired: true } },
                { ruleCode: 'HIGH_VALUE_REFUND', enabled: true, priority: 100, reasonCode: 'HIGH_VALUE_REFUND', when: { minimumRefundMinorUnits: '50000' }, apply: { verificationLevel: 'ENHANCED', manualReviewRequired: true } },
                { ruleCode: 'ELEVATED_RISK', enabled: true, priority: 200, reasonCode: 'RISK_STEP_UP', when: { minimumRiskScore: 70 }, apply: { verificationLevel: 'ENHANCED', additionalCheckTypes: ['MANUAL_RISK_REVIEW'], manualReviewRequired: true, reusableDecision: { enabled: false } } }
            ]
        },
        documents: { mediaPurpose: 'kycDocuments', requirePrivateVisibility: true, allowRawPath: false, auditedDelivery: true },
        persistence: { transactionModuleName: 'kycSchema', requireAtomicSubmission: true },
        eligibility: { contractVersion: 1, maximumTtlSeconds: 300, invalidateOn: ['PROFILE_CHANGED', 'DECISION_CHANGED', 'POLICY_CHANGED', 'CONSENT_REVOKED', 'CASE_EXPIRED'] },
        providerExecution: { defaultProvider: 'mockKyc', allowedProviders: ['mockKyc'], liveCallsEnabled: false, timeoutMs: 10000, maxAttempts: 3, backoffMs: 500, webhookToleranceSeconds: 300, replayWindowSeconds: 86400 },
        providerWebhook: { signatureHeader: 'x-kyc-signature', eventIdHeader: 'x-kyc-event-id', timestampHeader: 'x-kyc-timestamp', accountHeader: 'x-kyc-account', secretResolverService: 'DefaultSecretReferenceService' },
        workflows: { verificationWorkflowCode: 'kycVerificationWorkflow', manualReviewWorkflowCode: 'kycManualReviewWorkflow', reviewSlaHours: 24, escalationSlaHours: 48, maximumSafeNoteLength: 1000, maximumSafeNotes: 20, reviewActionPermissions: { ASSIGN: 'kyc.review.assign', REASSIGN: 'kyc.review.assign', CLAIM: 'kyc.review.claim', TAKEOVER: 'kyc.review.takeover', REQUEST_MORE_INFORMATION: 'kyc.review.request-information', ESCALATE: 'kyc.review.escalate', REQUEST_CHECKER: 'kyc.review.request-checker', APPROVE: 'kyc.review.approve', REJECT: 'kyc.review.reject', OVERRIDE: 'kyc.review.override', REJECTION_REVERSAL: 'kyc.review.rejection-reversal', HIGH_RISK_APPROVAL: 'kyc.review.high-risk-approve', POLICY_EXCEPTION: 'kyc.review.policy-exception', CLOSE: 'kyc.review.close', EXPIRE: 'kyc.review.expire' } },
        lifecycle: { batchSize: 100, triggerExpression: '0 0 * * * *', activeByDefault: false, reverificationNoticeDays: 30, reverificationWorkflowCode: 'kycReverificationWorkflow', retryOnFailure: true, backupRestoreRunbook: '/docs/reference/compliance-kyc/operations-and-recovery' },
        operations: { dashboardMaximumRecords: 500 },
        rateLimit: {
            moduleName: 'cache',
            channelName: 'rateLimit',
            requireDistributedInProduction: true,
            operations: {
                submit: { limit: 5, windowSeconds: 3600, identityFields: ['tenantCode', 'enterpriseCode', 'subjectType', 'subjectCode'] },
                decision: { limit: 3, windowSeconds: 60, identityFields: ['tenantCode', 'enterpriseCode', 'caseCode'] },
                callback: { limit: 120, windowSeconds: 60, identityFields: ['tenantCode', 'providerCode', 'providerAccountCode'] },
                resend: { limit: 3, windowSeconds: 600, identityFields: ['tenantCode', 'type', 'refId'] },
                documentAccess: { limit: 30, windowSeconds: 60, identityFields: ['tenantCode', 'caseCode', 'documentCode', 'actorReference'] },
                provider: { limit: 60, windowSeconds: 60, identityFields: ['tenantCode', 'providerCode', 'providerAccountCode'] }
            }
        },
        safeErrors: { invalidRequest: 'KYC_INVALID_REQUEST', forbidden: 'KYC_OPERATION_FORBIDDEN', conflict: 'KYC_STATE_CONFLICT', providerUnavailable: 'KYC_PROVIDER_UNAVAILABLE', evidenceRejected: 'KYC_EVIDENCE_REJECTED' },
        responseMapping: {
            default: { decision: 'ERROR', message: 'The verification operation could not be completed.' },
            SUC_TKN_00001: { decision: 'SUCCESS', message: 'Verification completed successfully.' },
            ERR_TKN_00001: { decision: 'ERROR', message: 'The verification challenge expired.' },
            ERR_TKN_00002: { decision: 'ERROR', message: 'No active verification challenge is available.' },
            ERR_TKN_00003: { decision: 'RETRY', message: 'The verification value is invalid.' }
        }
    }
};
