/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */

/* Nodics - governed by the root LICENSE. */
/** @module payment/test/paymentRefundAdjustmentContract @description Protects append-only governed finance adjustments and Refund exception closure. @layer test @owner payment */
const assert = require('assert'); const properties = require('../config/properties'); global.CONFIG = { get: key => key === 'payment' ? properties.payment : undefined }; global.SERVICE = {};
SERVICE.DefaultPaymentPolicyService = require('../src/service/policy/defaultPaymentPolicyService'); let records = [{ enterpriseCode: 'ent-1', transactionCode: 'refund-failed-1', idempotencyKey: 'provider-refund-1', providerCode: 'stripe', paymentModeCode: 'CARD', paymentGroupCode: 'card-1', orderCode: 'order-1', refundCode: 'refund-1', operation: 'REFUND', amount: '10', currencyCode: 'USD', status: 'FAILED' }];
SERVICE.DefaultPaymentTransactionService = { get: async request => ({ result: records.filter(value => Object.entries(request.query).every(([key,item]) => value[key] === item)) }), save: async request => { records.push(request.model); return { result: [request.model] }; } };
const service = require('../src/service/refund/defaultPaymentRefundAdjustmentService'); const access = body => ({ tenant: 'default', authData: { tokenType: 'access', principalId: 'finance-1', enterpriseCode: 'ent-1' }, body: Object.assign({ entCode: 'ent-1', orderCode: 'order-1', refundCode: 'refund-1', approvalEvidenceCode: 'approval-1', reasonCode: 'PROVIDER_OFFLINE' }, body) });
(async () => { let adjusted = await service.adjust(access({ idempotencyKey: 'adjust-1', adjustmentType: 'CREDIT', amount: '10.00', currencyCode: 'USD', originalTransactionCode: 'refund-failed-1' })); assert.strictEqual(adjusted.operation, 'ADJUSTMENT'); assert.strictEqual(adjusted.status, 'RECONCILED'); assert.strictEqual(records.length, 2); let replay = await service.adjust(access({ idempotencyKey: 'adjust-1', adjustmentType: 'CREDIT', amount: '10.00', currencyCode: 'USD' })); assert.strictEqual(replay.idempotent, true); assert.strictEqual(records.length, 2); let alternate = await service.adjust(access({ idempotencyKey: 'adjust-wallet-1', adjustmentType: 'CREDIT', amount: '10.00', currencyCode: 'USD', originalTransactionCode: 'refund-failed-1', alternateDestinationType: 'WALLET', exceptionPolicyCode: 'cod-wallet-exception', customerCommunicationEvidenceCode: 'notification-1' })); assert.strictEqual(alternate.paymentModeCode, 'WALLET'); assert.strictEqual(alternate.providerCode, 'defaultWalletProvider'); assert.strictEqual(alternate.recoveryAction, 'ALTERNATE_REFUND_DESTINATION'); assert.strictEqual(alternate.exceptionPolicyCode, 'cod-wallet-exception'); await assert.rejects(() => service.adjust(access({ idempotencyKey: 'adjust-wallet-unsafe', adjustmentType: 'CREDIT', amount: '10.00', currencyCode: 'USD', originalTransactionCode: 'refund-failed-1', alternateDestinationType: 'WALLET', exceptionPolicyCode: 'cod-wallet-exception' })), /customer communication evidence/); let closed = await service.closeException(access({ idempotencyKey: 'close-1', exceptionTransactionCode: 'refund-failed-1', adjustmentTransactionCode: adjusted.transactionCode })); assert.strictEqual(closed.operation, 'RECONCILE'); assert.strictEqual(closed.recoveryStatus, 'EXCEPTION_CLOSED'); let maker = access({ idempotencyKey: 'adjust-2', adjustmentType: 'CREDIT', amount: '1', currencyCode: 'USD', requesterCode: 'finance-1' }); await assert.rejects(() => service.adjust(maker), /cannot approve/); let attack = access({ idempotencyKey: 'adjust-3', adjustmentType: 'CREDIT', amount: '1', currencyCode: 'USD', providerPayload: { secret: true } }); await assert.rejects(() => service.adjust(attack), /must not contain/); const routes = require('../src/router/routers').payment.refundOperations; assert.strictEqual(routes.adjust.permission, 'payment.refund.finance.adjust'); assert.strictEqual(routes.closeException.permission, 'payment.refund.finance.closeException'); console.log('Payment Refund adjustment and exception contract validated'); })().catch(error => { console.error(error); process.exit(1); });
