/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is the confidential and proprietary information of Nodics ("Confidential Information").
    You shall not disclose such Confidential Information and shall use it only in accordance with the
    terms of the license agreement you entered into with Nodics.

 */
/** @module inventory/test/inventoryExternalProviderContract @description Validates disabled-by-default provider transport, operation allow-listing, service identity, idempotency, and durable outcomes. @layer test @owner inventory */
const assert = require('assert'); const inventory = require('../config/properties').inventory; class NodicsError extends Error { constructor(code, message) { super(message || code); this.code = code; } } global.CLASSES = { NodicsError }; global.CONFIG = { get: key => key === 'inventory' ? inventory : undefined }; global.SERVICE = {}; global.NODICS = { getInternalAuthToken: () => 'service-token' }; SERVICE.DefaultInventoryEnterpriseScopeService = require('../src/service/foundation/defaultInventoryEnterpriseScopeService'); let records = []; let outbound; SERVICE.DefaultStockProviderOperationService = { get: async request => ({ result: records.filter(value => value.code === request.query.code) }), save: async request => { records.push(Object.assign({}, request.model)); }, update: async request => { Object.assign(records.find(value => value.code === request.query.code), request.model); } }; SERVICE.DefaultModuleService = { buildRequest: options => options, fetch: async descriptor => { outbound = descriptor; return { code: 'WMS_ACCEPTED' }; } }; const service = require('../src/service/provider/defaultInventoryExternalProviderService'); let authData = { tokenType: 'service', enterprise: { code: 'e1' } };
(async () => { await assert.rejects(service.invoke({ authData, provider: { providerCode: 'wms', operation: 'receipt', idempotencyKey: 'i1' } }), error => error.code === 'ERR_INV_00049'); inventory.externalProviders.enabled = true; inventory.externalProviders.providers.wms = { type: 'WMS', moduleName: 'wmsConnector', connectionName: 'wms', operations: ['receipt'] }; let result = await service.invoke({ tenant: 't1', authData, provider: { providerCode: 'wms', operation: 'receipt', idempotencyKey: 'i1', payload: { stockCode: 's1' } } }); assert.strictEqual(result.state, 'COMPLETED'); assert.strictEqual(outbound.moduleName, 'wmsConnector'); assert.strictEqual(outbound.header.Authorization, 'Bearer service-token'); assert.strictEqual(outbound.idempotencyKey, 'i1'); await service.invoke({ tenant: 't1', authData, provider: { providerCode: 'wms', operation: 'receipt', idempotencyKey: 'i1' } }); assert.strictEqual(records.length, 1); await assert.rejects(service.invoke({ authData: { tokenType: 'access', enterprise: { code: 'e1' } }, provider: { providerCode: 'wms', operation: 'receipt', idempotencyKey: 'i2' } }), error => error.code === 'ERR_INV_00051'); inventory.externalProviders.enabled = false; delete inventory.externalProviders.providers.wms; console.log('Inventory external provider contract validated'); })().catch(error => { console.error(error); process.exit(1); });
