/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is the confidential and proprietary information of Nodics ("Confidential Information").
    You shall not disclose such Confidential Information and shall use it only in accordance with the
    terms of the license agreement you entered into with Nodics.

 */
/** @module inventory/test/stockMovementCheckpointContract @description Validates immutable checkpoint creation, contiguous reconstruction, boundaries, and service identity. @layer test @owner inventory */
const assert = require('assert'); const inventory = require('../config/properties').inventory; class NodicsError extends Error { constructor(code, message) { super(message || code); this.code = code; } } global.CLASSES = { NodicsError }; global.CONFIG = { get: key => key === 'inventory' ? inventory : undefined }; global.SERVICE = {};
SERVICE.DefaultInventoryEnterpriseScopeService = require('../src/service/foundation/defaultInventoryEnterpriseScopeService'); SERVICE.DefaultExactUnitsService = require('../../../gCore/units/src/service/exact/defaultExactUnitsService'); let checkpoints = []; let balance = { code: 's1', enterpriseCode: 'e1', quantity: '12', reservedQuantity: '1', unitCode: 'EA', scale: 0, revision: 2, lastMovementCode: 'm2' }; let movements = [];
SERVICE.DefaultStockBalanceService = { get: async () => ({ result: [balance] }) }; SERVICE.DefaultStockMovementRecordService = { get: async request => ({ result: request.query.state === 'PENDING' ? [] : movements }) }; SERVICE.DefaultStockMovementCheckpointService = { get: async request => ({ result: request.query.code ? checkpoints.filter(value => value.code === request.query.code) : checkpoints.slice().sort((a, b) => b.balanceRevision - a.balanceRevision) }), save: async request => { checkpoints.push(request.model); } }; const service = require('../src/service/reconciliation/defaultStockMovementCheckpointOrchestrationService'); const authData = { tokenType: 'service', enterprise: { code: 'e1' } };
(async () => { let checkpoint = await service.create({ tenant: 't1', authData, checkpoint: { stockCode: 's1' } }); assert.strictEqual(checkpoint.quantity, '12'); balance = Object.assign({}, balance, { quantity: '15', revision: 4 }); movements = [{ code: 'm3', expectedRevision: 2, resultingRevision: 3, normalizedDelta: '2' }, { code: 'm4', expectedRevision: 3, resultingRevision: 4, normalizedDelta: '1' }]; let result = await service.reconstruct({ tenant: 't1', authData, checkpoint: { stockCode: 's1' } }); assert.strictEqual(result.expectedQuantity, '15'); assert.strictEqual(result.consistent, true); assert.strictEqual(result.reservationReconstructionSupported, false); movements[1].expectedRevision = 9; await assert.rejects(service.reconstruct({ tenant: 't1', authData, checkpoint: { stockCode: 's1' } }), error => error.code === 'ERR_INV_00049'); await assert.rejects(service.create({ authData: { tokenType: 'access', enterprise: { code: 'e1' } }, checkpoint: { stockCode: 's1' } }), error => error.code === 'ERR_INV_00051'); console.log('Inventory Stock Movement checkpoint contract validated'); })().catch(error => { console.error(error); process.exit(1); });
