/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */

/** @module payment/config/properties @description Layered payment policy and BackOffice metadata. @layer configuration @owner payment */
module.exports = {
  payment: {
    paymentPolicy: {
      operations: ["AUTHORIZE", "CAPTURE", "REFUND", "VOID", "DEFER", "RECONCILE"],
      transactionStatuses: ["REQUESTED", "AUTHORIZED", "CAPTURED", "REFUNDED", "VOIDED", "DEFERRED", "RECONCILED", "FAILED"],
      providerStatuses: ["DRAFT", "ACTIVE", "SUSPENDED", "INACTIVE", "RETIRED"],
      connectorPolicy: {
        requireConnectorReferenceForGateway: true,
        connectorCodePattern: "^[A-Za-z][A-Za-z0-9._:-]{0,127}$",
        configRefPattern: "^[A-Za-z][A-Za-z0-9._:-]{0,255}$",
        forbiddenReferenceTerms: ["secret", "password", "apikey", "api_key", "token", "credential", "pan", "cvv"],
        rotationAuthority: "connector-secret-authority",
      },
      methods: {
        CARD: {
          methodCode: "CARD",
          displayName: "Card payment",
          defaultOperation: "AUTHORIZE",
          providerRequired: true,
          gatewayRequired: true,
          defaultProviderCode: "defaultCardProvider",
          allowedProviderTypes: ["CARD_GATEWAY"],
        },
        WALLET: {
          methodCode: "WALLET",
          displayName: "Wallet payment",
          defaultOperation: "AUTHORIZE",
          providerRequired: true,
          gatewayRequired: true,
          defaultProviderCode: "defaultWalletProvider",
          allowedProviderTypes: ["WALLET"],
        },
        ADVANCE: {
          methodCode: "ADVANCE",
          displayName: "Advance payment",
          defaultOperation: "AUTHORIZE",
          providerRequired: true,
          gatewayRequired: true,
          defaultProviderCode: "defaultAdvanceProvider",
          allowedProviderTypes: ["CARD_GATEWAY", "WALLET", "MANUAL"],
        },
        COD: {
          methodCode: "COD",
          displayName: "Cash on delivery",
          defaultOperation: "DEFER",
          providerRequired: true,
          gatewayRequired: false,
          defaultProviderCode: "deferredPaymentProvider",
          allowedProviderTypes: ["DEFERRED"],
        },
        BANK_TRANSFER: {
          methodCode: "BANK_TRANSFER",
          displayName: "Bank transfer",
          defaultOperation: "DEFER",
          providerRequired: true,
          gatewayRequired: false,
          defaultProviderCode: "deferredPaymentProvider",
          allowedProviderTypes: ["DEFERRED", "MANUAL"],
        },
        ACCOUNT_CREDIT: {
          methodCode: "ACCOUNT_CREDIT",
          displayName: "Account credit",
          defaultOperation: "AUTHORIZE",
          providerRequired: true,
          gatewayRequired: false,
          defaultProviderCode: "manualPaymentProvider",
          allowedProviderTypes: ["MANUAL"],
        },
        OFFLINE: {
          methodCode: "OFFLINE",
          displayName: "Offline payment",
          defaultOperation: "AUTHORIZE",
          providerRequired: true,
          gatewayRequired: false,
          defaultProviderCode: "manualPaymentProvider",
          allowedProviderTypes: ["MANUAL"],
        },
      },
      providers: {
        defaultCardProvider: {
          providerCode: "defaultCardProvider",
          providerType: "CARD_GATEWAY",
          displayName: "Default card provider",
          methodCodes: ["CARD", "ADVANCE"],
          operations: ["AUTHORIZE", "CAPTURE", "REFUND", "VOID", "RECONCILE"],
          adapterService: "DefaultCardPaymentProviderAdapterService",
          policyService: "DefaultPaymentProviderPolicyService",
          status: "ACTIVE",
        },
        defaultWalletProvider: {
          providerCode: "defaultWalletProvider",
          providerType: "WALLET",
          displayName: "Default wallet provider",
          methodCodes: ["WALLET"],
          operations: ["AUTHORIZE", "CAPTURE", "REFUND", "VOID", "RECONCILE"],
          adapterService: "DefaultCardPaymentProviderAdapterService",
          policyService: "DefaultPaymentProviderPolicyService",
          status: "ACTIVE",
        },
        defaultAdvanceProvider: {
          providerCode: "defaultAdvanceProvider",
          providerType: "CARD_GATEWAY",
          displayName: "Default advance payment provider",
          methodCodes: ["ADVANCE"],
          operations: ["AUTHORIZE", "CAPTURE", "REFUND", "VOID", "RECONCILE"],
          adapterService: "DefaultCardPaymentProviderAdapterService",
          policyService: "DefaultPaymentProviderPolicyService",
          status: "ACTIVE",
        },
        deferredPaymentProvider: {
          providerCode: "deferredPaymentProvider",
          providerType: "DEFERRED",
          displayName: "Deferred payment provider",
          methodCodes: ["COD", "BANK_TRANSFER"],
          operations: ["DEFER", "REFUND", "VOID", "RECONCILE"],
          adapterService: "DefaultDeferredPaymentProviderAdapterService",
          policyService: "DefaultPaymentProviderPolicyService",
          status: "ACTIVE",
        },
        manualPaymentProvider: {
          providerCode: "manualPaymentProvider",
          providerType: "MANUAL",
          displayName: "Manual payment provider",
          methodCodes: ["ACCOUNT_CREDIT", "OFFLINE", "ADVANCE"],
          operations: ["AUTHORIZE", "CAPTURE", "REFUND", "VOID", "RECONCILE"],
          adapterService: "DefaultManualPaymentProviderAdapterService",
          policyService: "DefaultPaymentProviderPolicyService",
          status: "ACTIVE",
        },
      },
      deferredPaymentModes: ["COD", "BANK_TRANSFER"],
      manualPaymentModes: ["ACCOUNT_CREDIT", "OFFLINE"],
      defaultProviderByPaymentMode: {
        CARD: "defaultCardProvider",
        WALLET: "defaultWalletProvider",
        ADVANCE: "defaultAdvanceProvider",
        COD: "deferredPaymentProvider",
        BANK_TRANSFER: "deferredPaymentProvider",
        ACCOUNT_CREDIT: "manualPaymentProvider",
        OFFLINE: "manualPaymentProvider",
      },
      gatewayRequiredModes: ["CARD", "WALLET", "ADVANCE"],
      refundCalculation: {
        defaultStrategy: "SUM_PAYMENT_ALLOCATIONS",
        allowExplicitAmount: true,
        explicitAmountMustNotExceedEligible: true,
        includeShipping: false,
        includeTax: true,
        includeDiscount: true,
        maximumAggregateRecords: 1000,
      },
      refundRecovery: {
        enabled: true,
        retryStatuses: ["REQUESTED", "FAILED"],
        terminalSuccessStatuses: ["REFUNDED"],
        maximumRetries: 3,
        failureMessageLimit: 240,
      },
      defaultCurrencyScale: 2,
      moneyPattern: "^(0|[1-9][0-9]*)(\\.[0-9]+)?$",
      maximumDigits: 38,
      maximumScale: 18,
      failureMessageLimit: 240,
      maximumAggregateRecords: 1000,
    },
  },
  backofficeCapabilities: {
    payment: {
      enabled: true,
      capabilityId: "payment-management",
      displayName: "Payment",
      category: "commerce",
      icon: "payment",
      contractVersion: 1,
      minimumClientContractVersion: 1,
      roles: ["FUNCTIONAL_CAPABILITY_PROVIDER"],
      discovery: {
        openApiPath: "/nodics/system/v0/contract/openapi/internal",
        contractVersion: 1,
      },
      requiredPermissions: ["payment.backoffice.read"],
      navigation: [
        {
          id: "payment-operations",
          label: "Payment Operations",
          route: "/commerce/payments",
          icon: "payment",
          order: 610,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["payment.backoffice.read"],
          workbenchTarget: { moduleName: "payment", schemaName: "paymentTransaction" },
          lifecycleActions: [
            {
              id: "review-failed-payments",
              label: "Review failed payments",
              intent: "RECONCILE",
              permission: "payment.backoffice.manage",
              summary:
                "Open the Payment-owned exception workflow for failed or recoverable payment evidence.",
              targetStatuses: ["FAILED", "REQUESTED"],
              featureState: "PREVIEW",
            },
          ],
          help: {
            summary:
              "Operate payment methods, providers, transactions, refunds, and reconciliation through the Payment capability.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "payment-methods",
          parentId: "payment-operations",
          label: "Payment Methods",
          route: "/commerce/payments/methods",
          icon: "payment",
          order: 611,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["payment.backoffice.read"],
          workbenchTarget: { moduleName: "payment", schemaName: "paymentMethod" },
          lifecycleActions: [
            {
              id: "create-payment-method",
              label: "Create method",
              intent: "CREATE",
              permission: "payment.backoffice.manage",
              summary:
                "Create an enterprise-scoped payment method through the Payment authority.",
              featureState: "PREVIEW",
            },
            {
              id: "retire-payment-method",
              label: "Retire method",
              intent: "UPDATE",
              permission: "payment.backoffice.manage",
              summary:
                "Retire a method after dependency and active-checkout validation.",
              targetStatuses: ["ACTIVE"],
              featureState: "PREVIEW",
            },
          ],
          help: {
            summary:
              "Review business-facing payment methods such as Card, COD, Wallet, Advance, or customer-specific methods.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "payment-transactions",
          parentId: "payment-operations",
          label: "Payment Transactions",
          route: "/commerce/payments/transactions",
          icon: "payment",
          order: 612,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["payment.backoffice.read"],
          workbenchTarget: { moduleName: "payment", schemaName: "paymentTransaction" },
          lifecycleActions: [
            {
              id: "retry-payment",
              label: "Retry payment",
              intent: "RETRY",
              permission: "payment.backoffice.manage",
              summary:
                "Retry a recoverable provider operation through Payment-owned retry policy.",
              targetStatuses: ["FAILED", "REQUESTED"],
              featureState: "PREVIEW",
            },
            {
              id: "reconcile-payment",
              label: "Reconcile payment",
              intent: "RECONCILE",
              permission: "payment.backoffice.manage",
              summary:
                "Compare safe Payment evidence with provider reconciliation output.",
              targetStatuses: ["FAILED", "REQUESTED", "AUTHORIZED", "CAPTURED"],
              featureState: "PREVIEW",
            },
          ],
          help: {
            summary:
              "Review authorization, capture, refund, void, deferred, and failed payment evidence.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "payment-providers",
          parentId: "payment-operations",
          label: "Payment Providers",
          route: "/commerce/payments/providers",
          icon: "payment",
          order: 613,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["payment.backoffice.read"],
          workbenchTarget: { moduleName: "payment", schemaName: "paymentProvider" },
          workbenchPresentation: {
            defaultColumns: [
              "providerCode",
              "displayName",
              "providerType",
              "methodCodes",
              "operations",
              "adapterService",
              "connectorCode",
              "status",
            ],
            hiddenFields: [
              "notes",
            ],
            editableFields: [
              "enterpriseCode",
              "providerCode",
              "displayName",
              "providerType",
              "methodCodes",
              "operations",
              "adapterService",
              "policyService",
              "connectorCode",
              "configRef",
              "status",
              "businessEditable",
              "notes",
            ],
            readonlyFields: [
              "configurationSource",
              "created",
              "updated",
              "createdBy",
              "updatedBy",
            ],
            forbiddenFields: [
              "secret",
              "password",
              "apiKey",
              "accessToken",
              "refreshToken",
              "cardNumber",
              "cvv",
              "pan",
              "rawGatewayPayload",
              "providerPayload",
            ],
            quickFilters: [
              {
                id: "active",
                label: "Active",
                field: "status",
                value: "ACTIVE",
              },
              {
                id: "card-gateways",
                label: "Card gateways",
                field: "providerType",
                value: "CARD_GATEWAY",
              },
              {
                id: "wallets",
                label: "Wallets",
                field: "providerType",
                value: "WALLET",
              },
              {
                id: "deferred",
                label: "Deferred",
                field: "providerType",
                value: "DEFERRED",
              },
            ],
          },
          lifecycleActions: [
            {
              id: "create-payment-provider",
              label: "Create provider",
              intent: "CREATE",
              permission: "payment.backoffice.manage",
              ownerModule: "payment",
              handlerAction: "DefaultPaymentProviderLifecycleService.validateProvider",
              operationRoute: "/providers/lifecycle",
              summary:
                "Register a safe provider identity and adapter reference. Secrets remain in the configured secret authority.",
              featureState: "PREVIEW",
            },
            {
              id: "validate-payment-provider",
              label: "Validate provider",
              intent: "VALIDATE",
              permission: "payment.backoffice.manage",
              ownerModule: "payment",
              handlerAction: "DefaultPaymentProviderLifecycleService.validateProvider",
              operationRoute: "/providers/lifecycle",
              summary:
                "Validate safe provider metadata, adapter availability, and connector references without reading secrets.",
              targetStatuses: ["DRAFT", "ACTIVE", "SUSPENDED"],
              featureState: "PREVIEW",
            },
            {
              id: "test-payment-provider",
              label: "Test provider",
              intent: "TEST",
              permission: "payment.backoffice.manage",
              ownerModule: "payment",
              handlerAction: "DefaultPaymentProviderLifecycleService.testProvider",
              operationRoute: "/providers/lifecycle",
              summary:
                "Run a safe provider contract test through normalized Payment evidence.",
              targetStatuses: ["DRAFT", "ACTIVE"],
              featureState: "PREVIEW",
            },
            {
              id: "activate-payment-provider",
              label: "Activate provider",
              intent: "ACTIVATE",
              permission: "payment.backoffice.manage",
              ownerModule: "payment",
              handlerAction: "DefaultPaymentProviderLifecycleService.activateProvider",
              operationRoute: "/providers/lifecycle",
              summary:
                "Activate a provider only after safe metadata and adapter validation.",
              targetStatuses: ["DRAFT", "SUSPENDED", "INACTIVE"],
              featureState: "PREVIEW",
            },
            {
              id: "suspend-payment-provider",
              label: "Suspend provider",
              intent: "UPDATE",
              permission: "payment.backoffice.manage",
              ownerModule: "payment",
              handlerAction: "DefaultPaymentProviderLifecycleService.suspendProvider",
              operationRoute: "/providers/lifecycle",
              summary:
                "Suspend an enterprise provider through Payment governance and checkout dependency checks.",
              targetStatuses: ["ACTIVE"],
              featureState: "PREVIEW",
            },
            {
              id: "request-provider-connector-rotation",
              label: "Request connector rotation",
              intent: "ROTATE_CONNECTOR",
              permission: "payment.backoffice.manage",
              ownerModule: "payment",
              handlerAction: "DefaultPaymentProviderLifecycleService.requestConnectorRotation",
              operationRoute: "/providers/lifecycle",
              summary:
                "Request credential rotation through the connector or secret authority without exposing secret values.",
              targetStatuses: ["ACTIVE", "SUSPENDED"],
              featureState: "PREVIEW",
            },
          ],
          help: {
            summary:
              "Review safe provider identities, supported operations, and lifecycle status. Provider secrets are never stored here.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "payment-refunds-reconciliation",
          parentId: "payment-operations",
          label: "Refunds & Reconciliation",
          route: "/commerce/payments/refunds-reconciliation",
          icon: "payment",
          order: 614,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["payment.backoffice.read"],
          workbenchTarget: { moduleName: "payment", schemaName: "paymentTransaction" },
          workbenchPresentation: {
            defaultColumns: [
              "transactionCode",
              "operation",
              "status",
              "providerCode",
              "orderCode",
              "paymentGroupCode",
              "amount",
              "currencyCode",
              "recoveryStatus",
            ],
            quickFilters: [
              {
                id: "refunds",
                label: "Refunds",
                field: "operation",
                value: "REFUND",
              },
              {
                id: "reconciliation",
                label: "Reconciliation",
                field: "operation",
                value: "RECONCILE",
              },
              {
                id: "recoverable",
                label: "Recoverable",
                field: "status",
                values: ["FAILED", "REQUESTED"],
              },
            ],
          },
          lifecycleActions: [
            {
              id: "retry-refund",
              label: "Retry refund",
              intent: "RETRY",
              permission: "payment.backoffice.manage",
              summary:
                "Retry a recoverable refund through Payment-owned recovery policy.",
              targetStatuses: ["FAILED", "REQUESTED"],
              featureState: "PREVIEW",
            },
            {
              id: "reconcile-provider-payment",
              label: "Reconcile provider evidence",
              intent: "RECONCILE",
              permission: "payment.backoffice.manage",
              summary:
                "Compare Payment evidence with normalized provider reconciliation output.",
              targetStatuses: ["FAILED", "REQUESTED", "AUTHORIZED", "CAPTURED", "REFUNDED"],
              featureState: "PREVIEW",
            },
          ],
          help: {
            summary:
              "Review refund and reconciliation evidence without exposing raw provider payloads or secrets.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
      ],
    },
  },
};
