/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is the confidential and proprietary information of Nodics ("Confidential Information").
    You shall not disclose such Confidential Information and shall use it only in accordance with the
    terms of the license agreement you entered into with Nodics.

 */
/** @module inventory/service/reconciliation/DefaultStockReconciliationService @description Runs bounded dry-first Inventory consistency audits and approved corrective movements. @layer service @owner inventory */
module.exports = {
    /** Initializes reconciliation. */ init: function () { return Promise.resolve(true); }, /** Completes initialization. */ postInit: function () { return Promise.resolve(true); },
    /** Allows internal persistence. */ authorizeMutation: function (request) { return request && request._stockReconciliationMutationAuthorized === true ? Promise.resolve(true) : Promise.reject(new CLASSES.NodicsError('ERR_INV_00048', 'Reconciliation evidence is orchestration-owned')); },
    /** Rejects evidence deletion. */ rejectDelete: function () { return Promise.reject(new CLASSES.NodicsError('ERR_INV_00048', 'Reconciliation evidence cannot be deleted')); },
    /** Extracts generated result items. */ items: function (response) { return response && Array.isArray(response.result) ? response.result : []; },
    /** Negates exact quantity. */ negate: function (value) { let parsed = SERVICE.DefaultExactUnitsService.parse(value); return SERVICE.DefaultExactUnitsService.format(-parsed.unscaled, parsed.scale); },
    /** Creates one deterministic finding unless it already exists. */ finding: async function (run, type, severity, subjectType, subjectCode, expected, actual, repairable, request) {
        let code = SERVICE.DefaultInventoryEnterpriseScopeService.buildIdentity(request.enterpriseCode, 'reconciliationFinding', [run.idempotencyKey, type, subjectCode]);
        let existing = this.items(await SERVICE.DefaultStockReconciliationFindingService.get({ tenant: request.tenant, authData: request.authData, query: { code, enterpriseCode: request.enterpriseCode }, searchOptions: { limit: 1 } }))[0]; if (existing) { if (SERVICE.DefaultStockReconciliationWorkflowService) await SERVICE.DefaultStockReconciliationWorkflowService.start(existing, request); return existing; }
        let model = { code, active: true, enterpriseCode: request.enterpriseCode, runCode: run.runCode, findingCode: code, type, severity, state: 'OPEN', subjectType, subjectCode, expected, actual, repairable };
        await SERVICE.DefaultStockReconciliationFindingService.save({ tenant: request.tenant, authData: request.authData, model, _stockReconciliationMutationAuthorized: true });
        if (SERVICE.DefaultStockReconciliationWorkflowService) await SERVICE.DefaultStockReconciliationWorkflowService.start(model, request);
        return model;
    },
    /** Parses a persisted multi-source cursor without trusting caller-shaped database input. */
    cursor: function (value) { try { let parsed = JSON.parse(value || '{}'); return ['balances', 'allocations', 'transfers', 'movements', 'reservations'].reduce((result, key) => { result[key] = Math.max(0, Number(parsed[key]) || 0); return result; }, {}); } catch (error) { throw new CLASSES.NodicsError('ERR_INV_00050', 'Reconciliation cursor is invalid'); } },
    /** Returns one bounded page from an authoritative generated service. */
    page: async function (service, request, query, offset, limit) { return this.items(await service.get({ tenant: request.tenant, authData: request.authData, query: Object.assign({ enterpriseCode: request.enterpriseCode }, query || {}), searchOptions: { pageSize: limit, pageNumber: Math.floor(offset / limit) + 1, sort: { code: 1 } } })); },
    /** Adds exact canonical quantities. */
    sum: function (values, scale) { let total = SERVICE.DefaultExactUnitsService.multiplyRational('0', '1', '1', scale, 'UNNECESSARY'); values.forEach(value => { total = SERVICE.DefaultExactUnitsService.add(total, value, scale, 'UNNECESSARY'); }); return total; },
    /** Runs one bounded, resumable, dry-first scan across Stock-owned operational evidence. */
    scan: async function (request) {
        request.enterpriseCode = SERVICE.DefaultInventoryEnterpriseScopeService.resolveEnterpriseCode(request); let input = request.reconciliation || {}; let policy = ((CONFIG.get('inventory') || {}).stockReconciliation) || {};
        if (!request.authData || request.authData.tokenType !== 'service' || !input.idempotencyKey) throw new CLASSES.NodicsError('ERR_INV_00051', 'Reconciliation scan requires service identity and idempotency key');
        let runCode = SERVICE.DefaultInventoryEnterpriseScopeService.buildIdentity(request.enterpriseCode, 'reconciliationRun', [input.idempotencyKey]); let existing = this.items(await SERVICE.DefaultStockReconciliationRunService.get({ tenant: request.tenant, authData: request.authData, query: { code: runCode, enterpriseCode: request.enterpriseCode }, searchOptions: { limit: 1 } }))[0]; if (existing && existing.state === 'COMPLETED') return existing;
        let run = existing || { code: runCode, active: true, enterpriseCode: request.enterpriseCode, runCode, idempotencyKey: input.idempotencyKey, state: 'RUNNING', dryRun: input.dryRun === undefined ? policy.dryRunDefault !== false : input.dryRun === true, scannedCount: 0, findingCount: 0, repairCount: 0, startedAt: new Date() };
        if (!existing) await SERVICE.DefaultStockReconciliationRunService.save({ tenant: request.tenant, authData: request.authData, model: run, _stockReconciliationMutationAuthorized: true });
        let limit = Number(policy.batchSize || 500); let cursor = this.cursor(run.cursor); let findings = [];
        let balances = await this.page(SERVICE.DefaultStockBalanceService, request, {}, cursor.balances, limit);
        let allocations = await this.page(SERVICE.DefaultStockAllocationService, request, {}, cursor.allocations, limit);
        let transfers = await this.page(SERVICE.DefaultStockTransferService, request, {}, cursor.transfers, limit);
        let movements = await this.page(SERVICE.DefaultStockMovementRecordService, request, { state: 'PENDING' }, cursor.movements, limit);
        let reservationsPending = await this.page(SERVICE.DefaultStockReservationService, request, { state: { $in: ['PENDING', 'RELEASE_PENDING'] } }, cursor.reservations, limit);
        for (let balance of balances) {
            let reservations = this.items(await SERVICE.DefaultStockReservationService.get({ tenant: request.tenant, authData: request.authData, query: { enterpriseCode: request.enterpriseCode, stockCode: balance.code, state: { $in: ['ACTIVE', 'CONSUMED', 'RELEASE_PENDING'] } }, searchOptions: { limit } }));
            let expectedReserved = SERVICE.DefaultExactUnitsService.multiplyRational('0', '1', '1', balance.scale, 'UNNECESSARY'); reservations.forEach(value => { expectedReserved = SERVICE.DefaultExactUnitsService.add(expectedReserved, value.quantity, balance.scale, 'UNNECESSARY'); });
            if (expectedReserved !== balance.reservedQuantity) findings.push(await this.finding(run, 'RESERVED_QUANTITY_MISMATCH', 'HIGH', 'stockBalance', balance.code, { reservedQuantity: expectedReserved }, { reservedQuantity: balance.reservedQuantity }, false, request));
            if (SERVICE.DefaultExactUnitsService.parse(balance.quantity).unscaled < 0n) findings.push(await this.finding(run, 'NEGATIVE_BALANCE', 'CRITICAL', 'stockBalance', balance.code, { quantity: SERVICE.DefaultExactUnitsService.multiplyRational('0', '1', '1', balance.scale, 'UNNECESSARY') }, { quantity: balance.quantity, revision: balance.revision, warehouseCode: balance.warehouseCode, itemType: balance.itemType, itemCode: balance.itemCode, unitCode: balance.unitCode, scale: balance.scale }, true, request));
        }
        for (let allocation of allocations) {
            let allocated = this.sum((allocation.assignments || []).map(value => value.quantity), allocation.scale); let requestedAccounted = this.sum([allocation.allocatedQuantity, allocation.backorderedQuantity], allocation.scale);
            if (allocated !== allocation.allocatedQuantity || requestedAccounted !== allocation.requestedQuantity || SERVICE.DefaultExactUnitsService.parse(SERVICE.DefaultExactUnitsService.add(allocation.allocatedQuantity, this.negate(allocation.fulfilledQuantity), allocation.scale, 'UNNECESSARY')).unscaled < 0n) findings.push(await this.finding(run, 'ALLOCATION_QUANTITY_MISMATCH', 'HIGH', 'stockAllocation', allocation.code, { allocatedQuantity: allocated, requestedQuantity: requestedAccounted, fulfilledAtMostAllocated: true }, { allocatedQuantity: allocation.allocatedQuantity, requestedQuantity: allocation.requestedQuantity, fulfilledQuantity: allocation.fulfilledQuantity }, false, request));
        }
        for (let transfer of transfers) {
            let accounted = this.sum([transfer.receivedQuantity, transfer.damagedQuantity, transfer.lostQuantity], transfer.scale); let dispatchRemaining = SERVICE.DefaultExactUnitsService.add(transfer.requestedQuantity, this.negate(transfer.dispatchedQuantity), transfer.scale, 'UNNECESSARY'); let receiptRemaining = SERVICE.DefaultExactUnitsService.add(transfer.dispatchedQuantity, this.negate(accounted), transfer.scale, 'UNNECESSARY');
            if (SERVICE.DefaultExactUnitsService.parse(dispatchRemaining).unscaled < 0n || SERVICE.DefaultExactUnitsService.parse(receiptRemaining).unscaled < 0n) findings.push(await this.finding(run, 'TRANSFER_QUANTITY_MISMATCH', 'CRITICAL', 'stockTransfer', transfer.code, { dispatchedAtMostRequested: true, accountedAtMostDispatched: true }, { requestedQuantity: transfer.requestedQuantity, dispatchedQuantity: transfer.dispatchedQuantity, accountedQuantity: accounted }, false, request));
        }
        for (let movement of movements) findings.push(await this.finding(run, 'PENDING_MOVEMENT', 'HIGH', 'stockMovementRecord', movement.code, { terminalState: true }, { state: movement.state, failureCode: movement.failureCode }, false, request));
        let cutoff = Date.now() - Number(policy.pendingAgeSeconds || 300) * 1000;
        for (let reservation of reservationsPending) { let changedAt = new Date(reservation.updatedAt || reservation.createdAt || 0).getTime(); if (changedAt <= cutoff) findings.push(await this.finding(run, 'STALE_RESERVATION_TRANSITION', 'HIGH', 'stockReservation', reservation.code, { terminalOrActiveState: true }, { state: reservation.state, changedAt: reservation.updatedAt || reservation.createdAt }, false, request)); }
        let totalFindings = Number(run.findingCount || 0) + findings.length; if (totalFindings > Number(policy.maximumFindings || 5000)) throw new CLASSES.NodicsError('ERR_INV_00050', 'Reconciliation finding boundary exceeded');
        let pages = { balances, allocations, transfers, movements, reservations: reservationsPending }; let next = {}; let complete = true; Object.keys(pages).forEach(key => { next[key] = cursor[key] + pages[key].length; if (pages[key].length === limit) complete = false; });
        let scanned = Object.values(pages).reduce((count, values) => count + values.length, 0); let state = complete ? 'COMPLETED' : 'PARTIAL'; let patch = { state, cursor: complete ? undefined : JSON.stringify(next), scannedCount: Number(run.scannedCount || 0) + scanned, findingCount: totalFindings }; if (complete) patch.completedAt = new Date();
        await SERVICE.DefaultStockReconciliationRunService.update({ tenant: request.tenant, authData: request.authData, _stockReconciliationMutationAuthorized: true, query: { code: run.code, enterpriseCode: request.enterpriseCode }, model: patch });
        return Object.assign({}, run, patch, { findings });
    },
    /** Records explicit human approval; service and cron identities cannot approve. */
    approve: async function (request) { request.enterpriseCode = SERVICE.DefaultInventoryEnterpriseScopeService.resolveEnterpriseCode(request); if (!request.authData || request.authData.tokenType === 'service') throw new CLASSES.NodicsError('ERR_INV_00051', 'Human identity is required for manual approval'); let input = request.reconciliation || {}; return SERVICE.DefaultStockReconciliationFindingService.update({ tenant: request.tenant, authData: request.authData, _stockReconciliationMutationAuthorized: true, query: { code: input.code, enterpriseCode: request.enterpriseCode, state: 'OPEN' }, model: { state: 'APPROVED', approvalMode: 'MANUAL', approvedBy: request.authData.principalId || request.authData.code, approvedAt: new Date(), workflowCarrierCode: input.workflowCarrierCode, resolutionNote: input.note } }); },
    /** Records a policy-authorized automatic workflow approval without impersonating a human. */
    approveAutomatic: async function (request) { request.enterpriseCode = SERVICE.DefaultInventoryEnterpriseScopeService.resolveEnterpriseCode(request); let input = request.reconciliation || {}; if (!request.authData || request.authData.tokenType !== 'service' || !input.workflowCarrierCode) throw new CLASSES.NodicsError('ERR_INV_00051', 'Automatic approval requires service identity and workflow evidence'); return SERVICE.DefaultStockReconciliationFindingService.update({ tenant: request.tenant, authData: request.authData, _stockReconciliationMutationAuthorized: true, query: { code: input.code, enterpriseCode: request.enterpriseCode, state: 'OPEN' }, model: { state: 'APPROVED', approvalMode: 'AUTOMATIC', approvedBy: 'WORKFLOW:' + input.workflowCarrierCode, approvedAt: new Date(), workflowCarrierCode: input.workflowCarrierCode, resolutionNote: input.note } }); },
    /** Repairs one approved repairable finding exclusively through Stock Movement. */
    repair: async function (request) { request.enterpriseCode = SERVICE.DefaultInventoryEnterpriseScopeService.resolveEnterpriseCode(request); if (!request.authData || request.authData.tokenType !== 'service') throw new CLASSES.NodicsError('ERR_INV_00051', 'Repair execution requires service identity'); let input = request.reconciliation || {}; let finding = this.items(await SERVICE.DefaultStockReconciliationFindingService.get({ tenant: request.tenant, authData: request.authData, query: { code: input.code, enterpriseCode: request.enterpriseCode }, searchOptions: { limit: 1 } }))[0]; if (!finding || finding.state !== 'APPROVED' || finding.repairable !== true || finding.type !== 'NEGATIVE_BALANCE') throw new CLASSES.NodicsError('ERR_INV_00049', 'Finding is not approved and repairable'); let actual = finding.actual; let movement = await SERVICE.DefaultStockMovementService.apply({ tenant: request.tenant, authData: request.authData, stock: { warehouseCode: actual.warehouseCode, itemType: actual.itemType, itemCode: actual.itemCode, unitCode: actual.unitCode, scale: actual.scale }, movement: { idempotencyKey: finding.findingCode + ':repair', movementType: 'CORRECTION', quantity: this.negate(actual.quantity), expectedRevision: actual.revision, reasonCode: 'RECONCILIATION', sourceType: 'STOCK_RECONCILIATION', sourceCode: finding.code } }); await SERVICE.DefaultStockReconciliationFindingService.update({ tenant: request.tenant, authData: request.authData, _stockReconciliationMutationAuthorized: true, query: { code: finding.code, enterpriseCode: request.enterpriseCode, state: 'APPROVED' }, model: { state: 'RESOLVED', repairMovementCode: movement.code, terminalAt: new Date() } }); return { findingCode: finding.code, movementCode: movement.code, state: 'RESOLVED' }; }
};
