/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is the confidential and proprietary information of Nodics ("Confidential Information").
    You shall not disclose such Confidential Information and shall use it only in accordance with the
    terms of the license agreement you entered into with Nodics.

 */
const crypto = require('crypto');
/** @module inventory/service/reconciliation/DefaultStockMovementCheckpointOrchestrationService @description Creates immutable Balance checkpoints and verifies contiguous on-hand Movement history. @layer service @owner inventory */
module.exports = {
    /** Initializes checkpoints. */ init: function () { return Promise.resolve(true); }, /** Completes initialization. */ postInit: function () { return Promise.resolve(true); },
    /** Allows orchestration-owned save. */ authorizeMutation: function (request) { return request && request._stockCheckpointMutationAuthorized === true ? Promise.resolve(true) : Promise.reject(new CLASSES.NodicsError('ERR_INV_00048', 'Checkpoint evidence is orchestration-owned')); },
    /** Rejects checkpoint rewrite or deletion. */ rejectMutation: function () { return Promise.reject(new CLASSES.NodicsError('ERR_INV_00048', 'Checkpoint evidence is immutable')); },
    /** Extracts items. */ items: function (response) { return response && Array.isArray(response.result) ? response.result : []; },
    /** Requires service identity. */ authorize: function (request) { if (!request.authData || request.authData.tokenType !== 'service') throw new CLASSES.NodicsError('ERR_INV_00051', 'Movement checkpoint requires service identity'); request.enterpriseCode = SERVICE.DefaultInventoryEnterpriseScopeService.resolveEnterpriseCode(request); },
    /** Creates an idempotent checkpoint only when no Movement is pending for the Balance. */
    create: async function (request) { this.authorize(request); let input = request.checkpoint || {}; let balance = this.items(await SERVICE.DefaultStockBalanceService.get({ tenant: request.tenant, authData: request.authData, query: { code: input.stockCode, enterpriseCode: request.enterpriseCode }, searchOptions: { limit: 1 } }))[0]; if (!balance) throw new CLASSES.NodicsError('ERR_INV_00049', 'Stock Balance was not found'); let pending = this.items(await SERVICE.DefaultStockMovementRecordService.get({ tenant: request.tenant, authData: request.authData, query: { enterpriseCode: request.enterpriseCode, stockCode: balance.code, state: 'PENDING' }, searchOptions: { limit: 1 } })); if (pending.length) throw new CLASSES.NodicsError('ERR_INV_00049', 'Pending Movement prevents checkpoint creation'); let identity = crypto.createHash('sha256').update(balance.code + ':' + balance.revision).digest('hex'); let code = SERVICE.DefaultInventoryEnterpriseScopeService.buildIdentity(request.enterpriseCode, 'movementCheckpoint', [identity]); let existing = this.items(await SERVICE.DefaultStockMovementCheckpointService.get({ tenant: request.tenant, authData: request.authData, query: { code, enterpriseCode: request.enterpriseCode }, searchOptions: { limit: 1 } }))[0]; if (existing) return existing; let model = { code, active: true, enterpriseCode: request.enterpriseCode, checkpointCode: code, stockCode: balance.code, quantity: balance.quantity, reservedQuantity: balance.reservedQuantity, unitCode: balance.unitCode, scale: balance.scale, balanceRevision: balance.revision, lastMovementCode: balance.lastMovementCode, checkpointAt: new Date(), state: 'ACTIVE' }; await SERVICE.DefaultStockMovementCheckpointService.save({ tenant: request.tenant, authData: request.authData, model, _stockCheckpointMutationAuthorized: true }); return model; },
    /** Reconstructs on-hand from the latest checkpoint and a contiguous APPLIED Movement revision chain. */
    reconstruct: async function (request) { this.authorize(request); let input = request.checkpoint || {}; let checkpoints = this.items(await SERVICE.DefaultStockMovementCheckpointService.get({ tenant: request.tenant, authData: request.authData, query: { enterpriseCode: request.enterpriseCode, stockCode: input.stockCode, state: 'ACTIVE' }, searchOptions: { pageSize: 1, pageNumber: 1, sort: { balanceRevision: -1 } } })); if (!checkpoints.length) throw new CLASSES.NodicsError('ERR_INV_00049', 'Opening checkpoint is required'); let checkpoint = checkpoints[0]; let limit = Number((((CONFIG.get('inventory') || {}).movementCheckpoint || {}).batchSize || 1000)); let movements = this.items(await SERVICE.DefaultStockMovementRecordService.get({ tenant: request.tenant, authData: request.authData, query: { enterpriseCode: request.enterpriseCode, stockCode: input.stockCode, state: 'APPLIED', resultingRevision: { $gt: checkpoint.balanceRevision } }, searchOptions: { pageSize: limit + 1, pageNumber: 1, sort: { resultingRevision: 1 } } })); if (movements.length > limit) throw new CLASSES.NodicsError('ERR_INV_00050', 'Movement reconstruction boundary exceeded'); let quantity = checkpoint.quantity; let revision = Number(checkpoint.balanceRevision); for (let movement of movements) { if (Number(movement.expectedRevision) !== revision || Number(movement.resultingRevision) !== revision + 1) throw new CLASSES.NodicsError('ERR_INV_00049', 'Movement revision history is not contiguous'); quantity = SERVICE.DefaultExactUnitsService.add(quantity, movement.normalizedDelta, checkpoint.scale, 'UNNECESSARY'); revision++; } let balance = this.items(await SERVICE.DefaultStockBalanceService.get({ tenant: request.tenant, authData: request.authData, query: { code: input.stockCode, enterpriseCode: request.enterpriseCode }, searchOptions: { limit: 1 } }))[0]; return { stockCode: input.stockCode, checkpointCode: checkpoint.code, expectedQuantity: quantity, expectedRevision: revision, actualQuantity: balance && balance.quantity, actualRevision: balance && balance.revision, consistent: !!balance && quantity === balance.quantity && revision === Number(balance.revision), reservationReconstructionSupported: false }; }
};
