/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is the confidential and proprietary information of Nodics ("Confidential Information").
    You shall not disclose such Confidential Information and shall use it only in accordance with the
    terms of the license agreement you entered into with Nodics.

 */

/** @module product/service/delivery/DefaultProductOnlineReadService @description Resolves bounded customer-safe Product views exclusively from the active immutable Online manifest. @layer service @owner product */
module.exports = {
    /** Initializes Product Online reads. */ init: function () { return Promise.resolve(true); },
    /** Completes Online-read initialization. */ postInit: function () { return Promise.resolve(true); },
    /** Returns Product delivery policy. */ policy: function () { return (CONFIG.get('product') || {}).delivery || {}; },
    /** Extracts generated-service items. */ items: function (response) { return response && Array.isArray(response.result) ? response.result : []; },
    /** Resolves route parameters across supported request shapes. */ parameter: function (request, name) { return request && (request.params && request.params[name] || request.pathParams && request.pathParams[name] || request[name]); },
    /** Parses and bounds requested expansion names. */ expansions: function (request) { let policy = this.policy(), input = request.query && request.query.expand, values = input ? String(input).split(',').map(value => value.trim()).filter(Boolean) : []; if (values.length > Number(policy.maximumExpansions || 8) || new Set(values).size !== values.length || values.some(value => !(policy.allowedExpansions || []).includes(value))) throw SERVICE.DefaultProductEnterpriseScopeService.error('ERR_PRODUCT_00060', 'Product delivery expansions are invalid'); return values; },
    /** Requires an Online runtime and returns trusted read identity. */ identity: function (request) { if ((((CONFIG.get('product') || {}).publication || {}).runtimeRole) !== 'ONLINE' || CONFIG.get('publishEnabled') === true) throw SERVICE.DefaultProductEnterpriseScopeService.error('ERR_PRODUCT_00060', 'Product delivery requires the non-versioned Online runtime'); let enterpriseCode = SERVICE.DefaultProductEnterpriseScopeService.resolveEnterpriseCode(request), catalogCode = SERVICE.DefaultProductEnterpriseScopeService.validateBusinessCode(request.query && request.query.catalogCode, 'Catalog'), itemType = SERVICE.DefaultProductEnterpriseScopeService.validateBusinessCode(this.parameter(request, 'itemType'), 'Item type'), itemCode = SERVICE.DefaultProductEnterpriseScopeService.validateBusinessCode(this.parameter(request, 'itemCode'), 'Item'), localeCode = request.query && request.query.localeCode; if (localeCode && !new RegExp(this.policy().localePattern).test(localeCode)) throw SERVICE.DefaultProductEnterpriseScopeService.error('ERR_PRODUCT_00060', 'Product delivery locale is invalid'); return { enterpriseCode: enterpriseCode, catalogCode: catalogCode, itemType: itemType, itemCode: itemCode, localeCode: localeCode, expansions: this.expansions(request) }; },
    /** Loads the active pointer and integrity-checked immutable manifest. */ release: async function (identity, request) { let pointers = this.items(await SERVICE.DefaultProductOnlinePointerService.get({ tenant: request.tenant, authData: request.authData, query: { enterpriseCode: identity.enterpriseCode, catalogCode: identity.catalogCode }, searchOptions: { limit: 2 } })); if (pointers.length !== 1) throw SERVICE.DefaultProductEnterpriseScopeService.error('ERR_PRODUCT_00061', 'Active Product Online release is unavailable'); let manifests = this.items(await SERVICE.DefaultProductReleaseManifestService.get({ tenant: request.tenant, authData: request.authData, query: { code: pointers[0].manifestCode }, searchOptions: { limit: 2 } })); if (manifests.length !== 1) throw SERVICE.DefaultProductEnterpriseScopeService.error('ERR_PRODUCT_00061', 'Active Product manifest is unavailable'); SERVICE.DefaultProductPublicationManifestService.verify(manifests[0]); if (manifests[0].snapshot.enterpriseCode !== identity.enterpriseCode || manifests[0].snapshot.catalogCode !== identity.catalogCode) throw SERVICE.DefaultProductEnterpriseScopeService.error('ERR_PRODUCT_00062', 'Product release scope validation failed'); return { pointer: pointers[0], manifest: manifests[0] }; },
    /** Groups manifest records by Product schema. */ grouped: function (manifest) { return (manifest.snapshot.records || []).reduce((result, record) => { if (!result[record.schema]) result[record.schema] = []; result[record.schema].push(record.model); return result; }, {}); },
    /** Applies finite deterministic record bounds. */ bounded: function (records) { let maximum = Number(this.policy().maximumRecordsPerExpansion || 1000); if (records.length > maximum) throw SERVICE.DefaultProductEnterpriseScopeService.error('ERR_PRODUCT_00063', 'Product delivery expansion exceeds configured bounds'); return records; },
    /** Projects safe Item fields. */ itemProjection: function (item) { return ['catalogCode', 'itemType', 'itemCode', 'name', 'description', 'baseUnitCode', 'sellable', 'stockManaged', 'status'].reduce((result, key) => { if (item[key] !== undefined) result[key] = item[key]; return result; }, {}); },
    /** Builds one customer-safe graph projection from a single manifest snapshot. */ project: function (identity, release) { let grouped = this.grouped(release.manifest), items = grouped.productItem || [], item = items.find(model => model.enterpriseCode === identity.enterpriseCode && model.catalogCode === identity.catalogCode && model.itemType === identity.itemType && model.itemCode === identity.itemCode && model.status === 'ACTIVE'); if (!item) return { found: false, catalogCode: identity.catalogCode, itemType: identity.itemType, itemCode: identity.itemCode, releaseVersion: release.pointer.manifestCode }; let result = { found: true, releaseVersion: release.pointer.manifestCode, item: this.itemProjection(item) }, matchItem = model => model.itemType === identity.itemType && model.itemCode === identity.itemCode, assignments;
        identity.expansions.forEach(name => { if (name === 'identifiers') result.identifiers = this.bounded((grouped.productIdentifier || []).filter(matchItem)); if (name === 'attributes') result.attributes = this.bounded((grouped.productAttributeValue || []).filter(model => matchItem(model) && (!model.localeCode || !identity.localeCode || model.localeCode === identity.localeCode))); if (name === 'classifications') result.classifications = this.bounded((grouped.productClassificationAssignment || []).filter(matchItem)); if (name === 'categories') { assignments = this.bounded((grouped.productCategoryAssignment || []).filter(matchItem)); let codes = new Set(assignments.map(model => model.categoryCode)); result.categories = { assignments: assignments, definitions: this.bounded((grouped.productCategory || []).filter(model => codes.has(model.categoryCode))) }; } if (name === 'variants') result.variants = this.bounded((grouped.productVariantAssignment || []).filter(model => model.baseItemType === identity.itemType && model.baseItemCode === identity.itemCode || model.variantItemType === identity.itemType && model.variantItemCode === identity.itemCode)); if (name === 'relations') result.relations = this.bounded((grouped.productRelation || []).filter(model => model.sourceItemType === identity.itemType && model.sourceItemCode === identity.itemCode)); if (name === 'bundles') result.bundles = this.bounded((grouped.productBundleEntry || []).filter(model => model.bundleItemType === identity.itemType && model.bundleItemCode === identity.itemCode)); if (name === 'packaging') result.packaging = this.bounded((grouped.productPackaging || []).filter(matchItem)); if (name === 'media') result.media = this.bounded((grouped.productMediaReference || []).filter(model => matchItem(model) && (!model.localeCode || !identity.localeCode || model.localeCode === identity.localeCode))); }); return result; },
    /** Resolves one uncached active-release Product view. */ resolve: async function (request) { let identity = this.identity(request), release = await this.release(identity, request); return this.project(identity, release); }
};
