/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */
/** @module order/test/orderRefundPipelineContract @description Protects Refund calculation adaptation, risk-aware approval, and owner execution delegation. @layer test @owner order */
const assert = require('assert'); const properties = require('../config/properties'); global.CONFIG = { get: key => key === 'order' ? properties.order : undefined };
const calculation = require('../src/service/lifecycle/defaultOrderRefundCalculationService'); const approval = require('../src/service/lifecycle/defaultOrderRefundApprovalService'); const execution = require('../src/service/lifecycle/defaultOrderRefundExecutionService');
let delegated;
global.SERVICE = {
    DefaultOrderCancellationCalculationService: { calculate: async request => { delegated = request.cancellationCalculation; return { amount: '3.25', currencyCode: 'USD', paymentCalculation: { allocationEvidence: [{ paymentGroupCode: 'card', originalTransactionCode: 'capture-1', amount: '3.25', currencyCode: 'USD' }] } }; } },
    DefaultPaymentRefundExecutionService: { execute: async request => request.refundExecution },
    DefaultOrderCancellationProductEvidenceProviderService: { resolve: async request => ({ items: request.items.map(item => ({ orderEntryCode: item.orderEntryCode, lifecycleType: item.immutableEvidence.lifecycleType || 'PHYSICAL', entitlementReference: item.immutableEvidence.entitlementReference, entitlementState: item.immutableEvidence.entitlementState, providerActionRequired: item.immutableEvidence.lifecycleType === 'LICENSE', providerActionCode: item.immutableEvidence.lifecycleType === 'LICENSE' ? 'REVOKE_LICENSE' : undefined })) }) },
    DefaultProductLifecycleCancellationService: { execute: async request => ({ status: request.productLifecycleCancellation.providerActionRequired ? 'REVOKED' : 'NO_PRODUCT_PROVIDER_ACTION_REQUIRED', orderEntryCode: request.productLifecycleCancellation.orderEntryCode }) },
};
const requestModel = { requestCode: 'refund-1', requestType: 'REFUND', state: 'APPROVED', version: 2, entCode: 'ent-1', orderCode: 'order-1', requesterType: 'CUSTOMER', idempotencyKey: 'key-1', evidence: { calculation: { amount: '3.25', paymentCalculation: { allocationEvidence: [{ paymentGroupCode: 'card', originalTransactionCode: 'capture-1', amount: '3.25', currencyCode: 'USD' }] } } } };
(async () => {
    let calculated = await calculation.calculate({ tenant: 'default', authData: { tokenType: 'service' } }, { request: requestModel, items: [{ orderEntryCode: 'entry-1', requestedQuantity: '1' }], paymentTransactions: [{ transactionCode: 'capture-1' }], orderEntries: [], paymentAllocations: [] }); assert.strictEqual(calculated.amount, '3.25'); assert.strictEqual(delegated.eligibility.items[0].requestedQuantity, '1');
    let route = approval.prepare({ refundApproval: { request: requestModel, calculation: calculated, riskEvidence: { requiresHumanReview: true } } }); assert.strictEqual(route.route, 'MANUAL_REVIEW');
    const policy = properties.order.orderLifecycle.refundApproval; policy.autoApprovalEnabled = true; policy.autoApprovalRequesterTypes = ['CUSTOMER']; policy.approvalRules = [{ ruleCode: 'low-risk-card', enterpriseCode: ['ent-1'], channelCode: ['web'], countryCode: ['AE'], paymentMethodCode: ['CARD'], returnReasonCode: ['GOODWILL'], productType: ['PHYSICAL'], customerSegment: ['STANDARD'], customerTrustLevel: ['TRUSTED'], historicalReturnBand: ['LOW'], riskBand: ['LOW'], providerRiskBand: ['LOW'], maximumAmount: '5.00', route: 'AUTO_APPROVE' }]; let ruledRequest = Object.assign({}, requestModel, { channelCode: 'web', countryCode: 'AE', reasonCode: 'GOODWILL' }); let ruled = approval.prepare({ refundApproval: { request: ruledRequest, calculation: calculated, policyContext: { paymentMethodCode: 'CARD', productType: 'PHYSICAL', customerSegment: 'STANDARD', customerTrustLevel: 'TRUSTED', historicalReturnBand: 'LOW' }, riskEvidence: { riskBand: 'LOW', riskScore: '10', signalCodes: [] } } }); assert.strictEqual(ruled.route, 'AUTO_APPROVE'); assert.strictEqual(ruled.ruleCode, 'low-risk-card'); let untrusted = approval.prepare({ refundApproval: { request: ruledRequest, calculation: calculated, policyContext: { paymentMethodCode: 'CARD', productType: 'PHYSICAL', customerSegment: 'STANDARD', customerTrustLevel: 'UNTRUSTED', historicalReturnBand: 'HIGH' }, riskEvidence: { riskBand: 'LOW' } } }); assert.strictEqual(untrusted.route, 'MANUAL_REVIEW'); assert.throws(() => approval.prepare({ refundApproval: { request: ruledRequest, calculation: calculated, riskEvidence: { rawProviderPayload: { score: 10 } } } }), /normalized/); policy.autoApprovalEnabled = false; policy.approvalRules = [];
    let response = {}, refundItems = [{ orderEntryCode: 'entry-1', requestedQuantity: '1', immutableEvidence: { lifecycleType: 'LICENSE', entitlementReference: 'license-1', entitlementState: 'DELIVERED', catalogCode: 'catalog', itemType: 'SKU', itemCode: 'license' } }]; await new Promise((resolve, reject) => execution.validateExecution({ tenant: 'default', authData: { tokenType: 'service' }, refundExecution: { request: requestModel, items: refundItems } }, response, { nextSuccess: resolve, error: (req, res, error) => reject(error) })); await new Promise((resolve, reject) => execution.executeProductLifecycleActions({ tenant: 'default', authData: { tokenType: 'service' } }, response, { nextSuccess: resolve, error: (req, res, error) => reject(error) })); assert.strictEqual(response.productLifecycleExecution[0].status, 'REVOKED'); await new Promise((resolve, reject) => execution.executePaymentRefund({ tenant: 'default', authData: { tokenType: 'service' } }, response, { nextSuccess: resolve, error: (req, res, error) => reject(error) })); assert.strictEqual(response.refundExecution.payment.refundCode, 'refund-1'); assert.strictEqual(response.refundExecution.payment.allocations[0].originalTransactionCode, 'capture-1'); const pipeline = require('../src/pipelines/pipelines').refundExecutionPipeline; assert.strictEqual(pipeline.nodes.validateExecution.success, 'executeProductLifecycleActions'); assert.strictEqual(pipeline.nodes.executeProductLifecycleActions.success, 'executePaymentRefund');
    console.log('Order Refund Pipeline contract validated');
})().catch(error => { console.error(error); process.exit(1); });
