/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */

/* Nodics - governed by the root LICENSE. */
const assert=require('assert'),properties=require('../config/properties');global.CONFIG={get:key=>key==='order'?properties.order:undefined};let events=[],histories=[];const model={requestCode:'return-1',requestType:'RETURN',version:2,entCode:'ent-1',orderCode:'order-1',customerCode:'customer-1',state:'AUTHORIZATION_PENDING'};global.SERVICE={DefaultOrderCancellationIntentService:{enterprise:()=>true,loadOrder:async()=>({code:'order-1',siteCode:'site-1',channelCode:'web'})},DefaultOrderLifecycleOrchestrationService:{loadRequest:async()=>model},DefaultOrderLifecycleAuditService:{record:async(request,lifecycle,type,code)=>{let existing=histories.find(value=>value.historyCode===code);if(existing)return Object.assign({idempotent:true},existing);let item={historyCode:code,eventType:type};histories.push(item);return item;}},DefaultEventService:{handleEvent:async request=>events.push(request.event)}};SERVICE.DefaultOrderLifecycleEventService=require('../src/service/lifecycle/defaultOrderLifecycleEventService');const service=require('../src/service/lifecycle/defaultOrderLifecycleSupportService'),request=body=>({tenant:'default',authData:{tokenType:'access',principalId:'support-1',enterpriseCode:'ent-1',siteCodes:['site-1'],channelCodes:['web']},params:{requestCode:'return-1'},body:Object.assign({expectedVersion:2},body)});(async()=>{let recommendation=await service.recommend(request({recommendation:'APPROVE',recommendationCode:'rec-1',reasonCode:'POLICY_ELIGIBLE'}));assert.strictEqual(recommendation.recommendation,'APPROVE');let message=await service.message(request({messageCode:'msg-1',templateCode:'ORDER_LIFECYCLE_STATUS_UPDATE',templateVariables:{status:'AUTHORIZATION_PENDING'}}));assert.strictEqual(message.notification.published,true);assert.strictEqual(events[0].data.notificationIntent.templateCode,'ORDER_LIFECYCLE_STATUS_UPDATE');let outside=request({recommendation:'REJECT',recommendationCode:'rec-2',reasonCode:'OTHER'});outside.authData.siteCodes=['other'];await assert.rejects(()=>service.recommend(outside),/outside support scope/);await assert.rejects(()=>service.message(request({messageCode:'msg-2',templateCode:'UNAPPROVED_TEMPLATE'})),/template evidence is invalid/);const routes=require('../src/router/routers').order.lifecycleSupportOperations;assert.strictEqual(routes.recommend.permission,'order.lifecycle.support.recommend');assert.strictEqual(routes.message.permission,'order.lifecycle.support.message');console.log('Order lifecycle support operations contract validated');})().catch(error=>{console.error(error);process.exit(1);});
