/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */
/** @module order/test/orderDigitalLifecycleCancellationContract @description Protects non-physical cancellation without stock mutation and with configured entitlement-provider evidence. @layer test @owner order */
const assert = require('assert'); const properties = require('../config/properties'); global.CONFIG = { get: key => key === 'order' ? properties.order : key === 'units' ? { maximumScale: 18 } : undefined }; global.CLASSES = { NodicsError: class NodicsError extends Error { constructor(message, cause, code) { super(message); this.code = code; } } }; global.SERVICE = { DefaultExactUnitsService: require('../../../../gCore/units/src/service/exact/defaultExactUnitsService') };
const eligibility = require('../src/service/lifecycle/defaultOrderCancellationEligibilityService'); const execution = require('../src/service/lifecycle/defaultOrderCancellationExecutionService');
const request = { tenant: 'default', authData: { tokenType: 'service' }, now: '2026-08-03T00:00:00.000Z', cancellationEligibility: { entCode: 'ent-1', order: { code: 'order-1', status: 'PLACED', placedAt: '2026-08-03T00:00:00.000Z' }, items: [{ orderEntryCode: 'entry-digital', unitCode: 'EA', requestedQuantity: '1', orderedQuantity: '1', alreadyCancelledQuantity: '0', immutableEvidence: { lifecycleType: 'LICENSE' } }], ownerEvidence: { inventory: { items: [{ orderEntryCode: 'entry-digital', unitCode: 'EA', releasableQuantity: '1', inventoryRequired: false }] }, fulfillment: { items: [{ orderEntryCode: 'entry-digital', unitCode: 'EA', cancellableQuantity: '1', state: 'NOT_APPLICABLE', fulfillmentRequired: false }] }, payment: { items: [{ orderEntryCode: 'entry-digital', state: 'CAPTURED', transactionCodes: ['capture-1'], transactions: [{ transactionCode: 'capture-1', paymentGroupCode: 'card', providerCode: 'stripe', paymentModeCode: 'CARD' }] }] }, product: { items: [{ orderEntryCode: 'entry-digital', cancellationAllowed: true, policyCode: 'license-policy', lifecycleType: 'LICENSE', providerActionRequired: true, providerActionCode: 'REVOKE_LICENSE', entitlementReference: 'license-1', entitlementState: 'DELIVERED' }] } } } };
(async () => { let result = await eligibility.evaluate(request); assert.strictEqual(result.eligible, true); assert.strictEqual(result.items[0].requiredActions.inventory, 'NONE'); assert.strictEqual(result.items[0].requiredActions.fulfillment, 'NONE'); assert.strictEqual(result.items[0].requiredActions.productLifecycle, 'REVOKE_LICENSE'); let input = { request: { requestCode: 'cancel-1', version: 1, evidence: { eligibility: result } }, items: [{ orderEntryCode: 'entry-digital', requestedQuantity: '1', unitCode: 'EA', immutableEvidence: { lifecycleType: 'LICENSE' } }] }; assert.deepStrictEqual(execution.fulfillmentItems(input), []); assert.deepStrictEqual(execution.inventoryPlans(input), []); console.log('Order digital lifecycle cancellation contract validated'); })().catch(error => { console.error(error); process.exit(1); });
