/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is the confidential and proprietary information of Nodics ("Confidential Information").
    You shall not disclose such Confidential Information and shall use it only in accordance with the
    terms of the license agreement you entered into with Nodics.

 */

/**
 * @module inventory/src/interceptors/interceptors
 * @description Enforces enterprise scope, stable identities, hierarchy validation, lifecycle transitions, and no-hard-delete governance at generated persistence boundaries.
 * @layer interceptor
 * @owner inventory
 * @override Later modules may replace validators while preserving the published warehouse-foundation invariants.
 */
module.exports = {
    warehousePreSave: { type: 'schema', item: 'warehouse', trigger: 'preSave', active: 'true', index: -100,
        handler: 'DefaultInventoryWarehouseFoundationService.prepareWarehouseSave' },
    warehousePreGet: { type: 'schema', item: 'warehouse', trigger: 'preGet', active: 'true', index: -100,
        handler: 'DefaultInventoryEnterpriseScopeService.scopeQuery' },
    warehousePreUpdate: { type: 'schema', item: 'warehouse', trigger: 'preUpdate', active: 'true', index: -100,
        handler: 'DefaultInventoryWarehouseFoundationService.prepareWarehouseUpdate' },
    warehousePreRemove: { type: 'schema', item: 'warehouse', trigger: 'preRemove', active: 'true', index: -100,
        handler: 'DefaultInventoryWarehouseFoundationService.rejectHardDelete' },
    warehouseLocationPreSave: { type: 'schema', item: 'warehouseLocation', trigger: 'preSave', active: 'true', index: -100,
        handler: 'DefaultInventoryWarehouseLocationFoundationService.prepareLocationSave' },
    warehouseLocationPreGet: { type: 'schema', item: 'warehouseLocation', trigger: 'preGet', active: 'true', index: -100,
        handler: 'DefaultInventoryEnterpriseScopeService.scopeQuery' },
    warehouseLocationPreUpdate: { type: 'schema', item: 'warehouseLocation', trigger: 'preUpdate', active: 'true', index: -100,
        handler: 'DefaultInventoryWarehouseLocationFoundationService.prepareLocationUpdate' },
    warehouseLocationPreRemove: { type: 'schema', item: 'warehouseLocation', trigger: 'preRemove', active: 'true', index: -100,
        handler: 'DefaultInventoryWarehouseLocationFoundationService.rejectHardDelete' },
    stockBalancePreGet: { type: 'schema', item: 'stockBalance', trigger: 'preGet', active: 'true', index: -100,
        handler: 'DefaultInventoryEnterpriseScopeService.scopeQuery' },
    stockBalancePreSave: { type: 'schema', item: 'stockBalance', trigger: 'preSave', active: 'true', index: -100,
        handler: 'DefaultStockMovementService.authorizeInternalMutation' },
    stockBalancePreUpdate: { type: 'schema', item: 'stockBalance', trigger: 'preUpdate', active: 'true', index: -100,
        handler: 'DefaultStockMovementService.authorizeInternalMutation' },
    stockBalancePreRemove: { type: 'schema', item: 'stockBalance', trigger: 'preRemove', active: 'true', index: -100,
        handler: 'DefaultStockMovementService.rejectDelete' },
    stockBalancePostSaveInvalidateAvailability: { type: 'schema', item: 'stockBalance', trigger: 'postSave', active: 'true', index: 100, handler: 'DefaultStockAvailabilityCacheService.invalidate' },
    stockBalancePostUpdateInvalidateAvailability: { type: 'schema', item: 'stockBalance', trigger: 'postUpdate', active: 'true', index: 100, handler: 'DefaultStockAvailabilityCacheService.invalidate' },
    stockMovementRecordPreGet: { type: 'schema', item: 'stockMovementRecord', trigger: 'preGet', active: 'true', index: -100,
        handler: 'DefaultInventoryEnterpriseScopeService.scopeQuery' },
    stockMovementRecordPreSave: { type: 'schema', item: 'stockMovementRecord', trigger: 'preSave', active: 'true', index: -100,
        handler: 'DefaultStockMovementService.authorizeInternalMutation' },
    stockMovementRecordPreUpdate: { type: 'schema', item: 'stockMovementRecord', trigger: 'preUpdate', active: 'true', index: -100,
        handler: 'DefaultStockMovementService.authorizeInternalMutation' },
    stockMovementRecordPreRemove: { type: 'schema', item: 'stockMovementRecord', trigger: 'preRemove', active: 'true', index: -100,
        handler: 'DefaultStockMovementService.rejectDelete' },
    stockMovementCheckpointPreGet: { type: 'schema', item: 'stockMovementCheckpoint', trigger: 'preGet', active: 'true', index: -100, handler: 'DefaultInventoryEnterpriseScopeService.scopeQuery' },
    stockMovementCheckpointPreSave: { type: 'schema', item: 'stockMovementCheckpoint', trigger: 'preSave', active: 'true', index: -100, handler: 'DefaultStockMovementCheckpointOrchestrationService.authorizeMutation' },
    stockMovementCheckpointPreUpdate: { type: 'schema', item: 'stockMovementCheckpoint', trigger: 'preUpdate', active: 'true', index: -100, handler: 'DefaultStockMovementCheckpointOrchestrationService.rejectMutation' },
    stockMovementCheckpointPreRemove: { type: 'schema', item: 'stockMovementCheckpoint', trigger: 'preRemove', active: 'true', index: -100, handler: 'DefaultStockMovementCheckpointOrchestrationService.rejectMutation' },
    stockProviderOperationPreGet: { type: 'schema', item: 'stockProviderOperation', trigger: 'preGet', active: 'true', index: -100, handler: 'DefaultInventoryEnterpriseScopeService.scopeQuery' },
    stockProviderOperationPreSave: { type: 'schema', item: 'stockProviderOperation', trigger: 'preSave', active: 'true', index: -100, handler: 'DefaultInventoryExternalProviderService.authorizeMutation' },
    stockProviderOperationPreUpdate: { type: 'schema', item: 'stockProviderOperation', trigger: 'preUpdate', active: 'true', index: -100, handler: 'DefaultInventoryExternalProviderService.authorizeMutation' },
    stockProviderOperationPreRemove: { type: 'schema', item: 'stockProviderOperation', trigger: 'preRemove', active: 'true', index: -100, handler: 'DefaultInventoryExternalProviderService.rejectDelete' },
    stockReservationPreGet: { type: 'schema', item: 'stockReservation', trigger: 'preGet', active: 'true', index: -100,
        handler: 'DefaultInventoryEnterpriseScopeService.scopeQuery' },
    stockReservationPreSave: { type: 'schema', item: 'stockReservation', trigger: 'preSave', active: 'true', index: -100,
        handler: 'DefaultStockReservationOrchestrationService.authorizeInternalMutation' },
    stockReservationPreUpdate: { type: 'schema', item: 'stockReservation', trigger: 'preUpdate', active: 'true', index: -100,
        handler: 'DefaultStockReservationOrchestrationService.authorizeInternalMutation' },
    stockReservationPreRemove: { type: 'schema', item: 'stockReservation', trigger: 'preRemove', active: 'true', index: -100,
        handler: 'DefaultStockReservationOrchestrationService.rejectDelete' },
    stockAllocationPreGet: { type: 'schema', item: 'stockAllocation', trigger: 'preGet', active: 'true', index: -100,
        handler: 'DefaultInventoryEnterpriseScopeService.scopeQuery' },
    stockAllocationPreSave: { type: 'schema', item: 'stockAllocation', trigger: 'preSave', active: 'true', index: -100,
        handler: 'DefaultStockAllocationOrchestrationService.authorizeInternalMutation' },
    stockAllocationPreUpdate: { type: 'schema', item: 'stockAllocation', trigger: 'preUpdate', active: 'true', index: -100,
        handler: 'DefaultStockAllocationOrchestrationService.authorizeInternalMutation' },
    stockAllocationPreRemove: { type: 'schema', item: 'stockAllocation', trigger: 'preRemove', active: 'true', index: -100,
        handler: 'DefaultStockAllocationOrchestrationService.rejectDelete' },
    stockTransferPreGet: { type: 'schema', item: 'stockTransfer', trigger: 'preGet', active: 'true', index: -100, handler: 'DefaultInventoryEnterpriseScopeService.scopeQuery' },
    stockTransferPreSave: { type: 'schema', item: 'stockTransfer', trigger: 'preSave', active: 'true', index: -100, handler: 'DefaultStockTransferOrchestrationService.authorizeInternalMutation' },
    stockTransferPreUpdate: { type: 'schema', item: 'stockTransfer', trigger: 'preUpdate', active: 'true', index: -100, handler: 'DefaultStockTransferOrchestrationService.authorizeInternalMutation' },
    stockTransferPreRemove: { type: 'schema', item: 'stockTransfer', trigger: 'preRemove', active: 'true', index: -100, handler: 'DefaultStockTransferOrchestrationService.rejectDelete' },
    stockReconciliationRunPreGet: { type: 'schema', item: 'stockReconciliationRun', trigger: 'preGet', active: 'true', index: -100, handler: 'DefaultInventoryEnterpriseScopeService.scopeQuery' },
    stockReconciliationRunPreSave: { type: 'schema', item: 'stockReconciliationRun', trigger: 'preSave', active: 'true', index: -100, handler: 'DefaultStockReconciliationService.authorizeMutation' },
    stockReconciliationRunPreUpdate: { type: 'schema', item: 'stockReconciliationRun', trigger: 'preUpdate', active: 'true', index: -100, handler: 'DefaultStockReconciliationService.authorizeMutation' },
    stockReconciliationRunPreRemove: { type: 'schema', item: 'stockReconciliationRun', trigger: 'preRemove', active: 'true', index: -100, handler: 'DefaultStockReconciliationService.rejectDelete' },
    stockReconciliationFindingPreGet: { type: 'schema', item: 'stockReconciliationFinding', trigger: 'preGet', active: 'true', index: -100, handler: 'DefaultInventoryEnterpriseScopeService.scopeQuery' },
    stockReconciliationFindingPreSave: { type: 'schema', item: 'stockReconciliationFinding', trigger: 'preSave', active: 'true', index: -100, handler: 'DefaultStockReconciliationService.authorizeMutation' },
    stockReconciliationFindingPreUpdate: { type: 'schema', item: 'stockReconciliationFinding', trigger: 'preUpdate', active: 'true', index: -100, handler: 'DefaultStockReconciliationService.authorizeMutation' },
    stockReconciliationFindingPreRemove: { type: 'schema', item: 'stockReconciliationFinding', trigger: 'preRemove', active: 'true', index: -100, handler: 'DefaultStockReconciliationService.rejectDelete' },
    stockPoolPreSave: { type: 'schema', item: 'stockPool', trigger: 'preSave', active: 'true', index: -100,
        handler: 'DefaultStockPoolFoundationService.preparePoolSave' },
    stockPoolPreGet: { type: 'schema', item: 'stockPool', trigger: 'preGet', active: 'true', index: -100,
        handler: 'DefaultInventoryEnterpriseScopeService.scopeQuery' },
    stockPoolPreUpdate: { type: 'schema', item: 'stockPool', trigger: 'preUpdate', active: 'true', index: -100,
        handler: 'DefaultStockPoolFoundationService.preparePoolUpdate' },
    stockPoolPreRemove: { type: 'schema', item: 'stockPool', trigger: 'preRemove', active: 'true', index: -100,
        handler: 'DefaultStockPoolFoundationService.rejectHardDelete' },
    stockPoolPostSaveInvalidateSourcing: { type: 'schema', item: 'stockPool', trigger: 'postSave', active: 'true', index: 100,
        handler: 'DefaultStockSourcingCacheService.invalidate' },
    stockPoolPostUpdateInvalidateSourcing: { type: 'schema', item: 'stockPool', trigger: 'postUpdate', active: 'true', index: 100,
        handler: 'DefaultStockSourcingCacheService.invalidate' },
    stockPoolPostSaveInvalidateAvailability: { type: 'schema', item: 'stockPool', trigger: 'postSave', active: 'true', index: 110, handler: 'DefaultStockAvailabilityCacheService.invalidate' },
    stockPoolPostUpdateInvalidateAvailability: { type: 'schema', item: 'stockPool', trigger: 'postUpdate', active: 'true', index: 110, handler: 'DefaultStockAvailabilityCacheService.invalidate' },
    stockPoolMemberPreSave: { type: 'schema', item: 'stockPoolMember', trigger: 'preSave', active: 'true', index: -100,
        handler: 'DefaultStockPoolMemberFoundationService.prepareMemberSave' },
    stockPoolMemberPreGet: { type: 'schema', item: 'stockPoolMember', trigger: 'preGet', active: 'true', index: -100,
        handler: 'DefaultInventoryEnterpriseScopeService.scopeQuery' },
    stockPoolMemberPreUpdate: { type: 'schema', item: 'stockPoolMember', trigger: 'preUpdate', active: 'true', index: -100,
        handler: 'DefaultStockPoolMemberFoundationService.prepareMemberUpdate' },
    stockPoolMemberPreRemove: { type: 'schema', item: 'stockPoolMember', trigger: 'preRemove', active: 'true', index: -100,
        handler: 'DefaultStockPoolMemberFoundationService.rejectHardDelete' },
    stockPoolMemberPostSaveInvalidateSourcing: { type: 'schema', item: 'stockPoolMember', trigger: 'postSave', active: 'true', index: 100,
        handler: 'DefaultStockSourcingCacheService.invalidate' },
    stockPoolMemberPostUpdateInvalidateSourcing: { type: 'schema', item: 'stockPoolMember', trigger: 'postUpdate', active: 'true', index: 100,
        handler: 'DefaultStockSourcingCacheService.invalidate' },
    stockPoolMemberPostSaveInvalidateAvailability: { type: 'schema', item: 'stockPoolMember', trigger: 'postSave', active: 'true', index: 110, handler: 'DefaultStockAvailabilityCacheService.invalidate' },
    stockPoolMemberPostUpdateInvalidateAvailability: { type: 'schema', item: 'stockPoolMember', trigger: 'postUpdate', active: 'true', index: 110, handler: 'DefaultStockAvailabilityCacheService.invalidate' },
    stockSourcingPolicyPreSave: { type: 'schema', item: 'stockSourcingPolicy', trigger: 'preSave', active: 'true', index: -100,
        handler: 'DefaultStockSourcingPolicyFoundationService.preparePolicySave' },
    stockSourcingPolicyPreGet: { type: 'schema', item: 'stockSourcingPolicy', trigger: 'preGet', active: 'true', index: -100,
        handler: 'DefaultInventoryEnterpriseScopeService.scopeQuery' },
    stockSourcingPolicyPreUpdate: { type: 'schema', item: 'stockSourcingPolicy', trigger: 'preUpdate', active: 'true', index: -100,
        handler: 'DefaultStockSourcingPolicyFoundationService.preparePolicyUpdate' },
    stockSourcingPolicyPreRemove: { type: 'schema', item: 'stockSourcingPolicy', trigger: 'preRemove', active: 'true', index: -100,
        handler: 'DefaultStockSourcingPolicyFoundationService.rejectHardDelete' },
    stockSourcingPolicyPostSaveInvalidate: { type: 'schema', item: 'stockSourcingPolicy', trigger: 'postSave', active: 'true', index: 100,
        handler: 'DefaultStockSourcingCacheService.invalidate' },
    stockSourcingPolicyPostUpdateInvalidate: { type: 'schema', item: 'stockSourcingPolicy', trigger: 'postUpdate', active: 'true', index: 100,
        handler: 'DefaultStockSourcingCacheService.invalidate' },
    stockSourcingPolicyPostSaveInvalidateAvailability: { type: 'schema', item: 'stockSourcingPolicy', trigger: 'postSave', active: 'true', index: 110, handler: 'DefaultStockAvailabilityCacheService.invalidate' },
    stockSourcingPolicyPostUpdateInvalidateAvailability: { type: 'schema', item: 'stockSourcingPolicy', trigger: 'postUpdate', active: 'true', index: 110, handler: 'DefaultStockAvailabilityCacheService.invalidate' },
    stockSourcingRulePreSave: { type: 'schema', item: 'stockSourcingRule', trigger: 'preSave', active: 'true', index: -100,
        handler: 'DefaultStockSourcingRuleFoundationService.prepareRuleSave' },
    stockSourcingRulePreGet: { type: 'schema', item: 'stockSourcingRule', trigger: 'preGet', active: 'true', index: -100,
        handler: 'DefaultInventoryEnterpriseScopeService.scopeQuery' },
    stockSourcingRulePreUpdate: { type: 'schema', item: 'stockSourcingRule', trigger: 'preUpdate', active: 'true', index: -100,
        handler: 'DefaultStockSourcingRuleFoundationService.prepareRuleUpdate' },
    stockSourcingRulePreRemove: { type: 'schema', item: 'stockSourcingRule', trigger: 'preRemove', active: 'true', index: -100,
        handler: 'DefaultStockSourcingRuleFoundationService.rejectHardDelete' },
    stockSourcingRulePostSaveInvalidate: { type: 'schema', item: 'stockSourcingRule', trigger: 'postSave', active: 'true', index: 100,
        handler: 'DefaultStockSourcingCacheService.invalidate' },
    stockSourcingRulePostUpdateInvalidate: { type: 'schema', item: 'stockSourcingRule', trigger: 'postUpdate', active: 'true', index: 100,
        handler: 'DefaultStockSourcingCacheService.invalidate' },
    stockSourcingRulePostSaveInvalidateAvailability: { type: 'schema', item: 'stockSourcingRule', trigger: 'postSave', active: 'true', index: 110, handler: 'DefaultStockAvailabilityCacheService.invalidate' },
    stockSourcingRulePostUpdateInvalidateAvailability: { type: 'schema', item: 'stockSourcingRule', trigger: 'postUpdate', active: 'true', index: 110, handler: 'DefaultStockAvailabilityCacheService.invalidate' }
};
