/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is the confidential and proprietary information of Nodics ("Confidential Information").
    You shall not disclose such Confidential Information and shall use it only in accordance with the
    terms of the license agreement you entered into with Nodics.

 */

/** @module product/management/DefaultProductManagementService @description Provides bounded human Product Item and Identifier management intents over internal generated services. @layer service @owner product */
module.exports = {
    /** Initializes Product management. */ init: function () { return Promise.resolve(true); },
    /** Completes Product management initialization. */ postInit: function () { return Promise.resolve(true); },
    /** Returns allow-listed resources, filters, and safe projections. */ resources: function () { return {
        items: { service: 'DefaultProductItemService', identity: 'itemCode', filters: ['catalogCode', 'itemType', 'itemCode', 'status', 'sellable', 'stockManaged'], fields: ['code', 'catalogCode', 'itemType', 'itemCode', 'name', 'description', 'baseUnitCode', 'sellable', 'stockManaged', 'status', 'versionId', 'updatedAt'] },
        identifiers: { service: 'DefaultProductIdentifierService', identity: 'identifierCode', filters: ['catalogCode', 'identifierCode', 'itemType', 'itemCode', 'identifierType', 'identifierValue', 'status'], fields: ['code', 'catalogCode', 'identifierCode', 'itemType', 'itemCode', 'identifierType', 'identifierValue', 'primary', 'status', 'versionId', 'updatedAt'] },
        categories: { service: 'DefaultProductCategoryService', identity: 'categoryCode', filters: ['catalogCode', 'categoryCode', 'parentCategoryCode', 'status', 'navigable'], fields: ['code', 'catalogCode', 'categoryCode', 'name', 'description', 'parentCategoryCode', 'order', 'navigable', 'status', 'effectiveFrom', 'effectiveTo', 'versionId', 'updatedAt'] },
        categoryAssignments: { service: 'DefaultProductCategoryAssignmentService', identity: 'assignmentCode', filters: ['catalogCode', 'assignmentCode', 'categoryCode', 'itemType', 'itemCode', 'status', 'primary'], fields: ['code', 'catalogCode', 'assignmentCode', 'categoryCode', 'itemType', 'itemCode', 'position', 'primary', 'status', 'effectiveFrom', 'effectiveTo', 'versionId', 'updatedAt'] },
        attributeDefinitions: { service: 'DefaultProductAttributeDefinitionService', identity: 'attributeCode', filters: ['catalogCode', 'attributeCode', 'valueType', 'localized', 'multiValued', 'status'], fields: ['code', 'catalogCode', 'attributeCode', 'name', 'description', 'valueType', 'localized', 'multiValued', 'required', 'minimumValues', 'maximumValues', 'enumerationValues', 'unitRequired', 'status', 'versionId', 'updatedAt'] },
        attributeValues: { service: 'DefaultProductAttributeValueService', identity: 'valueCode', filters: ['catalogCode', 'valueCode', 'itemType', 'itemCode', 'attributeCode', 'localeCode', 'status'], fields: ['code', 'catalogCode', 'valueCode', 'itemType', 'itemCode', 'attributeCode', 'localeCode', 'ordinal', 'stringValue', 'booleanValue', 'integerValue', 'decimalValue', 'dateValue', 'referenceType', 'referenceItemType', 'referenceCode', 'unitCode', 'status', 'versionId', 'updatedAt'] },
        classificationClasses: { service: 'DefaultProductClassificationClassService', identity: 'classCode', filters: ['catalogCode', 'classCode', 'status'], fields: ['code', 'catalogCode', 'classCode', 'name', 'description', 'attributeCodes', 'requiredAttributeCodes', 'status', 'versionId', 'updatedAt'] },
        classificationAssignments: { service: 'DefaultProductClassificationAssignmentService', identity: 'assignmentCode', filters: ['catalogCode', 'assignmentCode', 'classCode', 'itemType', 'itemCode', 'status'], fields: ['code', 'catalogCode', 'assignmentCode', 'classCode', 'itemType', 'itemCode', 'status', 'effectiveFrom', 'effectiveTo', 'versionId', 'updatedAt'] },
        variantAxes: { service: 'DefaultProductVariantAxisService', identity: 'axisCode', filters: ['catalogCode', 'axisCode', 'baseItemType', 'baseItemCode', 'attributeCode', 'status'], fields: ['code', 'catalogCode', 'axisCode', 'baseItemType', 'baseItemCode', 'attributeCode', 'position', 'required', 'status', 'versionId', 'updatedAt'] },
        variantAssignments: { service: 'DefaultProductVariantAssignmentService', identity: 'assignmentCode', filters: ['catalogCode', 'assignmentCode', 'baseItemType', 'baseItemCode', 'variantItemType', 'variantItemCode', 'combinationKey', 'status'], fields: ['code', 'catalogCode', 'assignmentCode', 'baseItemType', 'baseItemCode', 'variantItemType', 'variantItemCode', 'axisValues', 'combinationKey', 'status', 'versionId', 'updatedAt'] }
        ,relations: { service: 'DefaultProductRelationService', identity: 'relationCode', filters: ['catalogCode', 'relationCode', 'relationType', 'sourceItemType', 'sourceItemCode', 'targetCatalogCode', 'targetItemType', 'targetItemCode', 'status'], fields: ['code', 'catalogCode', 'relationCode', 'relationType', 'sourceItemType', 'sourceItemCode', 'targetCatalogCode', 'targetItemType', 'targetItemCode', 'position', 'effectiveFrom', 'effectiveTo', 'status', 'versionId', 'updatedAt'] }
        ,bundleEntries: { service: 'DefaultProductBundleEntryService', identity: 'entryCode', filters: ['catalogCode', 'entryCode', 'bundleItemType', 'bundleItemCode', 'componentItemType', 'componentItemCode', 'status'], fields: ['code', 'catalogCode', 'entryCode', 'bundleItemType', 'bundleItemCode', 'componentItemType', 'componentItemCode', 'quantity', 'unitCode', 'position', 'optional', 'status', 'versionId', 'updatedAt'] }
        ,packaging: { service: 'DefaultProductPackagingService', identity: 'packagingCode', filters: ['catalogCode', 'packagingCode', 'itemType', 'itemCode', 'packageType', 'status'], fields: ['code', 'catalogCode', 'packagingCode', 'itemType', 'itemCode', 'packageType', 'containedQuantity', 'containedUnitCode', 'length', 'width', 'height', 'dimensionUnitCode', 'weight', 'weightUnitCode', 'position', 'status', 'versionId', 'updatedAt'] }
        ,mediaReferences: { service: 'DefaultProductMediaReferenceService', identity: 'mediaCode', filters: ['catalogCode', 'mediaCode', 'itemType', 'itemCode', 'mediaType', 'role', 'localeCode', 'status'], fields: ['code', 'catalogCode', 'mediaCode', 'itemType', 'itemCode', 'mediaType', 'role', 'uri', 'localeCode', 'position', 'altText', 'status', 'versionId', 'updatedAt'] }
    }; },
    /** Returns management limits. */ policy: function () { return (CONFIG.get('product') || {}).management || {}; },
    /** Requires a human identity and returns its enterprise. */ authorize: function (request) { let auth = request && request.authData || {}; if (!auth.tokenType || auth.tokenType === 'service' || !(auth.principalId || auth.loginId || auth.code)) throw SERVICE.DefaultProductEnterpriseScopeService.error('ERR_PRODUCT_00022', 'Product management requires an authenticated human principal'); return SERVICE.DefaultProductEnterpriseScopeService.resolveEnterpriseCode(request); },
    /** Resolves a route parameter across supported request shapes. */ parameter: function (request, name) { return request && (request.params && request.params[name] || request.pathParams && request.pathParams[name] || request[name]); },
    /** Resolves an allow-listed Product resource. */ resource: function (request) { let name = this.parameter(request, 'resource'), resource = this.resources()[name]; if (!resource || !(this.policy().allowedResources || []).includes(name) || !SERVICE[resource.service]) throw SERVICE.DefaultProductEnterpriseScopeService.error('ERR_PRODUCT_00023', 'Unsupported Product management resource'); return Object.assign({ name: name }, resource); },
    /** Projects a record to explicitly safe fields. */ project: function (item, fields) { return fields.reduce((result, field) => { if (item && item[field] !== undefined) result[field] = item[field]; return result; }, {}); },
    /** Reads and bounds a Product command payload. */ body: function (request) { let body = request && (request.body || request.model) || {}; if (!body || Array.isArray(body) || typeof body !== 'object') throw SERVICE.DefaultProductEnterpriseScopeService.error('ERR_PRODUCT_00023', 'Product management body must be an object'); if (Buffer.byteLength(JSON.stringify(body)) > Number(this.policy().maximumPayloadBytes || 262144)) throw SERVICE.DefaultProductEnterpriseScopeService.error('ERR_PRODUCT_00024', 'Product management payload is too large'); return body; },
    /** Builds a trusted service request without accepting client enterprise ownership. */ serviceRequest: function (request, extra) { return Object.assign({ tenant: request.tenant, authData: request.authData }, extra || {}); },
    /** Lists a bounded enterprise-owned safe projection. */ list: async function (request) { let enterpriseCode = this.authorize(request), resource = this.resource(request), input = request.query || {}, unknown = Object.keys(input).filter(key => !resource.filters.includes(key) && !['limit', 'page'].includes(key)); if (unknown.length || Object.values(input).some(value => value && typeof value === 'object')) throw SERVICE.DefaultProductEnterpriseScopeService.error('ERR_PRODUCT_00023', 'Product management filters are invalid'); let maximum = Number(this.policy().maximumResultCount || 500), limit = Math.min(maximum, Math.max(1, Number(input.limit) || maximum)), page = Math.max(1, Number(input.page) || 1), query = { enterpriseCode: enterpriseCode }; resource.filters.forEach(key => { if (input[key] !== undefined) query[key] = input[key]; }); let response = await SERVICE[resource.service].get(this.serviceRequest(request, { query: query, searchOptions: { pageSize: limit, pageNumber: page, sort: { updatedAt: -1, code: 1 } } })), items = response && Array.isArray(response.result) ? response.result : []; return { resource: resource.name, page: page, limit: limit, count: items.length, items: items.map(item => this.project(item, resource.fields)) }; },
    /** Gets exactly one Product record by business identity and catalog scope. */ get: async function (request) { let enterpriseCode = this.authorize(request), resource = this.resource(request), businessCode = SERVICE.DefaultProductEnterpriseScopeService.validateBusinessCode(this.parameter(request, 'businessCode'), resource.identity), catalogCode = SERVICE.DefaultProductEnterpriseScopeService.validateBusinessCode(request.query && request.query.catalogCode, 'Catalog'), query = { enterpriseCode: enterpriseCode, catalogCode: catalogCode }; query[resource.identity] = businessCode; let response = await SERVICE[resource.service].get(this.serviceRequest(request, { query: query, searchOptions: { limit: 2 } })), items = response && Array.isArray(response.result) ? response.result : []; if (items.length !== 1) throw SERVICE.DefaultProductEnterpriseScopeService.error('ERR_PRODUCT_00012', 'Product record was not found uniquely'); return this.project(items[0], resource.fields); },
    /** Creates through internal schema services and interceptors. */ create: async function (request) { this.authorize(request); let resource = this.resource(request), model = Object.assign({}, this.body(request)); delete model.enterpriseCode; delete model.code; let response = await SERVICE[resource.service].save(this.serviceRequest(request, { model: model })); return { resource: resource.name, operation: 'CREATED', result: response }; },
    /** Updates mutable fields by enterprise, catalog, and business identity. */ update: async function (request) { let enterpriseCode = this.authorize(request), resource = this.resource(request), businessCode = SERVICE.DefaultProductEnterpriseScopeService.validateBusinessCode(this.parameter(request, 'businessCode'), resource.identity), model = Object.assign({}, this.body(request)), catalogCode = SERVICE.DefaultProductEnterpriseScopeService.validateBusinessCode(model.catalogCode || request.query && request.query.catalogCode, 'Catalog'); delete model.enterpriseCode; delete model.code; delete model.catalogCode; let query = { enterpriseCode: enterpriseCode, catalogCode: catalogCode }; query[resource.identity] = businessCode; let response = await SERVICE[resource.service].update(this.serviceRequest(request, { query: query, model: model })); return { resource: resource.name, operation: 'UPDATED', result: response }; },
    /** Retires a Product record instead of deleting history. */ retire: async function (request) { request.body = Object.assign({}, request.body, { status: 'RETIRED' }); return this.update(request).then(result => Object.assign(result, { operation: 'RETIRED' })); },
    /** Submits an exact Product release through the configured Workflow authority. */ submitPublication: function (request) { this.authorize(request); return SERVICE.DefaultProductPublicationWorkflowService.submit(request); }
};
