module.exports = { core: [ 'core', 'cronjob', 'nems', 'profile', 'system' ],
  ems: [ 'emsClient' ],
  framework: 
   [ 'framework',
     'nconfig',
     'ncommon',
     'ndatabase',
     'ndao',
     'nservice',
     'nprocess',
     'nevent',
     'nfacade',
     'ncontroller',
     'nrouter',
     'ntest' ] };