module.exports = { core: [ 'core', 'cronjob', 'nems', 'profile' ],
  ems: [ 'emsClient', 'ems' ],
  framework: 
   [ 'framework',
     'nconfig',
     'ncommon',
     'ndatabase',
     'ndao',
     'nservice',
     'npipeline',
     'nevent',
     'nfacade',
     'ncontroller',
     'nrouter',
     'ndata',
     'ntest',
     'system' ] };