module.exports = { core: [ 'core', 'cronjob', 'nems', 'user' ],
  framework: 
   [ 'framework',
     'nconfig',
     'ncommon',
     'ndatabase',
     'ndao',
     'nservice',
     'nprocess',
     'nevent',
     'nfacade',
     'ncontroller',
     'nrouter',
     'ntest' ],
  custom: [ 'server' ] };