/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is the confidential and proprietary information of Nodics ("Confidential Information").
    You shall not disclose such Confidential Information and shall use it only in accordance with the
    terms of the license agreement you entered into with Nodics.

 */

/** @module store/service/management/DefaultStoreManagementService @description Provides bounded human Store management intents over private generated persistence services. @layer service @owner store @override Later modules may add allow-listed resources or policy while preserving human identity, enterprise scope, and bounded projections. */
module.exports = {
    /** Initializes management. */ init: function () { return Promise.resolve(true); },
    /** Completes initialization. */ postInit: function () { return Promise.resolve(true); },
    /** Returns allow-listed resources. */ resources: function () { return {
        stores: { service: 'DefaultStoreService', identity: 'storeCode', filters: ['storeCode', 'type', 'status', 'countryCode'], fields: ['code', 'storeCode', 'name', 'type', 'status', 'countryCode', 'timezone', 'addressRef', 'channels', 'capabilities', 'externalReferences', 'effectiveFrom', 'effectiveTo', 'updatedAt'] },
        warehouseAssignments: { service: 'DefaultStoreWarehouseAssignmentService', identity: 'warehouseCode', requiredQuery: 'storeCode', filters: ['storeCode', 'warehouseCode', 'status'], fields: ['code', 'storeCode', 'warehouseCode', 'purposes', 'priority', 'status', 'effectiveFrom', 'effectiveTo', 'updatedAt'] }
    }; },
    /** Returns management policy. */ policy: function () { return (CONFIG.get('store') || {}).management || {}; },
    /** Requires a human access identity. */ authorize: function (request) { let auth = request && request.authData || {}; if (!auth.tokenType || auth.tokenType === 'service' || !(auth.principalId || auth.loginId || auth.code)) throw SERVICE.DefaultStoreEnterpriseScopeService.error('ERR_STORE_00012', 'Store management requires a human principal'); return SERVICE.DefaultStoreEnterpriseScopeService.resolveEnterpriseCode(request); },
    /** Resolves a request parameter. */ parameter: function (request, name) { return request && (request.params && request.params[name] || request.pathParams && request.pathParams[name] || request[name]); },
    /** Resolves one management resource. */ resource: function (request) { let name = this.parameter(request, 'resource'), resource = this.resources()[name]; if (!resource || !(this.policy().allowedResources || []).includes(name) || !SERVICE[resource.service]) throw SERVICE.DefaultStoreEnterpriseScopeService.error('ERR_STORE_00013', 'Unsupported Store management resource'); return Object.assign({ name: name }, resource); },
    /** Projects safe fields. */ project: function (item, fields) { return fields.reduce((output, field) => { if (item && item[field] !== undefined) output[field] = item[field]; return output; }, {}); },
    /** Reads a bounded object payload. */ body: function (request) { let body = request && (request.body || request.model) || {}; if (!body || Array.isArray(body) || typeof body !== 'object') throw SERVICE.DefaultStoreEnterpriseScopeService.error('ERR_STORE_00013', 'Store body must be an object'); if (Buffer.byteLength(JSON.stringify(body)) > Number(this.policy().maximumPayloadBytes || 262144)) throw SERVICE.DefaultStoreEnterpriseScopeService.error('ERR_STORE_00014', 'Store payload exceeds configured bounds'); return body; },
    /** Builds a trusted internal request. */ serviceRequest: function (request, extra) { return Object.assign({ tenant: request.tenant, authData: request.authData }, extra || {}); },
    /** Lists bounded enterprise-owned records. */ list: async function (request) { let enterpriseCode = this.authorize(request), resource = this.resource(request), input = request.query || {}, unknown = Object.keys(input).filter(key => !resource.filters.includes(key) && !['limit', 'page'].includes(key)); if (unknown.length || Object.values(input).some(value => value && typeof value === 'object')) throw SERVICE.DefaultStoreEnterpriseScopeService.error('ERR_STORE_00013', 'Store filters are invalid'); let maximum = Number(this.policy().maximumResultCount || 500), limit = Math.min(maximum, Math.max(1, Number(input.limit) || maximum)), page = Math.max(1, Number(input.page) || 1), query = { enterpriseCode: enterpriseCode }; resource.filters.forEach(key => { if (input[key] !== undefined) query[key] = input[key]; }); let response = await SERVICE[resource.service].get(this.serviceRequest(request, { query: query, searchOptions: { pageSize: limit, pageNumber: page, sort: { updatedAt: -1, code: 1 } } })), items = response && Array.isArray(response.result) ? response.result : []; return { resource: resource.name, page: page, limit: limit, count: items.length, items: items.map(item => this.project(item, resource.fields)) }; },
    /** Gets one record by business identity. */ get: async function (request) { let enterpriseCode = this.authorize(request), resource = this.resource(request), businessCode = SERVICE.DefaultStoreEnterpriseScopeService.validateBusinessCode(this.parameter(request, 'businessCode'), resource.identity), query = { enterpriseCode: enterpriseCode }; query[resource.identity] = businessCode; if (resource.requiredQuery) query[resource.requiredQuery] = SERVICE.DefaultStoreEnterpriseScopeService.validateBusinessCode(request.query && request.query[resource.requiredQuery], resource.requiredQuery); let response = await SERVICE[resource.service].get(this.serviceRequest(request, { query: query, searchOptions: { limit: 2 } })), items = response && Array.isArray(response.result) ? response.result : []; if (items.length !== 1) throw SERVICE.DefaultStoreEnterpriseScopeService.error('ERR_STORE_00015', 'Store record was not found uniquely'); return this.project(items[0], resource.fields); },
    /** Creates through authoritative schema services. */ create: async function (request) { this.authorize(request); let resource = this.resource(request), model = Object.assign({}, this.body(request)); delete model.enterpriseCode; delete model.code; let response = await SERVICE[resource.service].save(this.serviceRequest(request, { model: model })); return { resource: resource.name, operation: 'CREATED', result: response }; },
    /** Updates one enterprise-owned record. */ update: async function (request) { let enterpriseCode = this.authorize(request), resource = this.resource(request), businessCode = SERVICE.DefaultStoreEnterpriseScopeService.validateBusinessCode(this.parameter(request, 'businessCode'), resource.identity), model = Object.assign({}, this.body(request)), query = { enterpriseCode: enterpriseCode }; delete model.enterpriseCode; delete model.code; query[resource.identity] = businessCode; if (resource.requiredQuery) query[resource.requiredQuery] = SERVICE.DefaultStoreEnterpriseScopeService.validateBusinessCode(request.query && request.query[resource.requiredQuery], resource.requiredQuery); let response = await SERVICE[resource.service].update(this.serviceRequest(request, { query: query, model: model })); return { resource: resource.name, operation: 'UPDATED', result: response }; },
    /** Retires history instead of deleting it. */ retire: async function (request) { request.body = { status: 'RETIRED' }; return this.update(request).then(result => Object.assign(result, { operation: 'RETIRED' })); }
};
