/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is the confidential and proprietary information of Nodics ("Confidential Information").
    You shall not disclose such Confidential Information and shall use it only in accordance with the
    terms of the license agreement you entered into with Nodics.

 */

/** @module pricing/service/management/DefaultPricingManagementService @description Human-only bounded Pricing intent API composed over authoritative generated services, validators, and resolver. @layer service @owner pricing */
module.exports = {
    /** Initializes management. */ init: function () { return Promise.resolve(true); },
    /** Completes initialization. */ postInit: function () { return Promise.resolve(true); },
    /** Returns resource ownership, identities, filters, and safe projections. */ resources: function () { return {
        priceLists: { service: 'DefaultPriceListService', identity: 'priceListCode', prepare: 'preparePriceList', filters: ['priceListCode', 'status', 'currencyCode'], fields: ['code', 'priceListCode', 'name', 'description', 'priority', 'currencies', 'taxMode', 'stackingMode', 'status', 'effectiveFrom', 'effectiveTo', 'versionId', 'updatedAt'] },
        assignments: { service: 'DefaultPriceListAssignmentService', identity: 'assignmentCode', prepare: 'prepareAssignmentWithReferences', filters: ['assignmentCode', 'priceListCode', 'scopeType', 'scopeCode', 'status', 'excluded'], fields: ['code', 'assignmentCode', 'priceListCode', 'scopeType', 'scopeCode', 'priority', 'excluded', 'status', 'effectiveFrom', 'effectiveTo', 'versionId', 'updatedAt'] },
        groups: { service: 'DefaultPriceGroupService', identity: 'priceGroupCode', prepare: 'prepareGroup', filters: ['priceGroupCode', 'groupType', 'status'], fields: ['code', 'priceGroupCode', 'name', 'groupType', 'status', 'effectiveFrom', 'effectiveTo', 'versionId', 'updatedAt'] },
        memberships: { service: 'DefaultPriceGroupMemberService', identity: 'membershipCode', prepare: 'prepareMembershipWithReferences', filters: ['membershipCode', 'priceGroupCode', 'memberType', 'memberCode', 'status'], fields: ['code', 'membershipCode', 'priceGroupCode', 'memberType', 'memberCode', 'status', 'effectiveFrom', 'effectiveTo', 'versionId', 'updatedAt'] },
        prices: { service: 'DefaultPriceService', identity: 'priceCode', prepare: 'preparePriceWithReferences', filters: ['priceCode', 'priceListCode', 'itemType', 'itemCode', 'itemPriceGroupCode', 'customerCode', 'customerPriceGroupCode', 'currencyCode', 'unitCode', 'channelCode', 'status'], fields: ['code', 'priceCode', 'priceListCode', 'itemType', 'itemCode', 'itemPriceGroupCode', 'customerCode', 'customerPriceGroupCode', 'amount', 'currencyCode', 'unitCode', 'unitFactor', 'minimumQuantity', 'taxMode', 'channelCode', 'status', 'effectiveFrom', 'effectiveTo', 'versionId', 'updatedAt'] }
    }; },
    /** Returns layered management policy. */ policy: function () { return (CONFIG.get('pricing') || {}).management || {}; },
    /** Creates a stable Pricing error. */ error: function (code, message) { return SERVICE.DefaultPricingEnterpriseScopeService.error(code, message); },
    /** Requires a human access identity independently of route metadata. */ authorize: function (request) { let auth = request && request.authData || {}; if (!auth.tokenType || auth.tokenType === 'service' || !(auth.principalId || auth.loginId || auth.code)) throw this.error('ERR_PRICE_00022', 'Pricing management requires an authenticated human principal'); return SERVICE.DefaultPricingEnterpriseScopeService.resolveEnterpriseCode(request); },
    /** Resolves a route parameter from supported framework request shapes. */ parameter: function (request, name) { return request && (request.params && request.params[name] || request.pathParams && request.pathParams[name] || request[name]); },
    /** Resolves one allow-listed resource. */ resource: function (request) { let name = this.parameter(request, 'resource'), resource = this.resources()[name]; if (!resource || !(this.policy().allowedResources || Object.keys(this.resources())).includes(name) || !SERVICE[resource.service]) throw this.error('ERR_PRICE_00023', 'Unsupported Pricing management resource'); return Object.assign({ name: name }, resource); },
    /** Copies only fields safe for BackOffice clients. */ project: function (item, fields) { return fields.reduce((result, field) => { if (item && item[field] !== undefined) result[field] = item[field]; return result; }, {}); },
    /** Rejects oversized or non-object payloads. */ body: function (request) { let body = request && (request.body || request.model) || {}; if (!body || Array.isArray(body) || typeof body !== 'object') throw this.error('ERR_PRICE_00023', 'Pricing management body must be an object'); if (Buffer.byteLength(JSON.stringify(body)) > Number(this.policy().maximumPayloadBytes || 262144)) throw this.error('ERR_PRICE_00024', 'Pricing management payload is too large'); return body; },
    /** Builds an enterprise-scoped service request without trusting client enterprise fields. */ serviceRequest: function (request, extra) { return Object.assign({ tenant: request.tenant, authData: request.authData }, extra || {}); },
    /** Lists a bounded, projected resource using scalar allow-listed filters only. */ list: async function (request) { let enterpriseCode = this.authorize(request), resource = this.resource(request), input = request.query || {}; let unknown = Object.keys(input).filter(key => !resource.filters.includes(key) && !['limit', 'page'].includes(key)); if (unknown.length || Object.values(input).some(value => value && typeof value === 'object')) throw this.error('ERR_PRICE_00023', 'Pricing management filters are invalid'); let maximum = Number(this.policy().maximumResultCount || 500), limit = Math.min(maximum, Math.max(1, Number(input.limit) || maximum)), page = Math.max(1, Number(input.page) || 1), query = { enterpriseCode: enterpriseCode }; resource.filters.forEach(key => { if (input[key] !== undefined) query[key] = input[key]; }); let response = await SERVICE[resource.service].get(this.serviceRequest(request, { query: query, searchOptions: { pageSize: limit, pageNumber: page, sort: { updatedAt: -1, code: 1 } } })), items = response && Array.isArray(response.result) ? response.result : []; return { resource: resource.name, page: page, limit: limit, count: items.length, items: items.map(item => this.project(item, resource.fields)) }; },
    /** Gets exactly one enterprise-owned record by its public business identity. */ get: async function (request) { let enterpriseCode = this.authorize(request), resource = this.resource(request), businessCode = SERVICE.DefaultPricingEnterpriseScopeService.validateBusinessCode(this.parameter(request, 'businessCode'), resource.identity), query = { enterpriseCode: enterpriseCode }; query[resource.identity] = businessCode; let response = await SERVICE[resource.service].get(this.serviceRequest(request, { query: query, searchOptions: { limit: 2 } })), items = response && Array.isArray(response.result) ? response.result : []; if (items.length !== 1) throw this.error('ERR_PRICE_00019', 'Pricing record was not found uniquely'); return this.project(items[0], resource.fields); },
    /** Creates through the authoritative generated service and schema interceptors. */ create: async function (request) { this.authorize(request); let resource = this.resource(request), model = Object.assign({}, this.body(request)); delete model.enterpriseCode; delete model.code; let response = await SERVICE[resource.service].save(this.serviceRequest(request, { model: model })); return { resource: resource.name, operation: 'CREATED', result: response }; },
    /** Updates mutable fields by enterprise-owned business identity. */ update: async function (request) { let enterpriseCode = this.authorize(request), resource = this.resource(request), businessCode = SERVICE.DefaultPricingEnterpriseScopeService.validateBusinessCode(this.parameter(request, 'businessCode'), resource.identity), model = Object.assign({}, this.body(request)); delete model.enterpriseCode; delete model.code; let query = { enterpriseCode: enterpriseCode }; query[resource.identity] = businessCode; let response = await SERVICE[resource.service].update(this.serviceRequest(request, { query: query, model: model })); return { resource: resource.name, operation: 'UPDATED', result: response }; },
    /** Retires history instead of exposing hard delete. */ retire: async function (request) { request.body = { status: 'RETIRED' }; return this.update(request).then(result => Object.assign(result, { operation: 'RETIRED' })); },
    /** Validates a proposed record without persistence. */ validate: async function (request) { let enterpriseCode = this.authorize(request), body = this.body(request), resourceName = body.resource, resource = this.resources()[resourceName]; if (!resource || !resource.prepare) throw this.error('ERR_PRICE_00023', 'Validation resource is unsupported'); let model = Object.assign({}, body.model || {}); delete model.enterpriseCode; delete model.code; await SERVICE.DefaultPricingValidationService[resource.prepare](this.serviceRequest(request, { model: model })); return { valid: true, resource: resourceName, enterpriseCode: enterpriseCode, normalized: this.project(model, resource.fields) }; },
    /** Detects exact qualifier/date-range overlaps that can become ambiguous at equal rank. */ conflicts: async function (request) { let enterpriseCode = this.authorize(request), body = this.body(request), proposed = body.price || body.model; if (!proposed) throw this.error('ERR_PRICE_00023', 'Proposed Price is required'); let validation = this.serviceRequest(request, { model: Object.assign({}, proposed) }); await SERVICE.DefaultPricingValidationService.preparePriceWithReferences(validation); proposed = validation.model; let query = { enterpriseCode: enterpriseCode, priceListCode: proposed.priceListCode, currencyCode: proposed.currencyCode, unitCode: proposed.unitCode, status: 'ACTIVE' }, response = await SERVICE.DefaultPriceService.get(this.serviceRequest(request, { query: query, searchOptions: { limit: Number(this.policy().maximumPreviewRecords || 5000) } })), items = response && Array.isArray(response.result) ? response.result : [], keys = ['itemType', 'itemCode', 'itemPriceGroupCode', 'customerCode', 'customerPriceGroupCode', 'minimumQuantity', 'channelCode']; let overlaps = items.filter(item => item.priceCode !== proposed.priceCode && keys.every(key => String(item[key] || '') === String(proposed[key] || '')) && (!item.effectiveTo || !proposed.effectiveFrom || new Date(item.effectiveTo) >= new Date(proposed.effectiveFrom)) && (!proposed.effectiveTo || !item.effectiveFrom || new Date(proposed.effectiveTo) >= new Date(item.effectiveFrom))).map(item => this.project(item, this.resources().prices.fields)); return { valid: overlaps.length === 0, enterpriseCode: enterpriseCode, conflictCount: overlaps.length, conflicts: overlaps }; },
    /** Simulates deterministic resolution with human identity but without cache or persistence. */ simulate: async function (request) { this.authorize(request); let body = this.body(request), result = await SERVICE.DefaultPriceResolutionService.resolve(this.serviceRequest(request, { body: body })); return { simulated: true, persisted: false, result: result }; },
    /** Submits a governed Price List release to the existing Workflow authority. */ submitPublication: function (request) { this.authorize(request); this.body(request); return SERVICE.DefaultPricingPublicationWorkflowService.submit(request); }
};
