/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is the confidential and proprietary information of Nodics ("Confidential Information").
    You shall not disclose such Confidential Information and shall use it only in accordance with the
    terms of the license agreement you entered into with Nodics.

 */
/** @module units/test/unitsMultiHopConversionContract @description Validates optional bounded exact graph conversion, reverse edges, and ambiguous shortest-path rejection. @layer test @owner units */
const assert = require('assert'); const units = require('../config/properties').units; class NodicsError extends Error { constructor(code, message) { super(message || code); this.code = code; } } global.CLASSES = { NodicsError }; global.CONFIG = { get: key => key === 'units' ? units : undefined }; global.SERVICE = {}; SERVICE.DefaultExactUnitsService = require('../src/service/exact/defaultExactUnitsService'); SERVICE.DefaultUnitsDefinitionService = require('../src/service/foundation/defaultUnitsDefinitionService'); SERVICE.DefaultUnitsConversionPolicyService = require('../src/service/conversion/defaultUnitsConversionPolicyService');
let definitions = ['A', 'B', 'C', 'D'].map(unitCode => ({ unitCode, status: 'ACTIVE', scopeType: 'GLOBAL', dimensionCode: 'LENGTH', dimensionVector: { LENGTH: 1 }, precisionScale: 3, roundingMode: 'UNNECESSARY' })); let conversions = [{ conversionCode: 'a-b', fromUnitCode: 'A', toUnitCode: 'B', numerator: '2', denominator: '1', status: 'ACTIVE', scopeType: 'GLOBAL', geographicScopeLevel: 'GLOBAL' }, { conversionCode: 'b-c', fromUnitCode: 'B', toUnitCode: 'C', numerator: '3', denominator: '1', status: 'ACTIVE', scopeType: 'GLOBAL', geographicScopeLevel: 'GLOBAL' }]; SERVICE.DefaultUnitOfMeasureService = { get: async request => ({ result: definitions.filter(value => value.unitCode === request.query.unitCode) }) }; SERVICE.DefaultUnitConversionService = { get: async request => ({ result: request.query.fromUnitCode ? conversions.filter(value => value.fromUnitCode === request.query.fromUnitCode && value.toUnitCode === request.query.toUnitCode) : conversions.slice() }) }; const service = require('../src/service/reference/defaultUnitsReferenceService');
(async () => { await assert.rejects(service.convertInternal({ quantity: '2', fromUnitCode: 'A', toUnitCode: 'C', targetScale: 0 }), error => error.code === 'ERR_UNIT_00005'); units.referenceConversion.multiHopEnabled = true; let result = await service.convertInternal({ quantity: '2', fromUnitCode: 'A', toUnitCode: 'C', targetScale: 0 }); assert.strictEqual(result.quantity, '12'); assert.strictEqual(result.conversion.multiHop, true); assert.deepStrictEqual(result.conversion.path.map(value => value.conversionCode), ['a-b', 'b-c']); let reverse = await service.convertInternal({ quantity: '12', fromUnitCode: 'C', toUnitCode: 'A', targetScale: 0 }); assert.strictEqual(reverse.quantity, '2'); conversions.push({ conversionCode: 'a-d', fromUnitCode: 'A', toUnitCode: 'D', numerator: '2', denominator: '1', status: 'ACTIVE', scopeType: 'GLOBAL', geographicScopeLevel: 'GLOBAL' }, { conversionCode: 'd-c', fromUnitCode: 'D', toUnitCode: 'C', numerator: '3', denominator: '1', status: 'ACTIVE', scopeType: 'GLOBAL', geographicScopeLevel: 'GLOBAL' }); await assert.rejects(service.convertInternal({ quantity: '2', fromUnitCode: 'A', toUnitCode: 'C', targetScale: 0 }), error => error.code === 'ERR_UNIT_00004'); units.referenceConversion.multiHopEnabled = false; console.log('Units multi-hop conversion contract validated'); })().catch(error => { console.error(error); process.exit(1); });
