/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */

/** @module product/config/properties @description Layered Product policy, provider, API, and BackOffice capability configuration. @layer configuration @owner product */
module.exports = {
  backofficeCapabilities: {
    product: {
      enabled: true,
      capabilityId: "product-management",
      displayName: "Products",
      category: "commerce",
      icon: "product",
      contractVersion: 1,
      minimumClientContractVersion: 1,
      roles: ["FUNCTIONAL_CAPABILITY_PROVIDER"],
      discovery: {
        openApiPath: "/nodics/system/v0/contract/openapi/internal",
        contractVersion: 1,
      },
      requiredPermissions: ["product.backoffice.read"],
      navigation: [
        {
          id: "catalog-and-products",
          label: "Catalog",
          route: "/commerce/catalog",
          icon: "product",
          order: 410,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["product.backoffice.read"],
          workbenchTarget: { moduleName: "catalog", schemaName: "catalog" },
          help: {
            summary:
              "Author product catalogs, categories, product data, classification, enrichment, and publishing records through owning backend schemas.",
            documentationRoute: "/docs/capabilities/commerce/products",
          },
        },
        {
          id: "catalog-management",
          parentId: "catalog-and-products",
          label: "Catalog Management",
          route: "/commerce/catalog/management",
          icon: "catalog",
          order: 411,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["product.backoffice.read"],
          workbenchTarget: { moduleName: "catalog", schemaName: "catalog" },
          help: {
            summary:
              "Manage the catalog, category, product, variant, and unit records used to organize commerce assortments.",
            documentationRoute: "/docs/capabilities/commerce/products",
          },
        },
        {
          id: "catalogs",
          parentId: "catalog-management",
          label: "Catalogs",
          route: "/commerce/catalog/catalogs",
          icon: "catalog",
          order: 412,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["product.backoffice.read"],
          workbenchTarget: { moduleName: "catalog", schemaName: "catalog" },
          help: {
            summary:
              "Review and maintain nCatalog-owned catalog records used by product and commerce capabilities.",
            documentationRoute: "/docs/capabilities/commerce/products",
          },
        },
        {
          id: "catalog-versions",
          parentId: "catalog-management",
          label: "Catalog Versions",
          route: "/commerce/catalog/versions",
          icon: "catalog",
          order: 413,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "DISABLED",
          help: {
            summary:
              "Planned workspace for staged and online catalog-version lifecycle once the backend model is introduced.",
            documentationRoute: "/docs/capabilities/commerce/products",
          },
        },
        {
          id: "categories",
          parentId: "catalog-management",
          label: "Categories",
          route: "/commerce/catalog/categories",
          icon: "product",
          order: 414,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["product.backoffice.read"],
          workbenchTarget: {
            moduleName: "product",
            schemaName: "productCategory",
          },
          help: {
            summary:
              "Manage product-owned category records, hierarchy metadata, navigation flags, ordering, and lifecycle state.",
            documentationRoute: "/docs/capabilities/commerce/products",
          },
        },
        {
          id: "category-assignments",
          parentId: "catalog-management",
          label: "Category Assignments",
          route: "/commerce/catalog/category-assignments",
          icon: "product",
          order: 415,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["product.backoffice.read"],
          workbenchTarget: {
            moduleName: "product",
            schemaName: "productCategoryAssignment",
          },
          help: {
            summary:
              "Assign products to categories with position, primary flag, effective dates, and lifecycle status.",
            documentationRoute: "/docs/capabilities/commerce/products",
          },
        },
        {
          id: "products",
          parentId: "catalog-management",
          label: "Products",
          route: "/commerce/catalog/products",
          icon: "product",
          order: 416,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "ACTIVE",
          requiredPermissions: ["product.backoffice.read"],
          workbenchTarget: { moduleName: "product", schemaName: "productItem" },
          detailPanels: [
            {
              id: "product-identifiers",
              label: "Product identifiers",
              order: 100,
              target: { moduleName: "product", schemaName: "productIdentifier" },
              relation: {
                sourceField: "itemCode",
                targetField: "itemCode",
                cardinality: "MANY",
              },
              summary:
                "Alternate identifiers and lookup keys attached to the selected product item.",
            },
            {
              id: "product-category-assignments",
              label: "Category assignments",
              order: 110,
              target: {
                moduleName: "product",
                schemaName: "productCategoryAssignment",
              },
              relation: {
                sourceField: "itemCode",
                targetField: "itemCode",
                cardinality: "MANY",
              },
              summary:
                "Category placement, primary flags, and merchandising position for the selected product.",
            },
            {
              id: "product-attributes",
              label: "Product attributes",
              order: 120,
              target: {
                moduleName: "product",
                schemaName: "productAttributeValue",
              },
              relation: {
                sourceField: "itemCode",
                targetField: "itemCode",
                cardinality: "MANY",
              },
              summary:
                "Structured attribute values contributed through the product attribute model.",
            },
            {
              id: "product-media",
              label: "Product media",
              order: 130,
              target: { moduleName: "product", schemaName: "productMedia" },
              relation: {
                sourceField: "itemCode",
                targetField: "itemCode",
                cardinality: "MANY",
              },
              summary:
                "Media assignments that connect product records to governed nMedia assets.",
            },
            {
              id: "product-variants",
              label: "Variant assignments",
              order: 140,
              target: {
                moduleName: "product",
                schemaName: "productVariantAssignment",
              },
              relation: {
                sourceField: "itemCode",
                targetField: "baseItemCode",
                cardinality: "MANY",
              },
              summary:
                "Variant relationships and variant axes for the selected base product.",
            },
            {
              id: "product-relations",
              label: "Product relations",
              order: 150,
              target: { moduleName: "product", schemaName: "productRelation" },
              relation: {
                sourceField: "itemCode",
                targetField: "sourceItemCode",
                cardinality: "MANY",
              },
              summary:
                "Cross-sell, up-sell, replacement, accessory, and other product relationships.",
            },
            {
              id: "product-packaging",
              label: "Packaging",
              order: 160,
              target: { moduleName: "product", schemaName: "productPackaging" },
              relation: {
                sourceField: "itemCode",
                targetField: "itemCode",
                cardinality: "MANY",
              },
              summary:
                "Packaging dimensions, units, and fulfillment-related package metadata.",
            },
          ],
          help: {
            summary:
              "Manage product and SKU records with enterprise, catalog, item type, unit, lifecycle, and sellable or stock-managed flags.",
            documentationRoute: "/docs/capabilities/commerce/products",
          },
        },
        {
          id: "product-variants",
          parentId: "catalog-management",
          label: "Product Variants",
          route: "/commerce/catalog/product-variants",
          icon: "product",
          order: 417,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["product.backoffice.read"],
          workbenchTarget: {
            moduleName: "product",
            schemaName: "productVariantAssignment",
          },
          help: {
            summary:
              "Connect base products to variant items with governed variant combination records.",
            documentationRoute: "/docs/capabilities/commerce/products",
          },
        },
        {
          id: "variant-axes",
          parentId: "catalog-management",
          label: "Variant Axes",
          route: "/commerce/catalog/variant-axes",
          icon: "product",
          order: 418,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["product.backoffice.read"],
          workbenchTarget: {
            moduleName: "product",
            schemaName: "productVariantAxis",
          },
          help: {
            summary:
              "Define the product attributes that act as variant axes for a base product.",
            documentationRoute: "/docs/capabilities/commerce/products",
          },
        },
        {
          id: "units",
          parentId: "catalog-management",
          label: "Units",
          route: "/commerce/catalog/units",
          icon: "units",
          order: 419,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["product.backoffice.read"],
          workbenchTarget: { moduleName: "units", schemaName: "unitOfMeasure" },
          help: {
            summary:
              "Review unit-of-measure records used by product quantities, packaging, pricing, and stock operations.",
            documentationRoute: "/docs/capabilities/commerce/units",
          },
        },
        {
          id: "keywords-tags",
          parentId: "catalog-management",
          label: "Keywords and Tags",
          route: "/commerce/catalog/keywords-tags",
          icon: "product",
          order: 420,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "DISABLED",
          help: {
            summary:
              "Planned workspace for commerce search keywords and tagging once the backend model is introduced.",
            documentationRoute: "/docs/capabilities/commerce/products",
          },
        },
        {
          id: "classification",
          parentId: "catalog-and-products",
          label: "Classification",
          route: "/commerce/catalog/classification",
          icon: "classification",
          order: 430,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["product.backoffice.read"],
          workbenchTarget: {
            moduleName: "product",
            schemaName: "productClassificationClass",
          },
          help: {
            summary:
              "Group products with classification classes, attributes, and assignment records.",
            documentationRoute: "/docs/capabilities/commerce/products",
          },
        },
        {
          id: "classification-systems",
          parentId: "classification",
          label: "Classification Systems",
          route: "/commerce/catalog/classification/systems",
          icon: "classification",
          order: 431,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "DISABLED",
          help: {
            summary:
              "Planned workspace for classification-system boundaries once the backend model is introduced.",
            documentationRoute: "/docs/capabilities/commerce/products",
          },
        },
        {
          id: "classification-classes",
          parentId: "classification",
          label: "Classification Classes",
          route: "/commerce/catalog/classification/classes",
          icon: "classification",
          order: 432,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["product.backoffice.read"],
          workbenchTarget: {
            moduleName: "product",
            schemaName: "productClassificationClass",
          },
          help: {
            summary:
              "Manage classification classes and the attribute codes they expose for product enrichment.",
            documentationRoute: "/docs/capabilities/commerce/products",
          },
        },
        {
          id: "classification-attributes",
          parentId: "classification",
          label: "Classification Attributes",
          route: "/commerce/catalog/classification/attributes",
          icon: "classification",
          order: 433,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["product.backoffice.read"],
          workbenchTarget: {
            moduleName: "product",
            schemaName: "productAttributeDefinition",
          },
          help: {
            summary:
              "Maintain typed product attribute definitions used by enrichment, classification, variants, and references.",
            documentationRoute: "/docs/capabilities/commerce/products",
          },
        },
        {
          id: "classification-assignments",
          parentId: "classification",
          label: "Classification Assignments",
          route: "/commerce/catalog/classification/assignments",
          icon: "classification",
          order: 434,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["product.backoffice.read"],
          workbenchTarget: {
            moduleName: "product",
            schemaName: "productClassificationAssignment",
          },
          help: {
            summary:
              "Assign product items to classification classes with effective lifecycle metadata.",
            documentationRoute: "/docs/capabilities/commerce/products",
          },
        },
        {
          id: "product-enrichment",
          parentId: "catalog-and-products",
          label: "Product Enrichment",
          route: "/commerce/catalog/enrichment",
          icon: "product",
          order: 450,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["product.backoffice.read"],
          workbenchTarget: {
            moduleName: "product",
            schemaName: "productAttributeValue",
          },
          help: {
            summary:
              "Manage product enrichment records such as attributes, media references, relations, bundles, packaging, and identifiers.",
            documentationRoute: "/docs/capabilities/commerce/products",
          },
        },
        {
          id: "product-attributes",
          parentId: "product-enrichment",
          label: "Product Attributes",
          route: "/commerce/catalog/enrichment/attributes",
          icon: "product",
          order: 451,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["product.backoffice.read"],
          workbenchTarget: {
            moduleName: "product",
            schemaName: "productAttributeValue",
          },
          help: {
            summary:
              "Maintain attribute values for product items, including localized, measured, boolean, numeric, and reference values.",
            documentationRoute: "/docs/capabilities/commerce/products",
          },
        },
        {
          id: "product-media",
          parentId: "product-enrichment",
          label: "Product Media",
          route: "/commerce/catalog/enrichment/media",
          icon: "media",
          order: 452,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["product.backoffice.read"],
          workbenchTarget: {
            moduleName: "product",
            schemaName: "productMedia",
          },
          help: {
            summary:
              "Link product records to nMedia-owned media or media sets without copying storage paths or delivery URLs.",
            documentationRoute: "/docs/capabilities/commerce/products",
          },
        },
        {
          id: "product-relations",
          parentId: "product-enrichment",
          label: "Product Relations",
          route: "/commerce/catalog/enrichment/relations",
          icon: "product",
          order: 453,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["product.backoffice.read"],
          workbenchTarget: {
            moduleName: "product",
            schemaName: "productRelation",
          },
          help: {
            summary:
              "Maintain accessory, substitute, replacement, upsell, cross-sell, and related-product graph records.",
            documentationRoute: "/docs/capabilities/commerce/products",
          },
        },
        {
          id: "product-bundles",
          parentId: "product-enrichment",
          label: "Product Bundles",
          route: "/commerce/catalog/enrichment/bundles",
          icon: "product",
          order: 454,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["product.backoffice.read"],
          workbenchTarget: {
            moduleName: "product",
            schemaName: "productBundleEntry",
          },
          help: {
            summary:
              "Manage bundle component entries, quantities, units, positions, and optional component flags.",
            documentationRoute: "/docs/capabilities/commerce/products",
          },
        },
        {
          id: "product-packaging",
          parentId: "product-enrichment",
          label: "Product Packaging",
          route: "/commerce/catalog/enrichment/packaging",
          icon: "product",
          order: 455,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["product.backoffice.read"],
          workbenchTarget: {
            moduleName: "product",
            schemaName: "productPackaging",
          },
          help: {
            summary:
              "Manage product packaging, contained quantity, unit, dimensions, weight, position, and lifecycle state.",
            documentationRoute: "/docs/capabilities/commerce/products",
          },
        },
        {
          id: "product-identifiers",
          parentId: "product-enrichment",
          label: "Product Identifiers",
          route: "/commerce/catalog/enrichment/identifiers",
          icon: "product",
          order: 456,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["product.backoffice.read"],
          workbenchTarget: {
            moduleName: "product",
            schemaName: "productIdentifier",
          },
          help: {
            summary:
              "Maintain external and standard product identifiers such as EAN, UPC, GTIN, ISBN, manufacturer, and parcel codes.",
            documentationRoute: "/docs/capabilities/commerce/products/create",
          },
        },
        {
          id: "product-publishing",
          parentId: "catalog-and-products",
          label: "Product Publishing",
          route: "/commerce/catalog/publishing",
          icon: "publishing",
          order: 470,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["product.backoffice.read"],
          workbenchTarget: {
            moduleName: "product",
            schemaName: "productReleaseManifest",
          },
          help: {
            summary:
              "Inspect product publication manifests, online pointers, receipts, and projection jobs.",
            documentationRoute: "/docs/capabilities/commerce/products",
          },
        },
        {
          id: "product-release-manifests",
          parentId: "product-publishing",
          label: "Product Release Manifests",
          route: "/commerce/catalog/publishing/release-manifests",
          icon: "publishing",
          order: 471,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["product.backoffice.read"],
          workbenchTarget: {
            moduleName: "product",
            schemaName: "productReleaseManifest",
          },
          help: {
            summary:
              "Review versioned release manifests and dependency snapshots prepared for product publication.",
            documentationRoute: "/docs/capabilities/commerce/products",
          },
        },
        {
          id: "online-product-pointers",
          parentId: "product-publishing",
          label: "Online Product Pointers",
          route: "/commerce/catalog/publishing/online-pointers",
          icon: "publishing",
          order: 472,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["product.backoffice.read"],
          workbenchTarget: {
            moduleName: "product",
            schemaName: "productOnlinePointer",
          },
          help: {
            summary:
              "Inspect which product manifest is currently online for an enterprise and catalog.",
            documentationRoute: "/docs/capabilities/commerce/products",
          },
        },
        {
          id: "product-publication-receipts",
          parentId: "product-publishing",
          label: "Product Publication Receipts",
          route: "/commerce/catalog/publishing/receipts",
          icon: "publishing",
          order: 473,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["product.backoffice.read"],
          workbenchTarget: {
            moduleName: "product",
            schemaName: "productPublicationReceipt",
          },
          help: {
            summary:
              "Review publication operation receipts returned by product publication targets.",
            documentationRoute: "/docs/capabilities/commerce/products",
          },
        },
        {
          id: "product-projection-jobs",
          parentId: "product-publishing",
          label: "Product Projection Jobs",
          route: "/commerce/catalog/publishing/projection-jobs",
          icon: "publishing",
          order: 474,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["product.backoffice.read"],
          workbenchTarget: {
            moduleName: "product",
            schemaName: "productProjectionJob",
          },
          help: {
            summary:
              "Monitor product projection jobs that update delivery cache, search, or other publication projections.",
            documentationRoute: "/docs/capabilities/commerce/products",
          },
        },
      ],
    },
  },
  product: {
    lifecycleCancellation: {
      supportedLifecycleTypes: ["PHYSICAL", "SERIALIZED_PHYSICAL", "NON_SERIALIZED_PHYSICAL", "DIGITAL", "PERPETUAL", "INFINITE_INVENTORY", "SERVICE", "SUBSCRIPTION", "LICENSE", "SIM", "ESIM", "PREORDER", "BACKORDER", "DROP_SHIP", "MADE_TO_ORDER"],
      nonPhysicalTypes: ["DIGITAL", "SERVICE", "SUBSCRIPTION", "LICENSE", "SIM", "ESIM", "PERPETUAL", "INFINITE_INVENTORY"],
      terminalEntitlementStates: ["EXPIRED", "REVOKED"],
      activatedState: "ACTIVATED",
      providerAdapters: {},
    },
    enterpriseScope: { required: true },
    identity: {
      separator: "::",
      maxCodeLength: 128,
      codePattern: "^[A-Za-z0-9][A-Za-z0-9._-]*$",
    },
    item: {
      itemTypes: ["PRODUCT", "SKU", "SERVICE", "ASSET", "BUNDLE"],
      stockManagedTypes: ["SKU", "ASSET", "BUNDLE"],
      sellableTypes: ["SKU", "SERVICE", "ASSET", "BUNDLE"],
      statuses: ["DRAFT", "ACTIVE", "SUSPENDED", "RETIRED"],
      allowedTransitions: {
        DRAFT: ["ACTIVE", "RETIRED"],
        ACTIVE: ["SUSPENDED", "RETIRED"],
        SUSPENDED: ["ACTIVE", "RETIRED"],
        RETIRED: [],
      },
      maximumNameLength: 256,
      maximumDescriptionLength: 16384,
    },
    identifier: {
      types: [
        "EAN",
        "UPC",
        "GTIN",
        "ISBN",
        "MANUFACTURER",
        "PARCEL",
        "TITLE",
        "EXTERNAL",
      ],
      maximumValueLength: 256,
    },
    category: {
      maximumDepth: 32,
      minimumOrder: 0,
      maximumOrder: 999999,
      statuses: ["DRAFT", "ACTIVE", "SUSPENDED", "RETIRED"],
      allowedTransitions: {
        DRAFT: ["ACTIVE", "RETIRED"],
        ACTIVE: ["SUSPENDED", "RETIRED"],
        SUSPENDED: ["ACTIVE", "RETIRED"],
        RETIRED: [],
      },
    },
    categoryAssignment: {
      minimumPosition: 0,
      maximumPosition: 999999,
      statuses: ["DRAFT", "ACTIVE", "SUSPENDED", "RETIRED"],
      allowedTransitions: {
        DRAFT: ["ACTIVE", "RETIRED"],
        ACTIVE: ["SUSPENDED", "RETIRED"],
        SUSPENDED: ["ACTIVE", "RETIRED"],
        RETIRED: [],
      },
    },
    attribute: {
      valueTypes: [
        "TEXT",
        "BOOLEAN",
        "INTEGER",
        "DECIMAL",
        "DATE",
        "ENUM",
        "REFERENCE",
        "MEASURED",
      ],
      referenceTypes: ["PRODUCT_ITEM", "EXTERNAL"],
      locales: { pattern: "^[A-Za-z]{2,3}(?:[-_][A-Za-z0-9]{2,8})*$" },
      maximumTextLength: 16384,
      maximumEnumValues: 1000,
      maximumValues: 1000,
      maximumDigits: 38,
      maximumScale: 18,
      statuses: ["DRAFT", "ACTIVE", "SUSPENDED", "RETIRED"],
      allowedTransitions: {
        DRAFT: ["ACTIVE", "RETIRED"],
        ACTIVE: ["SUSPENDED", "RETIRED"],
        SUSPENDED: ["ACTIVE", "RETIRED"],
        RETIRED: [],
      },
    },
    classification: {
      maximumAttributesPerClass: 1000,
      maximumClassesPerItem: 100,
      statuses: ["DRAFT", "ACTIVE", "SUSPENDED", "RETIRED"],
      allowedTransitions: {
        DRAFT: ["ACTIVE", "RETIRED"],
        ACTIVE: ["SUSPENDED", "RETIRED"],
        SUSPENDED: ["ACTIVE", "RETIRED"],
        RETIRED: [],
      },
    },
    variant: {
      baseItemTypes: ["PRODUCT"],
      variantItemTypes: ["SKU", "ASSET"],
      axisValueTypes: [
        "TEXT",
        "BOOLEAN",
        "INTEGER",
        "DECIMAL",
        "ENUM",
        "REFERENCE",
        "MEASURED",
      ],
      maximumAxesPerBase: 20,
      maximumVariantsPerBase: 10000,
      maximumHierarchyDepth: 8,
      requireSellableVariant: true,
      statuses: ["DRAFT", "ACTIVE", "SUSPENDED", "RETIRED"],
      allowedTransitions: {
        DRAFT: ["ACTIVE", "RETIRED"],
        ACTIVE: ["SUSPENDED", "RETIRED"],
        SUSPENDED: ["ACTIVE", "RETIRED"],
        RETIRED: [],
      },
    },
    relation: {
      types: [
        "ACCESSORY",
        "COMPATIBLE",
        "REPLACEMENT",
        "SUBSTITUTE",
        "CROSS_SELL",
        "UP_SELL",
        "RELATED",
      ],
      symmetricTypes: ["COMPATIBLE", "SUBSTITUTE", "RELATED"],
      acyclicTypes: ["REPLACEMENT", "UP_SELL"],
      allowCrossCatalog: false,
      maximumRelationsPerItem: 1000,
      maximumGraphDepth: 32,
      statuses: ["DRAFT", "ACTIVE", "SUSPENDED", "RETIRED"],
      allowedTransitions: {
        DRAFT: ["ACTIVE", "RETIRED"],
        ACTIVE: ["SUSPENDED", "RETIRED"],
        SUSPENDED: ["ACTIVE", "RETIRED"],
        RETIRED: [],
      },
    },
    bundle: {
      bundleItemTypes: ["BUNDLE"],
      maximumEntries: 1000,
      maximumDepth: 16,
      maximumDigits: 38,
      maximumScale: 18,
      statuses: ["DRAFT", "ACTIVE", "SUSPENDED", "RETIRED"],
      allowedTransitions: {
        DRAFT: ["ACTIVE", "RETIRED"],
        ACTIVE: ["SUSPENDED", "RETIRED"],
        SUSPENDED: ["ACTIVE", "RETIRED"],
        RETIRED: [],
      },
    },
    packaging: {
      types: ["EACH", "PACK", "BOX", "CASE", "PALLET", "CONTAINER"],
      maximumEntriesPerItem: 100,
      maximumDigits: 38,
      maximumScale: 18,
      statuses: ["DRAFT", "ACTIVE", "SUSPENDED", "RETIRED"],
      allowedTransitions: {
        DRAFT: ["ACTIVE", "RETIRED"],
        ACTIVE: ["SUSPENDED", "RETIRED"],
        SUSPENDED: ["ACTIVE", "RETIRED"],
        RETIRED: [],
      },
    },
    media: {
      types: ["IMAGE", "VIDEO", "DOCUMENT", "MODEL"],
      roles: [
        "PRIMARY",
        "GALLERY",
        "THUMBNAIL",
        "SWATCH",
        "MANUAL",
        "DATASHEET",
        "VIDEO",
        "ZOOM",
      ],
      referenceModes: ["MEDIA", "MEDIA_SET"],
      maximumEntriesPerItem: 1000,
      statuses: ["DRAFT", "ACTIVE", "SUSPENDED", "RETIRED"],
      allowedTransitions: {
        DRAFT: ["ACTIVE", "RETIRED"],
        ACTIVE: ["SUSPENDED", "RETIRED"],
        SUSPENDED: ["ACTIVE", "RETIRED"],
        RETIRED: [],
      },
    },
    references: {
      providers: {
        catalog: "DefaultProductCatalogReferenceProviderService",
        unit: "DefaultProductUnitsReferenceProviderService",
        media: "DefaultProductMediaReferenceProviderService",
        mediaSet: "DefaultProductMediaReferenceProviderService",
      },
      requireValidationWhenConfigured: true,
    },
    catalogReference: {
      moduleName: "catalog",
      apiVersion: "v0",
      preferLocal: true,
      maximumResults: 2,
    },
    unitsReference: {
      moduleName: "units",
      apiVersion: "v0",
      apiName: "/references/units/convert",
      requestTimeoutMs: 2000,
      maximumAttempts: 2,
      preferLocal: true,
    },
    mediaReference: {
      moduleName: "media",
      apiVersion: "v0",
      apiName: "/references/media/validate",
      requestTimeoutMs: 2000,
      maximumAttempts: 2,
      preferLocal: true,
    },
    management: {
      maximumResultCount: 500,
      maximumPayloadBytes: 262144,
      allowedResources: [
        "items",
        "identifiers",
        "categories",
        "categoryAssignments",
        "attributeDefinitions",
        "attributeValues",
        "classificationClasses",
        "classificationAssignments",
        "variantAxes",
        "variantAssignments",
        "relations",
        "bundleEntries",
        "packaging",
        "media",
      ],
    },
    workflow: {
      enabled: true,
      defaultMode: "MANUAL",
      modes: ["MANUAL", "AUTOMATIC"],
      manualWorkflowCode: "productPublicationManualFlow",
      automaticWorkflowCode: "productPublicationAutomaticFlow",
      maximumAssociatedItems: 20000,
      allowedAssociatedSchemas: [
        "productItem",
        "productIdentifier",
        "productCategory",
        "productCategoryAssignment",
        "productAttributeDefinition",
        "productAttributeValue",
        "productClassificationClass",
        "productClassificationAssignment",
        "productVariantAxis",
        "productVariantAssignment",
        "productRelation",
        "productBundleEntry",
        "productPackaging",
        "productMedia",
      ],
    },
    publication: {
      enabled: false,
      runtimeRole: "UNASSIGNED",
      rootTypes: {
        PRODUCT_ITEM: {
          schema: "productItem",
          service: "DefaultProductItemService",
        },
      },
      maxDependencies: 20000,
      targetTransportProvider: null,
      target: {
        moduleName: null,
        connectionName: null,
        connectionType: "abstract",
        timeoutMs: 30000,
        maxAttempts: 3,
        maxManifestBytes: 20971520,
        supportedContractVersions: [1],
      },
    },
    delivery: {
      maximumExpansions: 8,
      maximumRecordsPerExpansion: 1000,
      allowedExpansions: [
        "identifiers",
        "categories",
        "attributes",
        "classifications",
        "variants",
        "relations",
        "bundles",
        "packaging",
        "media",
      ],
      localePattern: "^[A-Za-z]{2,3}(?:[-_][A-Za-z0-9]{2,8})*$",
    },
    storefrontContext: {
      headerName: "x-nodics-storefront-context",
      moduleName: "storefront",
      apiVersion: "v0",
      apiName: "/context/introspect",
      bootstrapTenant: "default",
      preferLocal: true,
      requestTimeoutMs: 1000,
      maximumAttempts: 1,
      maximumResponseBytes: 32768,
    },
    cache: {
      enabled: true,
      moduleName: "product",
      channelName: "delivery",
      keyPrefix: "productDelivery:",
      ttlSeconds: 300,
      maximumKeyLength: 256,
    },
    searchProjection: {
      enabled: false,
      provider: "DefaultProductSearchProjectionProviderService",
      indexerCode: "productOnlineIndexer",
      indexName: "productOnline",
      maximumDocuments: 20000,
    },
    projection: {
      enabled: true,
      maximumAttempts: 10,
      reconciliationBatchSize: 100,
      retryStates: ["PENDING", "PARTIAL", "FAILED"],
    },
    referenceLookup: {
      maximumResultCount: 100,
      allowedItemTypes: ["PRODUCT", "SKU", "SERVICE", "ASSET", "BUNDLE"],
    },
  },
  cache: {
    product: {
      channels: {
        delivery: { enabled: true, fallback: true, engine: "local", ttl: 300 },
      },
    },
  },
  publish: {
    providers: {
      domainAdapters: { product: "DefaultProductPublicationAdapterService" },
      versionProviders: {
        product: "DefaultProductPublicationVersionProviderService",
      },
    },
  },
};
