/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */

/**
 * @module order/config/properties
 * @description Reserved order property contribution for module-level configuration defaults.
 * @layer config
 * @owner order
 * @override Project modules may provide later property contributions for order lifecycle, validation, and integration settings.
 */
module.exports = {
  order: {
    calculation: {
      enabled: true,
      validationPipeline: {
        name: "orderValidationPipeline",
        steps: [
          "validateOrderContext",
          "validateEntries",
          "validateAllocations",
          "validatePaymentEvidence",
          "validateHistoricalEvidence",
        ],
      },
      entryPipeline: {
        name: "orderEntryCalculationPipeline",
        steps: [
          "resolveOrderEntryContext",
          "reconcileEntryPriceEvidence",
          "reconcileEntryPromotions",
          "reconcileEntryTax",
          "reconcileInventoryEvidence",
          "prepareOrderEntryTotals",
        ],
      },
      orderPipeline: {
        name: "orderCalculationPipeline",
        steps: [
          "validateOrder",
          "calculateEntries",
          "reconcileDeliveryCharges",
          "reconcileOrderPromotions",
          "reconcileOrderTax",
          "reconcilePaymentEvidence",
          "prepareOrderTotals",
        ],
      },
      authority: {
        product: "product",
        pricing: "pricing",
        promotion: "promotion",
        tax: "tax",
        inventory: "inventory",
        payment: "payment",
        fulfillment: "fulfillment",
      },
      historicalEvidencePolicy: {
        preserveCheckoutEvidence: true,
        recalculationRequiresLifecycleOperation: true,
      },
      delegates: {
        orderEntryContext: {
          ownerModule: "order",
          serviceNames: ["DefaultOrderEntryContextService"],
          operations: ["resolve"],
        },
        priceEvidence: {
          ownerModule: "pricing",
          serviceNames: ["DefaultPriceResolutionService"],
          operations: ["resolve"],
        },
        promotionEvidence: {
          ownerModule: "promotion",
          serviceNames: ["DefaultPromotionEvaluationService"],
          operations: ["reconcileEntry"],
        },
        orderPromotionEvidence: {
          ownerModule: "promotion",
          serviceNames: ["DefaultPromotionEvaluationService"],
          operations: ["reconcileOrder"],
        },
        taxEvidence: {
          ownerModule: "tax",
          serviceNames: ["DefaultTaxCalculationService"],
          operations: ["reconcileEntryTax"],
        },
        inventoryEvidence: {
          ownerModule: "inventory",
          serviceNames: [
            "DefaultInventoryPromiseReadinessService",
            "DefaultStockAvailabilityIntentService",
          ],
          operations: ["reconcileEntryPromise", "resolve"],
        },
      },
    },
    checkoutEntry: {
      policy: {
        statuses: ["ORDERED", "ALLOCATED", "CANCELLED", "RETURNED"],
        taxInclusionModes: ["TAX_EXCLUSIVE", "TAX_INCLUSIVE"],
        immutableFields: [
          "code",
          "entCode",
          "entryCode",
          "orderCode",
          "cartCode",
          "catalogCode",
          "itemType",
          "itemCode",
          "quantity",
          "unitCode",
          "currencyCode",
          "unitPrice",
          "unitNetAmount",
          "unitGrossAmount",
          "totalPrice",
          "lineNetAmount",
          "lineGrossAmount",
          "taxTotal",
          "taxInclusionMode",
          "taxIncluded",
          "taxQuoteCode",
          "taxQuoteLineCode",
          "taxJurisdictionCode",
          "taxCategoryCode",
          "taxRateCode",
          "discountTotal",
          "priceEvidenceCode",
        ],
        allowedTransitions: {
          ORDERED: ["ALLOCATED", "CANCELLED"],
          ALLOCATED: ["CANCELLED", "RETURNED"],
          CANCELLED: [],
          RETURNED: [],
        },
        conversion: {
          sourceParentField: "cartCode",
          targetParentField: "orderCode",
          targetStatus: "ORDERED",
          copiedFields: [
            "entCode",
            "entryCode",
            "lineNumber",
            "catalogCode",
            "itemType",
            "itemCode",
            "quantity",
            "unitCode",
            "currencyCode",
            "unitPrice",
            "unitNetAmount",
            "unitGrossAmount",
            "totalPrice",
            "lineNetAmount",
            "lineGrossAmount",
            "taxTotal",
            "taxInclusionMode",
            "taxIncluded",
            "taxQuoteCode",
            "taxQuoteLineCode",
            "taxJurisdictionCode",
            "taxCategoryCode",
            "taxRateCode",
            "discountTotal",
            "priceEvidenceCode",
          ],
        },
      },
    },
    checkoutAllocation: {
      policy: {
        quantityPattern: "^(0|[1-9][0-9]*)(\\.[0-9]+)?$",
        moneyPattern: "^(0|[1-9][0-9]*)(\\.[0-9]+)?$",
        maximumDigits: 38,
        maximumScale: 18,
        deliveryGroupTypes: ["ADDRESS", "PICKUP", "DIGITAL", "SERVICE"],
        deliveryGroupStatuses: [
          "ORDERED",
          "ALLOCATED",
          "RELEASED",
          "SHIPPED",
          "CANCELLED",
          "RETURNED",
        ],
        paymentGroupStatuses: [
          "ORDERED",
          "AUTHORIZED",
          "CAPTURED",
          "PARTIALLY_REFUNDED",
          "REFUNDED",
          "CANCELLED",
        ],
        allocationStatuses: [
          "ORDERED",
          "RESERVED",
          "ALLOCATED",
          "RELEASED",
          "SHIPPED",
          "CANCELLED",
          "RETURNED",
        ],
        conversion: {
          sourceParentField: "cartCode",
          targetParentField: "orderCode",
          targetStatus: "ORDERED",
          deliveryGroupCopiedFields: [
            "entCode",
            "deliveryGroupCode",
            "groupType",
            "addressCode",
            "deliveryModeCode",
            "carrierCode",
            "deliveryChargeQuoteCode",
            "deliveryChargeAmount",
            "deliveryChargeCurrencyCode",
            "deliveryChargeTaxMode",
          ],
          paymentGroupCopiedFields: [
            "entCode",
            "paymentGroupCode",
            "paymentModeCode",
            "currencyCode",
            "plannedAmount",
            "authorizedAmount",
            "capturedAmount",
            "refundedAmount",
            "paymentEvidenceCode",
          ],
          deliveryAllocationCopiedFields: [
            "entCode",
            "allocationCode",
            "entryCode",
            "deliveryGroupCode",
            "quantity",
            "unitCode",
            "serialNumbers",
            "inventoryReservationCode",
            "inventoryAllocationCode",
          ],
          paymentAllocationCopiedFields: [
            "entCode",
            "allocationCode",
            "entryCode",
            "paymentGroupCode",
            "quantity",
            "unitCode",
            "serialNumbers",
            "inventoryReservationCode",
            "inventoryAllocationCode",
            "amount",
            "currencyCode",
          ],
        },
      },
    },
    checkoutPlacement: {
      enabled: true,
      workflow: {
        enabled: true,
        manualWorkflowCode: "checkoutPlacementManualFlow",
        automaticWorkflowCode: "checkoutPlacementAutomaticFlow",
        defaultMode: "AUTOMATIC",
        modes: ["MANUAL", "AUTOMATIC"],
      },
      pipeline: {
        name: "checkoutPlacementRunPipeline",
        states: ["INIT", "RUNNING", "COMPLETED", "FAILED"],
        steps: ["validateRequest", "startPlacementRun", "finalizePlacementRun"],
      },
      validation: {
        allowedCartStatuses: ["ACTIVE", "READY_FOR_CHECKOUT", "CHECKOUT_READY"],
        maximumAggregateRecords: 1000,
      },
      inventoryReservation: {
        enabled: true,
        allocationSource: "delivery",
        demandType: "CART",
        promiseCodeFields: ["promiseCode", "inventoryPromiseCode"],
        defaultReasonCode: "CHECKOUT_PLACEMENT",
        maximumAggregateRecords: 1000,
      },
      orderProjection: {
        enabled: true,
        orderCodePrefix: "order",
        refCodePrefix: "checkout",
        orderStatus: "PLACED",
        entryStatus: "ORDERED",
        maximumAggregateRecords: 1000,
      },
      allocationCopy: {
        enabled: true,
        targetStatus: "ORDERED",
        maximumAggregateRecords: 1000,
      },
      paymentAuthorization: {
        enabled: true,
        ownerModule: "payment",
        maximumAggregateRecords: 1000,
      },
      fulfillmentRelease: {
        enabled: true,
        ownerModule: "fulfillment",
        maximumAggregateRecords: 1000,
      },
      compensation: {
        enabled: true,
        releaseInventoryReservations: true,
        cancelFulfillmentReleases: true,
        inventoryReleaseState: "RELEASED",
        inventoryReleaseReasonCode: "CHECKOUT_PLACEMENT_FAILED",
        recordOrderHistory: true,
        failedOrderStatus: "PLACEMENT_FAILED",
        failureMessageLimit: 240,
      },
    },
    checkoutReverse: {
      enabled: true,
      workflow: {
        enabled: true,
        manualWorkflowCode: "checkoutReverseManualFlow",
        automaticWorkflowCode: "checkoutReverseAutomaticFlow",
        defaultMode: "MANUAL",
        modes: ["MANUAL", "AUTOMATIC"],
      },
      states: [
        "INIT",
        "RUNNING",
        "RETURN_REQUESTED",
        "RETURN_APPROVED",
        "RETURN_RECEIVED",
        "RETURN_DISPOSED",
        "INVENTORY_DISPOSITION_APPLIED",
        "REFUND_CALCULATED",
        "REFUNDED",
        "COMPLETED",
        "FAILED",
        "COMPENSATING",
      ],
      returnRequest: {
        enabled: true,
        ownerModule: "fulfillment",
        recoveryService: "DefaultReturnRequestService",
        defaultReturnType: "CUSTOMER_RETURN",
        defaultReturnReasonCode: "CUSTOMER_RETURN",
        defaultDispositionCode: "INSPECT",
      },
      inventoryDisposition: {
        enabled: true,
        ownerModule: "inventory",
        service: "DefaultReturnDispositionMovementService",
        recoveryService: "DefaultReturnDispositionMovementService",
        executeBeforeRefundCalculation: true,
      },
      paymentRefund: {
        enabled: true,
        ownerModule: "payment",
        requireReceivedReturnBeforeRefund: true,
        calculateBeforeRefund: true,
        allocationSourceService: "DefaultOrderPaymentAllocationService",
        recoveryService: "DefaultPaymentRefundService",
        maximumAggregateRecords: 1000,
      },
      history: {
        enabled: true,
        eventType: "ORDER_REVERSE_FLOW",
        completedStatus: "RETURN_REFUNDED",
      },
      compensation: {
        enabled: true,
        state: "COMPENSATING",
        failureCode: "CHECKOUT_REVERSE_FAILED",
        failureMessageLimit: 240,
        recoveryStrategies: {
          RUNNING: "ORDER_RETRY_REQUIRED",
          RETURN_REQUESTED: "FULFILLMENT_REVIEW_REQUIRED",
          RETURN_APPROVED: "FULFILLMENT_REVIEW_REQUIRED",
          RETURN_RECEIVED: "FULFILLMENT_REVIEW_REQUIRED",
          RETURN_DISPOSED: "INVENTORY_REVIEW_REQUIRED",
          INVENTORY_DISPOSITION_APPLIED: "PAYMENT_RETRY_REQUIRED",
          REFUND_CALCULATED: "PAYMENT_RETRY_REQUIRED",
          REFUNDED: "ORDER_HISTORY_RETRY_REQUIRED",
          COMPLETED: "NO_COMPENSATION_REQUIRED",
        },
        ownerActions: {
          fulfillment: ["REVIEW_RETURN", "CLOSE_OR_CANCEL_RETURN"],
          inventory: [
            "REVIEW_DISPOSITION_MOVEMENT",
            "ADJUST_THROUGH_STOCK_MOVEMENT",
          ],
          payment: ["RETRY_REFUND", "RECONCILE_PROVIDER_REFUND"],
          order: ["RETRY_HISTORY", "MARK_RECOVERY_COMPLETE"],
        },
      },
      failureMessageLimit: 240,
    },
    orderLifecycle: {
      enabled: true,
      requestTypes: ["CANCELLATION", "RETURN", "REFUND"],
      requestStates: [
        "DRAFT",
        "SUBMISSION_PENDING",
        "SUBMISSION_FAILED",
        "SUBMITTED",
        "AUTHORIZATION_PENDING",
        "AUTHORIZED",
        "INFORMATION_REQUESTED",
        "INFORMATION_PROVIDED",
        "ESCALATED",
        "APPROVAL_PENDING",
        "APPROVED",
        "EXECUTING",
        "PARTIALLY_COMPLETED",
        "COMPLETED",
        "FAILED",
        "RECONCILIATION_REQUIRED",
        "REJECTED",
        "CANCELLED",
        "EXPIRED",
      ],
      terminalRequestStates: ["COMPLETED", "REJECTED", "CANCELLED", "EXPIRED"],
      itemStates: [
        "REQUESTED",
        "AUTHORIZATION_PENDING",
        "AUTHORIZED",
        "PARTIALLY_AUTHORIZED",
        "APPROVED",
        "REJECTED",
        "INFORMATION_REQUESTED",
        "RECEIVED",
        "INSPECTION",
        "DISPOSITIONED",
        "COMPLETED",
        "CANCELLED",
      ],
      terminalItemStates: ["REJECTED", "COMPLETED", "CANCELLED"],
      initialRequestState: "DRAFT",
      initialItemState: "REQUESTED",
      maximumItemsPerRequest: 100,
      maximumSerialNumbersPerItem: 100,
      maximumReasonLength: 500,
      reasonCodes: {
        CANCELLATION: ["CUSTOMER_REQUEST", "SUPPORT_CORRECTION"],
        RETURN: ["CUSTOMER_RETURN", "DAMAGED", "WRONG_ITEM", "WARRANTY", "EXCHANGE_ONLY", "NO_REFUND"],
        REFUND: ["GOODWILL", "DAMAGED_IN_TRANSIT", "MISSING_ITEM", "SERVICE_CREDIT", "PRICE_CORRECTION", "CORRECTION"],
      },
      persistence: {
        mutationFlag: "_orderLifecycleMutationAuthorized",
        hardDeleteAllowed: false,
        transactionModuleName: "order",
      },
      workflow: {
        enabled: true,
        defaultWorkflowCode: "orderLifecycleRequestFlow",
        workflowCodeByRequestType: {
          CANCELLATION: "orderLifecycleRequestFlow",
          RETURN: "orderReturnRequestFlow",
          REFUND: "orderRefundRequestFlow",
        },
        carrierPrefix: "orderLifecycle",
        approval: {
          defaultRoute: "MANUAL_REVIEW",
          autoApprovalEnabled: false,
          autoApprovalMaximumAmount: "0",
          autoApprovalRequesterTypes: ["SERVICE", "SYSTEM"],
          makerCheckerRequired: true,
          manualApproverTokenTypes: ["access"],
          maximumDecisionEvidenceBytes: 262144,
        },
      },
      policy: {
        version: "1",
        cancellationWindows: [{ policyCode: "STANDARD_CANCELLATION", tenant: "*", enterpriseCode: "*", siteCode: "*", channelCode: "*", productType: "*", orderStates: ["PLACED", "PROCESSING"], fulfillmentStates: ["UNRELEASED", "RELEASED"], paymentStates: ["UNPAID", "DEFERRED", "AUTHORIZED", "CAPTURED", "SETTLED"], windowMinutes: 1440 }],
        returnWindows: [{ policyCode: "STANDARD_RETURN", productCode: "*", categoryCode: "*", conditionCodes: ["UNOPENED", "OPENED", "DAMAGED"], countryCode: "*", customerSegment: "*", channelCode: "*", deliveryAgeDays: 30, warrantyRequired: false }],
        refundableAmounts: [{ policyCode: "STANDARD_REFUND", outcomes: ["FULL", "ITEM_ONLY", "TAX_ONLY", "SHIPPING", "RESTOCKING_FEE", "GOODWILL_CREDIT", "MANUAL_ADJUSTMENT"], shippingMode: "PROPORTIONAL", restockingFee: { mode: "NONE", amount: "0" }, manualAdjustmentRequiresApproval: true }],
        productRestrictions: [{ policyCode: "DEFAULT_PRODUCT_RESTRICTION", productType: "*", categoryCode: "*", returnable: true, refundable: true, reasonCode: "STANDARD" }],
        approvalEscalations: [{ policyCode: "STANDARD_APPROVAL", minimumAmount: "0", maximumAmount: "*", roles: ["order.refund.approve"], departmentCode: "*", enterpriseCode: "*", countryCode: "*", paymentMethodCode: "*", riskBands: ["LOW", "MEDIUM", "HIGH", "UNKNOWN"], route: "MANUAL_REVIEW", makerCheckerRequired: true }],
        evidenceRequirements: [{ policyCode: "STANDARD_EVIDENCE", reasonCodes: ["*"], requiredEvidence: [], supportedEvidence: ["IMAGE", "PACKAGE_CONDITION", "CARRIER_TRACKING", "SERIAL_NUMBER", "INVOICE", "SUPPORT_NOTE"], maximumAttachmentCount: 10 }],
        lifecycleTimers: [{ policyCode: "STANDARD_SLA", requestTypes: ["CANCELLATION", "RETURN", "REFUND"], states: ["SUBMITTED", "APPROVAL_PENDING", "INFORMATION_REQUESTED", "RECONCILIATION_REQUIRED"], expiryMinutes: 10080, slaMinutes: 1440, escalationMinutes: 720, abandonedState: "CANCELLED" }],
        exceptionRoutes: [{ policyCode: "STANDARD_EXCEPTION", findingCodes: ["PROVIDER_FAILURE", "RETURN_ITEM_MISSING", "RETURN_ITEM_DAMAGED", "FRAUD_REVIEW", "OVER_REFUND_RISK", "MANUAL_CORRECTION"], route: "HUMAN_REVIEW", ownerByFinding: { PROVIDER_FAILURE: "payment", RETURN_ITEM_MISSING: "fulfillment", RETURN_ITEM_DAMAGED: "fulfillment", FRAUD_REVIEW: "workflow", OVER_REFUND_RISK: "payment", MANUAL_CORRECTION: "order-workflow" } }],
      },
      cancellationEligibility: {
        enabled: true,
        pipelineName: "orderCancellationEligibilityPipeline",
        cancellableOrderStates: ["PLACED", "PROCESSING"],
        cancellationWindowMinutes: 1440,
        maximumItemsPerEvaluation: 100,
        fulfillmentBlockingStates: ["SHIPPED", "DELIVERED"],
        paymentActions: {
          AUTHORIZED: "VOID",
          CAPTURED: "REFUND",
          SETTLED: "REFUND",
          DEFERRED: "NONE",
          UNPAID: "NONE",
        },
        evidenceProviders: {
          inventory: {
            ownerModule: "inventory",
            service: "DefaultOrderCancellationInventoryEvidenceProviderService",
            operation: "resolve",
          },
          fulfillment: {
            ownerModule: "fulfillment",
            service: "DefaultOrderCancellationFulfillmentEvidenceProviderService",
            operation: "resolve",
          },
          payment: {
            ownerModule: "payment",
            service: "DefaultOrderCancellationPaymentEvidenceProviderService",
            operation: "resolve",
          },
          product: {
            ownerModule: "product",
            service: "DefaultOrderCancellationProductEvidenceProviderService",
            operation: "resolve",
          },
        },
      },
      cancellationCalculation: {
        enabled: true,
        pipelineName: "orderCancellationCalculationPipeline",
        maximumAggregateRecords: 1000,
        orderEntrySourceService: "DefaultOrderEntryService",
        paymentAllocationSourceService: "DefaultOrderPaymentAllocationService",
        paymentCalculationService: "DefaultPaymentRefundCalculationService",
        taxRefundEvidenceService: "DefaultTaxRefundEvidenceService",
        promotionRefundImpactService: "DefaultPromotionRefundImpactService",
        shippingRefundPolicyService: "DefaultFulfillmentShippingRefundPolicyService",
      },
      cancellationExecution: {
        enabled: true,
        pipelineName: "orderCancellationExecutionPipeline",
        maximumOwnerOperations: 300,
        fulfillmentService: "DefaultFulfillmentCancellationIntentService",
        inventoryService: "DefaultStockAllocationCancellationOrchestrationService",
        paymentService: "DefaultPaymentCancellationExecutionService",
        productLifecycleService: "DefaultProductLifecycleCancellationService",
      },
      intents: {
        maximumEntries: 500,
        maximumEvidenceMedia: 10,
        maximumInformationLength: 2000,
        customerOwnOrderRequired: true,
        supportCustomerMatchRequired: true,
        rateLimit: { enabled: true, windowMs: 60000, max: 10, key: "principal-order" },
      },
      returnValidation: { enabled: true, pipelineName: "returnRequestValidationPipeline", maximumItems: 100, evidenceProviders: {
        fulfillment: { ownerModule: "fulfillment", service: "DefaultOrderReturnFulfillmentEvidenceProviderService" },
        product: { ownerModule: "product", service: "DefaultOrderReturnProductEvidenceProviderService" },
      } },
      returnAuthorization: { pipelineName: "returnAuthorizationPipeline", defaultRoute: "MANUAL_REVIEW", autoApprovalEnabled: false, autoApprovalRequesterTypes: ["SERVICE", "SYSTEM"] },
      refundCalculation: { pipelineName: "refundCalculationPipeline" },
      refundApproval: { pipelineName: "refundApprovalPreparationPipeline", defaultRoute: "MANUAL_REVIEW", autoApprovalEnabled: false, autoApprovalMaximumAmount: "0", autoApprovalRequesterTypes: ["SERVICE", "SYSTEM"], approvalRules: [] },
      refundExecution: { pipelineName: "refundExecutionPipeline", productEvidenceService: "DefaultOrderCancellationProductEvidenceProviderService", productLifecycleService: "DefaultProductLifecycleCancellationService", paymentExecutionService: "DefaultPaymentRefundExecutionService" },
      operations: { maximumScanRecords: 500, slaMinutesByState: { SUBMISSION_PENDING: 5, SUBMISSION_FAILED: 15, SUBMITTED: 15, APPROVAL_PENDING: 1440, AUTHORIZATION_PENDING: 1440, INFORMATION_REQUESTED: 2880, EXECUTING: 15, ESCALATED: 240 }, ownerContributors: [{ owner: "payment", service: "DefaultPaymentRefundDiagnosticsService", operation: "scan" }, { owner: "inventory", service: "DefaultReturnStockDiagnosticsService", operation: "scan" }] },
      statusProjection: { approvedStates: ["APPROVED", "AUTHORIZED", "EXECUTING", "COMPLETED", "RECONCILIATION_REQUIRED"], expectedActionMinutesByState: { SUBMISSION_PENDING: 5, SUBMITTED: 15, APPROVAL_PENDING: 1440, AUTHORIZATION_PENDING: 1440, INFORMATION_REQUESTED: 2880, INFORMATION_PROVIDED: 240, EXECUTING: 15, RECONCILIATION_REQUIRED: 240, ESCALATED: 240 } },
      events: { maximumCorrelationReferences: 100, supportMessageTemplates: ["ORDER_LIFECYCLE_STATUS_UPDATE", "ORDER_LIFECYCLE_INFORMATION_GUIDANCE", "ORDER_LIFECYCLE_DECISION_EXPLANATION"], maximumTemplateVariables: 20, notificationByEventType: { CANCELLATION_SUBMITTED: { templateCode: "ORDER_CANCELLATION_REQUESTED", audiences: ["CUSTOMER", "SUPPORT"] }, CANCELLATION_APPROVED: { templateCode: "ORDER_CANCELLATION_APPROVED", audiences: ["CUSTOMER", "SUPPORT"] }, CANCELLATION_COMPLETED: { templateCode: "ORDER_CANCELLATION_COMPLETED", audiences: ["CUSTOMER", "SUPPORT"] }, RETURN_SUBMITTED: { templateCode: "ORDER_RETURN_REQUESTED", audiences: ["CUSTOMER", "SUPPORT"] }, RETURN_AUTHORIZED: { templateCode: "ORDER_RETURN_AUTHORIZED", audiences: ["CUSTOMER", "SUPPORT", "WAREHOUSE"] }, RETURN_REJECTED: { templateCode: "ORDER_RETURN_REJECTED", audiences: ["CUSTOMER", "SUPPORT"] }, REFUND_SUBMITTED: { templateCode: "ORDER_REFUND_REQUESTED", audiences: ["CUSTOMER", "SUPPORT"] }, REFUND_APPROVED: { templateCode: "ORDER_REFUND_APPROVED", audiences: ["CUSTOMER", "SUPPORT", "FINANCE"] }, REFUND_EXECUTED: { templateCode: "ORDER_REFUND_EXECUTED", audiences: ["CUSTOMER", "SUPPORT", "FINANCE"] }, REFUND_RECONCILIATION_REQUIRED: { templateCode: "ORDER_REFUND_EXCEPTION", audiences: ["SUPPORT", "FINANCE"] }, ORDER_LIFECYCLE_INFORMATION_REQUESTED: { templateCode: "ORDER_LIFECYCLE_INFORMATION_REQUIRED", audiences: ["CUSTOMER", "SUPPORT"] } } },
    },
  },
  backofficeCapabilities: {
    order: {
      enabled: true,
      capabilityId: "order-management",
      displayName: "Orders",
      category: "commerce",
      icon: "commerce",
      contractVersion: 1,
      minimumClientContractVersion: 1,
      roles: ["FUNCTIONAL_CAPABILITY_PROVIDER"],
      discovery: {
        openApiPath: "/nodics/system/v0/contract/openapi/internal",
        contractVersion: 1,
      },
      navigation: [
        {
          id: "checkout",
          parentId: "commerce-operations",
          parentModuleName: "pricing",
          label: "Checkout",
          route: "/commerce/operations/checkout",
          icon: "commerce",
          order: 580,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["order.backoffice.read"],
          workbenchTarget: { moduleName: "order", schemaName: "order" },
          help: {
            summary:
              "Review checkout journey records such as orders, order statuses, payment statuses, and shipping statuses.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "orders",
          parentId: "checkout",
          label: "Orders",
          route: "/commerce/operations/checkout/orders",
          icon: "commerce",
          order: 582,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["order.backoffice.read"],
          workbenchTarget: { moduleName: "order", schemaName: "order" },
          lifecycleActions: [
            { id: "support-create-cancellation", label: "Create cancellation", intent: "CREATE", permission: "order.cancellation.support.create", ownerModule: "order", operationRoute: "/operations/cancellations", summary: "Create a scoped cancellation intent; Order and owner Pipelines evaluate it.", inputFields: [{ name: "entCode", label: "Enterprise", type: "HIDDEN", required: true, valueFromRecord: "enterpriseCode" }, { name: "orderCode", label: "Order", type: "HIDDEN", required: true, valueFromRecord: "code" }, { name: "reasonCode", label: "Reason", type: "SELECT", required: true, options: ["CUSTOMER_REQUEST", "SUPPORT_CORRECTION"] }, { name: "items", label: "Items JSON", type: "JSON", required: true, maximumLength: 4000, defaultValue: "[]" }], order: 10 },
            { id: "support-create-return", label: "Create Return", intent: "CREATE", permission: "order.return.support.create", ownerModule: "order", operationRoute: "/operations/returns", summary: "Create a scoped Return intent; Fulfillment and Product provide owner evidence.", inputFields: [{ name: "entCode", label: "Enterprise", type: "HIDDEN", required: true, valueFromRecord: "enterpriseCode" }, { name: "orderCode", label: "Order", type: "HIDDEN", required: true, valueFromRecord: "code" }, { name: "reasonCode", label: "Reason", type: "SELECT", required: true, options: ["CUSTOMER_RETURN", "DAMAGED", "WRONG_ITEM", "WARRANTY", "NO_REFUND"] }, { name: "items", label: "Items JSON", type: "JSON", required: true, maximumLength: 4000, defaultValue: "[]" }], order: 20 },
            { id: "support-create-refund", label: "Create Refund", intent: "CREATE", permission: "order.refund.support.create", ownerModule: "order", operationRoute: "/operations/refunds", summary: "Create a scoped Refund intent; Order Workflow approves and Payment executes.", inputFields: [{ name: "entCode", label: "Enterprise", type: "HIDDEN", required: true, valueFromRecord: "enterpriseCode" }, { name: "orderCode", label: "Order", type: "HIDDEN", required: true, valueFromRecord: "code" }, { name: "reasonCode", label: "Reason", type: "SELECT", required: true, options: ["GOODWILL", "DAMAGED_IN_TRANSIT", "MISSING_ITEM", "SERVICE_CREDIT", "PRICE_CORRECTION", "CORRECTION"] }, { name: "items", label: "Items JSON", type: "JSON", required: true, maximumLength: 4000, defaultValue: "[]" }], order: 30 },
          ],
          detailPanels: [
            {
              id: "order-entries",
              label: "Order Entries",
              target: { moduleName: "order", schemaName: "orderEntry" },
              relation: {
                sourceField: "code",
                targetField: "orderCode",
                cardinality: "MANY",
              },
              summary:
                "Line-level product, quantity, price, tax, discount, and inventory evidence captured for this order.",
            },
            {
              id: "order-delivery-groups",
              label: "Order Delivery Groups",
              target: { moduleName: "order", schemaName: "orderDeliveryGroup" },
              relation: {
                sourceField: "code",
                targetField: "orderCode",
                cardinality: "MANY",
              },
              summary:
                "Delivery groups that split order-entry quantities across addresses, pickup points, digital delivery, or service destinations.",
            },
            {
              id: "order-delivery-allocations",
              label: "Order Delivery Allocations",
              target: {
                moduleName: "order",
                schemaName: "orderDeliveryAllocation",
              },
              relation: {
                sourceField: "code",
                targetField: "orderCode",
                cardinality: "MANY",
              },
              summary:
                "Quantity-level order-entry delivery allocations, including optional serial or inventory-unit evidence.",
            },
            {
              id: "order-payment-groups",
              label: "Order Payment Groups",
              target: { moduleName: "order", schemaName: "orderPaymentGroup" },
              relation: {
                sourceField: "code",
                targetField: "orderCode",
                cardinality: "MANY",
              },
              summary:
                "Payment groups that split order value across payment modes or payment authorities.",
            },
            {
              id: "order-payment-allocations",
              label: "Order Payment Allocations",
              target: {
                moduleName: "order",
                schemaName: "orderPaymentAllocation",
              },
              relation: {
                sourceField: "code",
                targetField: "orderCode",
                cardinality: "MANY",
              },
              summary:
                "Quantity and amount-level order-entry payment allocations.",
            },
            {
              id: "order-history",
              label: "Order History",
              target: { moduleName: "order", schemaName: "orderHistoryEntry" },
              relation: {
                sourceField: "code",
                targetField: "orderCode",
                cardinality: "MANY",
              },
              summary:
                "Lifecycle events, status changes, actors, reasons, and evidence recorded for this order.",
            },
          ],
          help: {
            summary:
              "Review persisted order records through the Order capability.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "checkout-placement-runs",
          parentId: "checkout",
          label: "Checkout Placement Runs",
          route: "/commerce/operations/checkout/placement-runs",
          icon: "workflow",
          order: 583,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["order.backoffice.read"],
          workbenchTarget: {
            moduleName: "order",
            schemaName: "checkoutPlacementRun",
          },
          help: {
            summary:
              "Review workflow-backed checkout placement runs that convert carts into orders through configured pipeline steps.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "checkout-reverse-runs",
          parentId: "checkout",
          label: "Checkout Reverse Runs",
          route: "/commerce/operations/checkout/reverse-runs",
          icon: "workflow",
          order: 584,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["order.backoffice.read"],
          workbenchTarget: {
            moduleName: "order",
            schemaName: "checkoutReverseRun",
          },
          workbenchPresentation: {
            defaultColumns: [
              "reverseCode",
              "orderCode",
              "state",
              "currentStep",
              "recoveryStrategy",
              "recoveryOwner",
              "returnCode",
              "refundTransactionCode",
            ],
            quickFilters: [
              {
                id: "active-recovery",
                label: "Active recovery",
                field: "state",
                value: "COMPENSATING",
                order: 10,
              },
              {
                id: "fulfillment-review",
                label: "Fulfillment review",
                field: "recoveryStrategy",
                value: "FULFILLMENT_REVIEW_REQUIRED",
                order: 20,
              },
              {
                id: "inventory-review",
                label: "Inventory review",
                field: "recoveryStrategy",
                value: "INVENTORY_REVIEW_REQUIRED",
                order: 30,
              },
              {
                id: "payment-retry",
                label: "Payment retry",
                field: "recoveryStrategy",
                value: "PAYMENT_RETRY_REQUIRED",
                order: 40,
              },
              {
                id: "history-retry",
                label: "History retry",
                field: "recoveryStrategy",
                value: "ORDER_HISTORY_RETRY_REQUIRED",
                order: 50,
              },
            ],
            recoveryActions: [
              {
                id: "review-fulfillment-return",
                label: "Review fulfillment return",
                ownerModule: "fulfillment",
                strategy: "FULFILLMENT_REVIEW_REQUIRED",
                handlerAction: "checkoutReverseRecoverFulfillmentAction",
                summary:
                  "Ask Fulfillment for safe return state and configured next actions. Order does not mutate return lifecycle.",
                order: 10,
              },
              {
                id: "review-inventory-disposition",
                label: "Review inventory disposition",
                ownerModule: "inventory",
                strategy: "INVENTORY_REVIEW_REQUIRED",
                handlerAction: "checkoutReverseRecoverInventoryAction",
                summary:
                  "Ask Inventory whether idempotent Stock Movement evidence exists or review/adjustment is required.",
                order: 20,
              },
              {
                id: "retry-payment-refund",
                label: "Retry payment refund",
                ownerModule: "payment",
                strategy: "PAYMENT_RETRY_REQUIRED",
                handlerAction: "checkoutReverseRecoverPaymentAction",
                summary:
                  "Ask Payment to retry or reconcile refund evidence using Payment-owned idempotency.",
                order: 30,
              },
              {
                id: "retry-order-history",
                label: "Retry order history",
                ownerModule: "order",
                strategy: "ORDER_HISTORY_RETRY_REQUIRED",
                handlerAction: "checkoutReverseRecoverHistoryAction",
                summary:
                  "Retry Order history evidence with the stable reverse history code.",
                order: 40,
              },
            ],
          },
          detailPanels: [
            {
              id: "reverse-run-order",
              label: "Order",
              target: { moduleName: "order", schemaName: "order" },
              relation: {
                sourceField: "orderCode",
                targetField: "code",
                cardinality: "ONE",
              },
              summary:
                "Order header linked to this return or refund workflow run.",
            },
            {
              id: "reverse-run-return",
              label: "Fulfillment Return",
              target: {
                moduleName: "fulfillment",
                schemaName: "fulfillmentReturnRequest",
              },
              relation: {
                sourceField: "returnCode",
                targetField: "returnCode",
                cardinality: "ONE",
              },
              summary:
                "Fulfillment-owned return request, receipt, inspection, and disposition evidence coordinated by this run.",
            },
            {
              id: "reverse-run-refund-transaction",
              label: "Payment Refund",
              target: {
                moduleName: "payment",
                schemaName: "paymentTransaction",
              },
              relation: {
                sourceField: "refundTransactionCode",
                targetField: "transactionCode",
                cardinality: "ONE",
              },
              summary:
                "Payment-owned refund transaction evidence coordinated by this run.",
            },
            {
              id: "reverse-run-history",
              label: "Order History",
              target: { moduleName: "order", schemaName: "orderHistoryEntry" },
              relation: {
                sourceField: "reverseCode",
                targetField: "evidenceCode",
                cardinality: "MANY",
              },
              summary:
                "Order-centered lifecycle history entries recorded against this reverse workflow run.",
            },
          ],
          help: {
            summary:
              "Review workflow-backed reverse checkout runs, owner evidence, and recovery strategies for returns and refunds.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "carts",
          parentId: "checkout",
          label: "Carts",
          route: "/commerce/operations/checkout/carts",
          icon: "cart",
          order: 581,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["cart.backoffice.read"],
          workbenchTarget: { moduleName: "cart", schemaName: "cart" },
          detailPanels: [
            {
              id: "cart-entries",
              label: "Cart Entries",
              target: { moduleName: "cart", schemaName: "cartEntry" },
              relation: {
                sourceField: "code",
                targetField: "cartCode",
                cardinality: "MANY",
              },
              summary:
                "Line-level product, quantity, and pricing evidence currently attached to this cart.",
            },
            {
              id: "cart-delivery-groups",
              label: "Cart Delivery Groups",
              target: { moduleName: "cart", schemaName: "cartDeliveryGroup" },
              relation: {
                sourceField: "code",
                targetField: "cartCode",
                cardinality: "MANY",
              },
              summary:
                "Delivery groups that split cart-entry quantities across addresses, pickup points, digital delivery, or service destinations.",
            },
            {
              id: "cart-delivery-allocations",
              label: "Cart Delivery Allocations",
              target: {
                moduleName: "cart",
                schemaName: "cartDeliveryAllocation",
              },
              relation: {
                sourceField: "code",
                targetField: "cartCode",
                cardinality: "MANY",
              },
              summary:
                "Quantity-level cart-entry delivery allocations, including optional serial or inventory-unit evidence.",
            },
            {
              id: "cart-payment-groups",
              label: "Cart Payment Groups",
              target: { moduleName: "cart", schemaName: "cartPaymentGroup" },
              relation: {
                sourceField: "code",
                targetField: "cartCode",
                cardinality: "MANY",
              },
              summary:
                "Payment groups that split cart value across payment modes before order placement.",
            },
            {
              id: "cart-payment-allocations",
              label: "Cart Payment Allocations",
              target: {
                moduleName: "cart",
                schemaName: "cartPaymentAllocation",
              },
              relation: {
                sourceField: "code",
                targetField: "cartCode",
                cardinality: "MANY",
              },
              summary:
                "Quantity and amount-level cart-entry payment allocations.",
            },
          ],
          help: {
            summary:
              "Review persisted cart records through the Cart capability while checkout journey grouping stays in Commerce Operations.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "cart-entries",
          parentId: "checkout",
          label: "Cart Entries",
          route: "/commerce/operations/checkout/cart-entries",
          icon: "cart",
          order: 582,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["cart.backoffice.read"],
          workbenchTarget: { moduleName: "cart", schemaName: "cartEntry" },
          workbenchPresentation: {
            defaultColumns: [
              "entryCode",
              "cartCode",
              "itemCode",
              "quantity",
              "unitCode",
              "currencyCode",
              "lineGrossAmount",
              "taxTotal",
              "taxInclusionMode",
              "status",
            ],
            readonlyFields: [
              "unitNetAmount",
              "unitGrossAmount",
              "lineNetAmount",
              "lineGrossAmount",
              "taxTotal",
              "taxInclusionMode",
              "taxIncluded",
              "taxQuoteCode",
              "taxQuoteLineCode",
              "taxJurisdictionCode",
              "taxCategoryCode",
              "taxRateCode",
            ],
            detailSections: [
              {
                id: "entry-identity",
                label: "Line identity",
                fields: [
                  "entryCode",
                  "cartCode",
                  "lineNumber",
                  "catalogCode",
                  "itemType",
                  "itemCode",
                  "quantity",
                  "unitCode",
                  "status",
                ],
                order: 10,
              },
              {
                id: "price-tax-display",
                label: "Price and tax display evidence",
                fields: [
                  "currencyCode",
                  "unitPrice",
                  "unitNetAmount",
                  "unitGrossAmount",
                  "totalPrice",
                  "lineNetAmount",
                  "lineGrossAmount",
                  "taxTotal",
                  "taxInclusionMode",
                  "taxIncluded",
                  "discountTotal",
                  "priceEvidenceCode",
                ],
                order: 20,
              },
              {
                id: "tax-authority-links",
                label: "Tax authority references",
                fields: [
                  "taxQuoteCode",
                  "taxQuoteLineCode",
                  "taxJurisdictionCode",
                  "taxCategoryCode",
                  "taxRateCode",
                ],
                order: 30,
              },
            ],
          },
          help: {
            summary:
              "Review cart line entries with product, quantity, unit, currency, line price, and tax display evidence.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
            documentationFragment: "tax-inclusive-display-evidence",
          },
        },
        {
          id: "order-entries",
          parentId: "checkout",
          label: "Order Entries",
          route: "/commerce/operations/checkout/order-entries",
          icon: "commerce",
          order: 583,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["order.backoffice.read"],
          workbenchTarget: { moduleName: "order", schemaName: "orderEntry" },
          workbenchPresentation: {
            defaultColumns: [
              "entryCode",
              "orderCode",
              "itemCode",
              "quantity",
              "unitCode",
              "currencyCode",
              "lineGrossAmount",
              "taxTotal",
              "taxInclusionMode",
              "status",
            ],
            readonlyFields: [
              "unitNetAmount",
              "unitGrossAmount",
              "lineNetAmount",
              "lineGrossAmount",
              "taxTotal",
              "taxInclusionMode",
              "taxIncluded",
              "taxQuoteCode",
              "taxQuoteLineCode",
              "taxJurisdictionCode",
              "taxCategoryCode",
              "taxRateCode",
              "priceEvidenceCode",
            ],
            detailSections: [
              {
                id: "entry-identity",
                label: "Line identity",
                fields: [
                  "entryCode",
                  "orderCode",
                  "cartCode",
                  "lineNumber",
                  "catalogCode",
                  "itemType",
                  "itemCode",
                  "quantity",
                  "unitCode",
                  "status",
                ],
                order: 10,
              },
              {
                id: "frozen-price-tax-evidence",
                label: "Frozen price and tax evidence",
                fields: [
                  "currencyCode",
                  "unitPrice",
                  "unitNetAmount",
                  "unitGrossAmount",
                  "totalPrice",
                  "lineNetAmount",
                  "lineGrossAmount",
                  "taxTotal",
                  "taxInclusionMode",
                  "taxIncluded",
                  "discountTotal",
                  "priceEvidenceCode",
                ],
                order: 20,
              },
              {
                id: "tax-authority-links",
                label: "Tax authority references",
                fields: [
                  "taxQuoteCode",
                  "taxQuoteLineCode",
                  "taxJurisdictionCode",
                  "taxCategoryCode",
                  "taxRateCode",
                ],
                order: 30,
              },
              {
                id: "inventory-links",
                label: "Inventory evidence",
                fields: ["allocationCode", "reservationCode"],
                order: 40,
              },
            ],
          },
          help: {
            summary:
              "Review immutable order line entries with product, quantity, pricing, tax, discount, and inventory evidence.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
            documentationFragment: "tax-inclusive-display-evidence",
          },
        },
        {
          id: "cart-delivery-groups",
          parentId: "checkout",
          label: "Cart Delivery Groups",
          route: "/commerce/operations/checkout/cart-delivery-groups",
          icon: "commerce",
          order: 584,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["cart.backoffice.read"],
          workbenchTarget: {
            moduleName: "cart",
            schemaName: "cartDeliveryGroup",
          },
          help: {
            summary:
              "Review cart delivery groups used to split entry quantities across delivery destinations.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "cart-delivery-allocations",
          parentId: "checkout",
          label: "Cart Delivery Allocations",
          route: "/commerce/operations/checkout/cart-delivery-allocations",
          icon: "commerce",
          order: 585,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["cart.backoffice.read"],
          workbenchTarget: {
            moduleName: "cart",
            schemaName: "cartDeliveryAllocation",
          },
          help: {
            summary:
              "Review quantity-level delivery allocations for cart entries, including optional serial evidence.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "cart-payment-groups",
          parentId: "checkout",
          label: "Cart Payment Groups",
          route: "/commerce/operations/checkout/cart-payment-groups",
          icon: "commerce",
          order: 586,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["cart.backoffice.read"],
          workbenchTarget: {
            moduleName: "cart",
            schemaName: "cartPaymentGroup",
          },
          help: {
            summary:
              "Review cart payment groups used to split payment responsibility before order placement.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "cart-payment-allocations",
          parentId: "checkout",
          label: "Cart Payment Allocations",
          route: "/commerce/operations/checkout/cart-payment-allocations",
          icon: "commerce",
          order: 587,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["cart.backoffice.read"],
          workbenchTarget: {
            moduleName: "cart",
            schemaName: "cartPaymentAllocation",
          },
          help: {
            summary:
              "Review cart payment allocations that assign exact amounts to allocated entry quantities.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "order-delivery-groups",
          parentId: "checkout",
          label: "Order Delivery Groups",
          route: "/commerce/operations/checkout/order-delivery-groups",
          icon: "commerce",
          order: 588,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["order.backoffice.read"],
          workbenchTarget: {
            moduleName: "order",
            schemaName: "orderDeliveryGroup",
          },
          help: {
            summary:
              "Review order delivery groups that become shipment or consignment inputs for fulfillment.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "order-delivery-allocations",
          parentId: "checkout",
          label: "Order Delivery Allocations",
          route: "/commerce/operations/checkout/order-delivery-allocations",
          icon: "commerce",
          order: 589,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["order.backoffice.read"],
          workbenchTarget: {
            moduleName: "order",
            schemaName: "orderDeliveryAllocation",
          },
          help: {
            summary:
              "Review quantity-level delivery allocations for order entries, including optional serial evidence.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "order-payment-groups",
          parentId: "checkout",
          label: "Order Payment Groups",
          route: "/commerce/operations/checkout/order-payment-groups",
          icon: "commerce",
          order: 590,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["order.backoffice.read"],
          workbenchTarget: {
            moduleName: "order",
            schemaName: "orderPaymentGroup",
          },
          help: {
            summary:
              "Review order payment groups that coordinate payment modes and transaction evidence.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "order-payment-allocations",
          parentId: "checkout",
          label: "Order Payment Allocations",
          route: "/commerce/operations/checkout/order-payment-allocations",
          icon: "commerce",
          order: 591,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["order.backoffice.read"],
          workbenchTarget: {
            moduleName: "order",
            schemaName: "orderPaymentAllocation",
          },
          help: {
            summary:
              "Review order payment allocations that assign exact payment amounts to allocated entry quantities.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "order-history",
          parentId: "checkout",
          label: "Order History",
          route: "/commerce/operations/checkout/order-history",
          icon: "audit",
          order: 592,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["order.backoffice.read"],
          workbenchTarget: {
            moduleName: "order",
            schemaName: "orderHistoryEntry",
          },
          help: {
            summary:
              "Review order lifecycle events, status changes, actors, reason codes, and operational evidence.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "order-statuses",
          parentId: "checkout",
          label: "Order Statuses",
          route: "/commerce/operations/checkout/order-statuses",
          icon: "commerce",
          order: 593,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["order.backoffice.read"],
          workbenchTarget: { moduleName: "order", schemaName: "orderstatus" },
          help: {
            summary:
              "Maintain order-status reference records and sequencing used by order lifecycle flows.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "payment-statuses",
          parentId: "checkout",
          label: "Payment Statuses",
          route: "/commerce/operations/checkout/payment-statuses",
          icon: "commerce",
          order: 594,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["order.backoffice.read"],
          workbenchTarget: { moduleName: "order", schemaName: "paymentstatus" },
          help: {
            summary:
              "Maintain payment-status reference records used by order payment lifecycle tracking.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "shipping-statuses",
          parentId: "checkout",
          label: "Shipping Statuses",
          route: "/commerce/operations/checkout/shipping-statuses",
          icon: "commerce",
          order: 595,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["order.backoffice.read"],
          workbenchTarget: {
            moduleName: "order",
            schemaName: "shippingstatus",
          },
          help: {
            summary:
              "Maintain shipping-status reference records used by fulfillment and shipping lifecycle tracking.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "order-cancellations",
          parentId: "checkout",
          label: "Order Cancellations",
          route: "/commerce/operations/checkout/cancellations",
          icon: "cancel",
          order: 596,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["order.cancellation.support.read"],
          workbenchTarget: { moduleName: "order", schemaName: "orderLifecycleRequest" },
          workbenchPresentation: { defaultColumns: ["requestCode", "orderCode", "customerCode", "requestType", "state", "reasonCode", "requesterType", "version"], forbiddenFields: ["rawGatewayPayload", "providerPayload", "carrierPayload", "secret", "password"], fixedFilters: [{ id: "cancellation-only", label: "Cancellation requests only", field: "requestType", value: "CANCELLATION", order: 0 }], quickFilters: [{ id: "active", label: "Active", field: "state", values: ["SUBMITTED", "APPROVAL_PENDING", "APPROVED", "EXECUTING", "RECONCILIATION_REQUIRED"], order: 20 }] },
          detailPanels: [{ id: "cancellation-items", label: "Requested quantities", target: { moduleName: "order", schemaName: "orderLifecycleRequestItem" }, relation: { sourceField: "requestCode", targetField: "requestCode", cardinality: "MANY" }, summary: "Immutable entry, quantity, serial, allocation, price, tax, and discount evidence.", order: 10 }, { id: "cancellation-history", label: "Audit history", target: { moduleName: "order", schemaName: "orderHistoryEntry" }, relation: { sourceField: "requestCode", targetField: "evidenceCode", cardinality: "MANY" }, summary: "Append-only cancellation decisions and execution checkpoints.", order: 20 }],
          help: { summary: "Review customer and support cancellation requests, decisions, owner execution, and reconciliation evidence.", documentationRoute: "/docs/capabilities/commerce/order-lifecycle", documentationFragment: "cancellation" },
        },
        {
          id: "shipments",
          parentId: "checkout",
          label: "Shipments",
          route: "/commerce/operations/checkout/shipments",
          icon: "commerce",
          order: 597,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "DISABLED",
          help: {
            summary:
              "Planned workspace for shipment records once the shipping backend model is introduced.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "returns",
          parentId: "checkout",
          label: "Returns",
          route: "/commerce/operations/checkout/returns",
          icon: "commerce",
          order: 598,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["order.return.support.read"],
          workbenchTarget: { moduleName: "order", schemaName: "orderLifecycleRequest" },
          workbenchPresentation: { defaultColumns: ["requestCode", "orderCode", "customerCode", "requestType", "state", "reasonCode", "requestedOutcome", "version"], forbiddenFields: ["rawGatewayPayload", "providerPayload", "carrierPayload", "secret", "password"], fixedFilters: [{ id: "return-only", label: "Return requests only", field: "requestType", value: "RETURN", order: 0 }], quickFilters: [{ id: "authorization", label: "Authorization queue", field: "state", values: ["SUBMITTED", "AUTHORIZATION_PENDING"], order: 20 }, { id: "authorized", label: "Authorized", field: "state", value: "AUTHORIZED", order: 30 }] },
          detailPanels: [{ id: "return-items", label: "Return items", target: { moduleName: "order", schemaName: "orderLifecycleRequestItem" }, relation: { sourceField: "requestCode", targetField: "requestCode", cardinality: "MANY" }, summary: "Immutable quantity and item policy evidence.", order: 10 }, { id: "return-history", label: "Audit history", target: { moduleName: "order", schemaName: "orderHistoryEntry" }, relation: { sourceField: "requestCode", targetField: "evidenceCode", cardinality: "MANY" }, summary: "Append-only authorization and RMA events.", order: 20 }],
          help: {
            summary:
              "Review Order-owned Return intent and authorization alongside Fulfillment-owned RMA and receipt workspaces.",
            documentationRoute: "/docs/capabilities/commerce/order-lifecycle",
            documentationFragment: "returns",
          },
        },
        {
          id: "order-refunds",
          parentId: "checkout",
          label: "Refund Requests",
          route: "/commerce/operations/checkout/refunds",
          icon: "payment",
          order: 599,
          group: { id: "commerce", label: "Commerce", order: 300 }, perspectives: ["operations", "commerce"], contexts: ["environment", "tenant", "enterprise"], featureState: "PREVIEW",
          requiredPermissions: ["order.refund.support.read"], workbenchTarget: { moduleName: "order", schemaName: "orderLifecycleRequest" },
          workbenchPresentation: { defaultColumns: ["requestCode", "orderCode", "customerCode", "requestType", "state", "reasonCode", "requesterType", "version"], forbiddenFields: ["rawGatewayPayload", "providerPayload", "cardNumber", "cvv", "pan", "secret"], fixedFilters: [{ id: "refund-only", label: "Refund requests only", field: "requestType", value: "REFUND", order: 0 }], quickFilters: [{ id: "approval", label: "Approval queue", field: "state", value: "APPROVAL_PENDING", order: 20 }, { id: "reconciliation", label: "Reconciliation", field: "state", value: "RECONCILIATION_REQUIRED", order: 30 }] },
          detailPanels: [{ id: "refund-items", label: "Refund items", target: { moduleName: "order", schemaName: "orderLifecycleRequestItem" }, relation: { sourceField: "requestCode", targetField: "requestCode", cardinality: "MANY" }, summary: "Immutable quantities and pricing references used by Payment calculation.", order: 10 }, { id: "refund-history", label: "Audit history", target: { moduleName: "order", schemaName: "orderHistoryEntry" }, relation: { sourceField: "requestCode", targetField: "evidenceCode", cardinality: "MANY" }, summary: "Append-only approval, provider execution, and reconciliation events.", order: 20 }],
          help: { summary: "Review Refund business intent and approval; Payment remains the provider-execution and reconciliation authority.", documentationRoute: "/docs/capabilities/commerce/order-lifecycle", documentationFragment: "refunds" },
        },
        {
          id: "order-lifecycle-support", parentId: "checkout", label: "Lifecycle Support", route: "/commerce/operations/checkout/lifecycle-support", icon: "support", order: 5991,
          group: { id: "commerce", label: "Commerce", order: 300 }, perspectives: ["operations", "commerce"], contexts: ["environment", "tenant", "enterprise"], featureState: "PREVIEW",
          requiredPermissions: ["order.backoffice.read"], workbenchTarget: { moduleName: "order", schemaName: "order" },
          workbenchPresentation: { defaultColumns: ["code", "customerCode", "siteCode", "channelCode", "status", "createdAt"], quickFilters: [{ id: "active-orders", label: "Active orders", field: "status", values: ["PLACED", "PROCESSING"], order: 10 }] },
          lifecycleActions: [
            { id: "support-create-cancellation", label: "Create cancellation", intent: "CREATE", permission: "order.cancellation.support.create", ownerModule: "order", operationRoute: "/operations/cancellations", inputFields: [{ name: "entCode", label: "Enterprise", type: "HIDDEN", required: true, valueFromRecord: "enterpriseCode" }, { name: "orderCode", label: "Order", type: "HIDDEN", required: true, valueFromRecord: "code" }, { name: "reasonCode", label: "Reason", type: "SELECT", required: true, options: ["CUSTOMER_REQUEST", "SUPPORT_CORRECTION"] }, { name: "items", label: "Items JSON", type: "JSON", required: true, maximumLength: 4000, defaultValue: "[]" }], order: 10 },
            { id: "support-create-return", label: "Create Return", intent: "CREATE", permission: "order.return.support.create", ownerModule: "order", operationRoute: "/operations/returns", inputFields: [{ name: "entCode", label: "Enterprise", type: "HIDDEN", required: true, valueFromRecord: "enterpriseCode" }, { name: "orderCode", label: "Order", type: "HIDDEN", required: true, valueFromRecord: "code" }, { name: "reasonCode", label: "Reason", type: "SELECT", required: true, options: ["CUSTOMER_RETURN", "DAMAGED", "WRONG_ITEM", "WARRANTY", "NO_REFUND"] }, { name: "items", label: "Items JSON", type: "JSON", required: true, maximumLength: 4000, defaultValue: "[]" }], order: 20 },
            { id: "support-create-refund", label: "Create Refund", intent: "CREATE", permission: "order.refund.support.create", ownerModule: "order", operationRoute: "/operations/refunds", inputFields: [{ name: "entCode", label: "Enterprise", type: "HIDDEN", required: true, valueFromRecord: "enterpriseCode" }, { name: "orderCode", label: "Order", type: "HIDDEN", required: true, valueFromRecord: "code" }, { name: "reasonCode", label: "Reason", type: "SELECT", required: true, options: ["GOODWILL", "DAMAGED_IN_TRANSIT", "MISSING_ITEM", "SERVICE_CREDIT", "PRICE_CORRECTION", "CORRECTION"] }, { name: "items", label: "Items JSON", type: "JSON", required: true, maximumLength: 4000, defaultValue: "[]" }], order: 30 },
          ],
          detailPanels: [
            { id: "support-order-history", label: "Order history", target: { moduleName: "order", schemaName: "orderHistoryEntry" }, relation: { sourceField: "code", targetField: "orderCode", cardinality: "MANY" }, summary: "Authorized Order and lifecycle audit history.", order: 10 },
            { id: "support-lifecycle-requests", label: "Cancellation, Return, and Refund history", target: { moduleName: "order", schemaName: "orderLifecycleRequest" }, relation: { sourceField: "code", targetField: "orderCode", cardinality: "MANY" }, summary: "Cancellation, Return, and Refund business requests for this Order.", order: 20 },
            { id: "support-payment-history", label: "Payment history", target: { moduleName: "payment", schemaName: "paymentTransaction" }, relation: { sourceField: "code", targetField: "orderCode", cardinality: "MANY" }, summary: "Permission-filtered Payment authorization, capture, void, Refund, retry, and reconciliation evidence.", order: 30 },
            { id: "support-shipment-history", label: "Shipment history", target: { moduleName: "fulfillment", schemaName: "fulfillmentShipment" }, relation: { sourceField: "code", targetField: "orderCode", cardinality: "MANY" }, summary: "Permission-filtered consignment, shipment, Return receipt, and warehouse outcome evidence.", order: 40 },
          ],
          help: { summary: "Search scoped Orders, inspect lifecycle context, and create support lifecycle intents through one backend operation.", documentationRoute: "/docs/capabilities/commerce/order-lifecycle", documentationFragment: "support" },
        },
        {
          id: "order-lifecycle-approvals", parentId: "checkout", label: "Lifecycle Approvals", route: "/commerce/operations/checkout/lifecycle-approvals", icon: "workflow", order: 5992,
          group: { id: "commerce", label: "Commerce", order: 300 }, perspectives: ["operations", "commerce"], contexts: ["environment", "tenant", "enterprise"], featureState: "PREVIEW",
          requiredPermissions: ["order.lifecycle.approval.read"], workbenchTarget: { moduleName: "order", schemaName: "orderLifecycleRequest" },
          workbenchPresentation: { defaultColumns: ["requestCode", "requestType", "orderCode", "customerCode", "state", "reasonCode", "workflowCarrierCode", "version"], fixedFilters: [{ id: "approval-state", label: "Awaiting decision", field: "state", values: ["APPROVAL_PENDING", "AUTHORIZATION_PENDING", "ESCALATED"], order: 0 }], readonlyFields: ["evidence"] },
          lifecycleActions: [
            { id: "approve-lifecycle", label: "Approve", intent: "APPROVE", permission: "workflow.action.perform", ownerModule: "workflow", operationRoute: "/action/process/:workflowCarrierCode", targetStatuses: ["APPROVAL_PENDING", "AUTHORIZATION_PENDING", "ESCALATED"], inputFields: [{ name: "decision", label: "Decision", type: "HIDDEN", required: true, defaultValue: "SUCCESS" }, { name: "feedback", label: "Decision evidence", type: "MULTILINE", required: true, maximumLength: 2000 }], order: 10 },
            { id: "reject-lifecycle", label: "Reject", intent: "REJECT", permission: "workflow.action.perform", ownerModule: "workflow", operationRoute: "/action/process/:workflowCarrierCode", targetStatuses: ["APPROVAL_PENDING", "AUTHORIZATION_PENDING", "ESCALATED"], inputFields: [{ name: "decision", label: "Decision", type: "HIDDEN", required: true, defaultValue: "REJECT" }, { name: "feedback", label: "Rejection evidence", type: "MULTILINE", required: true, maximumLength: 2000 }], order: 20 },
            { id: "request-lifecycle-information", label: "Request information", intent: "OTHER", permission: "workflow.action.perform", ownerModule: "workflow", operationRoute: "/action/process/:workflowCarrierCode", targetStatuses: ["APPROVAL_PENDING", "AUTHORIZATION_PENDING"], inputFields: [{ name: "decision", label: "Decision", type: "HIDDEN", required: true, defaultValue: "REQUEST_INFORMATION" }, { name: "feedback", label: "Information required", type: "MULTILINE", required: true, maximumLength: 2000 }], order: 30 },
            { id: "escalate-lifecycle", label: "Escalate", intent: "OTHER", permission: "workflow.action.perform", ownerModule: "workflow", operationRoute: "/action/process/:workflowCarrierCode", targetStatuses: ["APPROVAL_PENDING", "AUTHORIZATION_PENDING"], inputFields: [{ name: "decision", label: "Decision", type: "HIDDEN", required: true, defaultValue: "ESCALATE" }, { name: "feedback", label: "Escalation reason", type: "MULTILINE", required: true, maximumLength: 500 }], order: 40 },
          ],
          detailPanels: [{ id: "approval-items", label: "Requested items", target: { moduleName: "order", schemaName: "orderLifecycleRequestItem" }, relation: { sourceField: "requestCode", targetField: "requestCode", cardinality: "MANY" }, summary: "Immutable quantities, serials, and commercial evidence.", order: 10 }, { id: "approval-audit", label: "Audit history", target: { moduleName: "order", schemaName: "orderHistoryEntry" }, relation: { sourceField: "requestCode", targetField: "evidenceCode", cardinality: "MANY" }, summary: "Policy explanation, decisions, and owner checkpoints.", order: 20 }],
          help: { summary: "Task-focused approval queue with bounded evidence and Workflow-owned decisions.", documentationRoute: "/docs/capabilities/commerce/order-lifecycle", documentationFragment: "approvals" },
        },
        {
          id: "order-lifecycle-exceptions", parentId: "checkout", label: "Lifecycle Exceptions", route: "/commerce/operations/checkout/lifecycle-exceptions", icon: "warning", order: 5993,
          group: { id: "commerce", label: "Commerce", order: 300 }, perspectives: ["operations", "commerce"], contexts: ["environment", "tenant", "enterprise"], featureState: "PREVIEW",
          requiredPermissions: ["order.lifecycle.operations.diagnostics"], workbenchTarget: { moduleName: "order", schemaName: "orderLifecycleRequest" },
          workbenchPresentation: { defaultColumns: ["requestCode", "requestType", "orderCode", "state", "reasonCode", "workflowCarrierCode", "updatedAt"], fixedFilters: [{ id: "exception-state", label: "Exceptions", field: "state", values: ["RECONCILIATION_REQUIRED", "SUBMISSION_FAILED", "ESCALATED"], order: 0 }] },
          detailPanels: [{ id: "exception-audit", label: "Audit and recovery evidence", target: { moduleName: "order", schemaName: "orderHistoryEntry" }, relation: { sourceField: "requestCode", targetField: "evidenceCode", cardinality: "MANY" }, summary: "Safe owner failure, retry, reconciliation, and manual action evidence.", order: 10 }],
          help: { summary: "Cross-owner exception queue; recovery actions remain in Payment, Fulfillment, Inventory, and Workflow workspaces.", documentationRoute: "/docs/capabilities/commerce/order-lifecycle", documentationFragment: "operations" },
        },
        {
          id: "order-lifecycle-policies", parentId: "checkout", label: "Lifecycle Policies", route: "/commerce/operations/checkout/lifecycle-policies", icon: "settings", order: 5994,
          group: { id: "commerce", label: "Commerce", order: 300 }, perspectives: ["operations", "commerce"], contexts: ["environment", "tenant", "enterprise"], featureState: "PREVIEW", requiredPermissions: ["order.lifecycle.policy.read"],
          workbenchTarget: { moduleName: "order", schemaName: "orderLifecyclePolicyRule" }, workbenchPresentation: { defaultColumns: ["policyCode", "policyType", "status", "version", "effectiveFrom", "effectiveTo"], readonlyFields: ["entCode", "policyCode", "policyType", "status", "version", "approvalEvidence"] },
          lifecycleActions: [
            { id: "update-lifecycle-policy", label: "Update draft", intent: "UPDATE", permission: "order.lifecycle.policy.manage", ownerModule: "order", operationRoute: "/operations/lifecycle/policies", targetStatuses: ["DRAFT", "ACTIVE", "SUSPENDED"], inputFields: [{ name: "entCode", label: "Enterprise", type: "HIDDEN", required: true, valueFromRecord: "entCode" }, { name: "policyCode", label: "Policy", type: "HIDDEN", required: true, valueFromRecord: "policyCode" }, { name: "expectedVersion", label: "Version", type: "HIDDEN", required: true, valueFromRecord: "version" }, { name: "action", label: "Action", type: "HIDDEN", required: true, defaultValue: "UPDATE" }, { name: "scope", label: "Scope JSON", type: "JSON", required: false, maximumLength: 4000, defaultValue: "{}" }, { name: "rule", label: "Rule JSON", type: "JSON", required: true, maximumLength: 4000, defaultValue: "{}" }], order: 10 },
            { id: "activate-lifecycle-policy", label: "Activate", intent: "ACTIVATE", permission: "order.lifecycle.policy.manage", ownerModule: "order", operationRoute: "/operations/lifecycle/policies", targetStatuses: ["DRAFT", "SUSPENDED"], inputFields: [{ name: "entCode", label: "Enterprise", type: "HIDDEN", required: true, valueFromRecord: "entCode" }, { name: "policyCode", label: "Policy", type: "HIDDEN", required: true, valueFromRecord: "policyCode" }, { name: "expectedVersion", label: "Version", type: "HIDDEN", required: true, valueFromRecord: "version" }, { name: "action", label: "Action", type: "HIDDEN", required: true, defaultValue: "ACTIVATE" }, { name: "reasonCode", label: "Approval reason", type: "TEXT", required: true, maximumLength: 100 }], order: 20 },
            { id: "suspend-lifecycle-policy", label: "Suspend", intent: "OTHER", permission: "order.lifecycle.policy.manage", ownerModule: "order", operationRoute: "/operations/lifecycle/policies", targetStatuses: ["ACTIVE"], inputFields: [{ name: "entCode", label: "Enterprise", type: "HIDDEN", required: true, valueFromRecord: "entCode" }, { name: "policyCode", label: "Policy", type: "HIDDEN", required: true, valueFromRecord: "policyCode" }, { name: "expectedVersion", label: "Version", type: "HIDDEN", required: true, valueFromRecord: "version" }, { name: "action", label: "Action", type: "HIDDEN", required: true, defaultValue: "SUSPEND" }, { name: "reasonCode", label: "Suspension reason", type: "TEXT", required: true, maximumLength: 100 }], order: 30 },
          ], help: { summary: "Configure scoped windows, Refund thresholds, auto-approval, evidence, timers, exceptions, and role routing through optimistic maker-checker operations.", documentationRoute: "/docs/capabilities/commerce/order-lifecycle", documentationFragment: "policy" },
        },
        {
          id: "order-lifecycle-reasons", parentId: "checkout", label: "Lifecycle Reasons", route: "/commerce/operations/checkout/lifecycle-reasons", icon: "settings", order: 5995,
          group: { id: "commerce", label: "Commerce", order: 300 }, perspectives: ["operations", "commerce"], contexts: ["environment", "tenant", "enterprise"], featureState: "PREVIEW", requiredPermissions: ["order.lifecycle.reason.read"],
          workbenchTarget: { moduleName: "order", schemaName: "orderLifecycleReason" }, workbenchPresentation: { defaultColumns: ["reasonCode", "label", "requestTypes", "status", "version"], readonlyFields: ["entCode", "reasonCode", "status", "version", "approvalEvidence"] },
          lifecycleActions: [
            { id: "update-lifecycle-reason", label: "Update draft", intent: "UPDATE", permission: "order.lifecycle.reason.manage", ownerModule: "order", operationRoute: "/operations/lifecycle/reasons", targetStatuses: ["DRAFT", "ACTIVE", "SUSPENDED"], inputFields: [{ name: "entCode", label: "Enterprise", type: "HIDDEN", required: true, valueFromRecord: "entCode" }, { name: "reasonCode", label: "Reason", type: "HIDDEN", required: true, valueFromRecord: "reasonCode" }, { name: "expectedVersion", label: "Version", type: "HIDDEN", required: true, valueFromRecord: "version" }, { name: "action", label: "Action", type: "HIDDEN", required: true, defaultValue: "UPDATE" }, { name: "label", label: "Label", type: "TEXT", required: true, valueFromRecord: "label" }, { name: "requestTypes", label: "Request types JSON", type: "JSON", required: true, maximumLength: 1000, defaultValue: "[]" }, { name: "requiredEvidence", label: "Required evidence JSON", type: "JSON", required: false, maximumLength: 1000, defaultValue: "[]" }], order: 10 },
            { id: "activate-lifecycle-reason", label: "Activate", intent: "ACTIVATE", permission: "order.lifecycle.reason.manage", ownerModule: "order", operationRoute: "/operations/lifecycle/reasons", targetStatuses: ["DRAFT", "SUSPENDED"], inputFields: [{ name: "entCode", label: "Enterprise", type: "HIDDEN", required: true, valueFromRecord: "entCode" }, { name: "reasonCode", label: "Reason", type: "HIDDEN", required: true, valueFromRecord: "reasonCode" }, { name: "expectedVersion", label: "Version", type: "HIDDEN", required: true, valueFromRecord: "version" }, { name: "action", label: "Action", type: "HIDDEN", required: true, defaultValue: "ACTIVATE" }, { name: "approvalReasonCode", label: "Approval reason", type: "TEXT", required: true, maximumLength: 100 }], order: 20 },
          ], help: { summary: "Manage reason labels, request applicability, requested outcomes, and evidence requirements through backend governance.", documentationRoute: "/docs/capabilities/commerce/order-lifecycle", documentationFragment: "reasons" },
        },
        {
          id: "consignments",
          parentId: "checkout",
          label: "Consignments",
          route: "/commerce/operations/checkout/consignments",
          icon: "commerce",
          order: 600,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "DISABLED",
          help: {
            summary:
              "Planned workspace for consignment and fulfillment split records once the backend model is introduced.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "delivery-modes",
          parentId: "checkout",
          label: "Delivery Modes",
          route: "/commerce/operations/checkout/delivery-modes",
          icon: "commerce",
          order: 601,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "DISABLED",
          help: {
            summary:
              "Planned workspace for delivery-mode records once the backend model is introduced.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "tax-records",
          parentId: "checkout",
          label: "Tax Records",
          route: "/commerce/operations/checkout/tax-records",
          icon: "commerce",
          order: 603,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "DISABLED",
          help: {
            summary:
              "Planned workspace for tax calculation evidence once the backend model is introduced.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "fraud-checks",
          parentId: "checkout",
          label: "Fraud Checks",
          route: "/commerce/operations/checkout/fraud-checks",
          icon: "commerce",
          order: 604,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "DISABLED",
          help: {
            summary:
              "Planned workspace for fraud-check evidence once the backend model is introduced.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
      ],
    },
  },
};
