/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */

/**
 * @module order/config/properties
 * @description Reserved order property contribution for module-level configuration defaults.
 * @layer config
 * @owner order
 * @override Project modules may provide later property contributions for order lifecycle, validation, and integration settings.
 */
module.exports = {
  order: {
    checkoutEntry: {
      policy: {
        statuses: ["ORDERED", "ALLOCATED", "CANCELLED", "RETURNED"],
        immutableFields: [
          "code",
          "entCode",
          "entryCode",
          "orderCode",
          "cartCode",
          "catalogCode",
          "itemType",
          "itemCode",
          "quantity",
          "unitCode",
          "currencyCode",
          "unitPrice",
          "totalPrice",
          "taxTotal",
          "discountTotal",
          "priceEvidenceCode",
        ],
        allowedTransitions: {
          ORDERED: ["ALLOCATED", "CANCELLED"],
          ALLOCATED: ["CANCELLED", "RETURNED"],
          CANCELLED: [],
          RETURNED: [],
        },
        conversion: {
          sourceParentField: "cartCode",
          targetParentField: "orderCode",
          targetStatus: "ORDERED",
          copiedFields: [
            "entCode",
            "entryCode",
            "lineNumber",
            "catalogCode",
            "itemType",
            "itemCode",
            "quantity",
            "unitCode",
            "currencyCode",
            "unitPrice",
            "totalPrice",
            "taxTotal",
            "discountTotal",
            "priceEvidenceCode",
          ],
        },
      },
    },
    checkoutAllocation: {
      policy: {
        quantityPattern: "^(0|[1-9][0-9]*)(\\.[0-9]+)?$",
        moneyPattern: "^(0|[1-9][0-9]*)(\\.[0-9]+)?$",
        maximumDigits: 38,
        maximumScale: 18,
        deliveryGroupTypes: ["ADDRESS", "PICKUP", "DIGITAL", "SERVICE"],
        deliveryGroupStatuses: [
          "ORDERED",
          "ALLOCATED",
          "RELEASED",
          "SHIPPED",
          "CANCELLED",
          "RETURNED",
        ],
        paymentGroupStatuses: [
          "ORDERED",
          "AUTHORIZED",
          "CAPTURED",
          "PARTIALLY_REFUNDED",
          "REFUNDED",
          "CANCELLED",
        ],
        allocationStatuses: [
          "ORDERED",
          "RESERVED",
          "ALLOCATED",
          "RELEASED",
          "SHIPPED",
          "CANCELLED",
          "RETURNED",
        ],
        conversion: {
          sourceParentField: "cartCode",
          targetParentField: "orderCode",
          targetStatus: "ORDERED",
          deliveryGroupCopiedFields: [
            "entCode",
            "deliveryGroupCode",
            "groupType",
            "addressCode",
            "deliveryModeCode",
            "carrierCode",
            "deliveryChargeQuoteCode",
            "deliveryChargeAmount",
            "deliveryChargeCurrencyCode",
            "deliveryChargeTaxMode",
          ],
          paymentGroupCopiedFields: [
            "entCode",
            "paymentGroupCode",
            "paymentModeCode",
            "currencyCode",
            "plannedAmount",
            "authorizedAmount",
            "capturedAmount",
            "refundedAmount",
            "paymentEvidenceCode",
          ],
          deliveryAllocationCopiedFields: [
            "entCode",
            "allocationCode",
            "entryCode",
            "deliveryGroupCode",
            "quantity",
            "unitCode",
            "serialNumbers",
            "inventoryReservationCode",
            "inventoryAllocationCode",
          ],
          paymentAllocationCopiedFields: [
            "entCode",
            "allocationCode",
            "entryCode",
            "paymentGroupCode",
            "quantity",
            "unitCode",
            "serialNumbers",
            "inventoryReservationCode",
            "inventoryAllocationCode",
            "amount",
            "currencyCode",
          ],
        },
      },
    },
    checkoutPlacement: {
      enabled: true,
      workflow: {
        enabled: true,
        manualWorkflowCode: "checkoutPlacementManualFlow",
        automaticWorkflowCode: "checkoutPlacementAutomaticFlow",
        defaultMode: "AUTOMATIC",
        modes: ["MANUAL", "AUTOMATIC"],
      },
      pipeline: {
        name: "checkoutPlacementRunPipeline",
        states: ["INIT", "RUNNING", "COMPLETED", "FAILED"],
        steps: ["validateRequest", "startPlacementRun", "finalizePlacementRun"],
      },
      validation: {
        allowedCartStatuses: ["ACTIVE", "READY_FOR_CHECKOUT", "CHECKOUT_READY"],
        maximumAggregateRecords: 1000,
      },
      inventoryReservation: {
        enabled: true,
        allocationSource: "delivery",
        demandType: "CART",
        promiseCodeFields: ["promiseCode", "inventoryPromiseCode"],
        defaultReasonCode: "CHECKOUT_PLACEMENT",
        maximumAggregateRecords: 1000,
      },
      orderProjection: {
        enabled: true,
        orderCodePrefix: "order",
        refCodePrefix: "checkout",
        orderStatus: "PLACED",
        entryStatus: "ORDERED",
        maximumAggregateRecords: 1000,
      },
      allocationCopy: {
        enabled: true,
        targetStatus: "ORDERED",
        maximumAggregateRecords: 1000,
      },
      paymentAuthorization: {
        enabled: true,
        ownerModule: "payment",
        maximumAggregateRecords: 1000,
      },
      fulfillmentRelease: {
        enabled: true,
        ownerModule: "fulfillment",
        maximumAggregateRecords: 1000,
      },
      compensation: {
        enabled: true,
        releaseInventoryReservations: true,
        cancelFulfillmentReleases: true,
        inventoryReleaseState: "RELEASED",
        inventoryReleaseReasonCode: "CHECKOUT_PLACEMENT_FAILED",
        recordOrderHistory: true,
        failedOrderStatus: "PLACEMENT_FAILED",
        failureMessageLimit: 240,
      },
    },
    checkoutReverse: {
      enabled: true,
      workflow: {
        enabled: true,
        manualWorkflowCode: "checkoutReverseManualFlow",
        automaticWorkflowCode: "checkoutReverseAutomaticFlow",
        defaultMode: "MANUAL",
        modes: ["MANUAL", "AUTOMATIC"],
      },
      states: [
        "INIT",
        "RUNNING",
        "RETURN_REQUESTED",
        "RETURN_APPROVED",
        "RETURN_RECEIVED",
        "RETURN_DISPOSED",
        "INVENTORY_DISPOSITION_APPLIED",
        "REFUND_CALCULATED",
        "REFUNDED",
        "COMPLETED",
        "FAILED",
        "COMPENSATING",
      ],
      returnRequest: {
        enabled: true,
        ownerModule: "fulfillment",
        recoveryService: "DefaultReturnRequestService",
        defaultReturnType: "CUSTOMER_RETURN",
        defaultReturnReasonCode: "CUSTOMER_RETURN",
        defaultDispositionCode: "INSPECT",
      },
      inventoryDisposition: {
        enabled: true,
        ownerModule: "inventory",
        service: "DefaultReturnDispositionMovementService",
        recoveryService: "DefaultReturnDispositionMovementService",
        executeBeforeRefundCalculation: true,
      },
      paymentRefund: {
        enabled: true,
        ownerModule: "payment",
        requireReceivedReturnBeforeRefund: true,
        calculateBeforeRefund: true,
        allocationSourceService: "DefaultOrderPaymentAllocationService",
        recoveryService: "DefaultPaymentRefundService",
        maximumAggregateRecords: 1000,
      },
      history: {
        enabled: true,
        eventType: "ORDER_REVERSE_FLOW",
        completedStatus: "RETURN_REFUNDED",
      },
      compensation: {
        enabled: true,
        state: "COMPENSATING",
        failureCode: "CHECKOUT_REVERSE_FAILED",
        failureMessageLimit: 240,
        recoveryStrategies: {
          RUNNING: "ORDER_RETRY_REQUIRED",
          RETURN_REQUESTED: "FULFILLMENT_REVIEW_REQUIRED",
          RETURN_APPROVED: "FULFILLMENT_REVIEW_REQUIRED",
          RETURN_RECEIVED: "FULFILLMENT_REVIEW_REQUIRED",
          RETURN_DISPOSED: "INVENTORY_REVIEW_REQUIRED",
          INVENTORY_DISPOSITION_APPLIED: "PAYMENT_RETRY_REQUIRED",
          REFUND_CALCULATED: "PAYMENT_RETRY_REQUIRED",
          REFUNDED: "ORDER_HISTORY_RETRY_REQUIRED",
          COMPLETED: "NO_COMPENSATION_REQUIRED",
        },
        ownerActions: {
          fulfillment: ["REVIEW_RETURN", "CLOSE_OR_CANCEL_RETURN"],
          inventory: [
            "REVIEW_DISPOSITION_MOVEMENT",
            "ADJUST_THROUGH_STOCK_MOVEMENT",
          ],
          payment: ["RETRY_REFUND", "RECONCILE_PROVIDER_REFUND"],
          order: ["RETRY_HISTORY", "MARK_RECOVERY_COMPLETE"],
        },
      },
      failureMessageLimit: 240,
    },
  },
  backofficeCapabilities: {
    order: {
      enabled: true,
      capabilityId: "order-management",
      displayName: "Orders",
      category: "commerce",
      icon: "commerce",
      contractVersion: 1,
      minimumClientContractVersion: 1,
      roles: ["FUNCTIONAL_CAPABILITY_PROVIDER"],
      discovery: {
        openApiPath: "/nodics/system/v0/contract/openapi/internal",
        contractVersion: 1,
      },
      navigation: [
        {
          id: "checkout",
          parentId: "commerce-operations",
          parentModuleName: "pricing",
          label: "Checkout",
          route: "/commerce/operations/checkout",
          icon: "commerce",
          order: 580,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["order.backoffice.read"],
          workbenchTarget: { moduleName: "order", schemaName: "order" },
          help: {
            summary:
              "Review checkout journey records such as orders, order statuses, payment statuses, and shipping statuses.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "orders",
          parentId: "checkout",
          label: "Orders",
          route: "/commerce/operations/checkout/orders",
          icon: "commerce",
          order: 582,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["order.backoffice.read"],
          workbenchTarget: { moduleName: "order", schemaName: "order" },
          detailPanels: [
            {
              id: "order-entries",
              label: "Order Entries",
              target: { moduleName: "order", schemaName: "orderEntry" },
              relation: {
                sourceField: "code",
                targetField: "orderCode",
                cardinality: "MANY",
              },
              summary:
                "Line-level product, quantity, price, tax, discount, and inventory evidence captured for this order.",
            },
            {
              id: "order-delivery-groups",
              label: "Order Delivery Groups",
              target: { moduleName: "order", schemaName: "orderDeliveryGroup" },
              relation: {
                sourceField: "code",
                targetField: "orderCode",
                cardinality: "MANY",
              },
              summary:
                "Delivery groups that split order-entry quantities across addresses, pickup points, digital delivery, or service destinations.",
            },
            {
              id: "order-delivery-allocations",
              label: "Order Delivery Allocations",
              target: {
                moduleName: "order",
                schemaName: "orderDeliveryAllocation",
              },
              relation: {
                sourceField: "code",
                targetField: "orderCode",
                cardinality: "MANY",
              },
              summary:
                "Quantity-level order-entry delivery allocations, including optional serial or inventory-unit evidence.",
            },
            {
              id: "order-payment-groups",
              label: "Order Payment Groups",
              target: { moduleName: "order", schemaName: "orderPaymentGroup" },
              relation: {
                sourceField: "code",
                targetField: "orderCode",
                cardinality: "MANY",
              },
              summary:
                "Payment groups that split order value across payment modes or payment authorities.",
            },
            {
              id: "order-payment-allocations",
              label: "Order Payment Allocations",
              target: {
                moduleName: "order",
                schemaName: "orderPaymentAllocation",
              },
              relation: {
                sourceField: "code",
                targetField: "orderCode",
                cardinality: "MANY",
              },
              summary:
                "Quantity and amount-level order-entry payment allocations.",
            },
            {
              id: "order-history",
              label: "Order History",
              target: { moduleName: "order", schemaName: "orderHistoryEntry" },
              relation: {
                sourceField: "code",
                targetField: "orderCode",
                cardinality: "MANY",
              },
              summary:
                "Lifecycle events, status changes, actors, reasons, and evidence recorded for this order.",
            },
          ],
          help: {
            summary:
              "Review persisted order records through the Order capability.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "checkout-placement-runs",
          parentId: "checkout",
          label: "Checkout Placement Runs",
          route: "/commerce/operations/checkout/placement-runs",
          icon: "workflow",
          order: 583,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["order.backoffice.read"],
          workbenchTarget: {
            moduleName: "order",
            schemaName: "checkoutPlacementRun",
          },
          help: {
            summary:
              "Review workflow-backed checkout placement runs that convert carts into orders through configured pipeline steps.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "checkout-reverse-runs",
          parentId: "checkout",
          label: "Checkout Reverse Runs",
          route: "/commerce/operations/checkout/reverse-runs",
          icon: "workflow",
          order: 584,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["order.backoffice.read"],
          workbenchTarget: {
            moduleName: "order",
            schemaName: "checkoutReverseRun",
          },
          workbenchPresentation: {
            defaultColumns: [
              "reverseCode",
              "orderCode",
              "state",
              "currentStep",
              "recoveryStrategy",
              "recoveryOwner",
              "returnCode",
              "refundTransactionCode",
            ],
            quickFilters: [
              {
                id: "active-recovery",
                label: "Active recovery",
                field: "state",
                value: "COMPENSATING",
                order: 10,
              },
              {
                id: "fulfillment-review",
                label: "Fulfillment review",
                field: "recoveryStrategy",
                value: "FULFILLMENT_REVIEW_REQUIRED",
                order: 20,
              },
              {
                id: "inventory-review",
                label: "Inventory review",
                field: "recoveryStrategy",
                value: "INVENTORY_REVIEW_REQUIRED",
                order: 30,
              },
              {
                id: "payment-retry",
                label: "Payment retry",
                field: "recoveryStrategy",
                value: "PAYMENT_RETRY_REQUIRED",
                order: 40,
              },
              {
                id: "history-retry",
                label: "History retry",
                field: "recoveryStrategy",
                value: "ORDER_HISTORY_RETRY_REQUIRED",
                order: 50,
              },
            ],
            recoveryActions: [
              {
                id: "review-fulfillment-return",
                label: "Review fulfillment return",
                ownerModule: "fulfillment",
                strategy: "FULFILLMENT_REVIEW_REQUIRED",
                handlerAction: "checkoutReverseRecoverFulfillmentAction",
                summary:
                  "Ask Fulfillment for safe return state and configured next actions. Order does not mutate return lifecycle.",
                order: 10,
              },
              {
                id: "review-inventory-disposition",
                label: "Review inventory disposition",
                ownerModule: "inventory",
                strategy: "INVENTORY_REVIEW_REQUIRED",
                handlerAction: "checkoutReverseRecoverInventoryAction",
                summary:
                  "Ask Inventory whether idempotent Stock Movement evidence exists or review/adjustment is required.",
                order: 20,
              },
              {
                id: "retry-payment-refund",
                label: "Retry payment refund",
                ownerModule: "payment",
                strategy: "PAYMENT_RETRY_REQUIRED",
                handlerAction: "checkoutReverseRecoverPaymentAction",
                summary:
                  "Ask Payment to retry or reconcile refund evidence using Payment-owned idempotency.",
                order: 30,
              },
              {
                id: "retry-order-history",
                label: "Retry order history",
                ownerModule: "order",
                strategy: "ORDER_HISTORY_RETRY_REQUIRED",
                handlerAction: "checkoutReverseRecoverHistoryAction",
                summary:
                  "Retry Order history evidence with the stable reverse history code.",
                order: 40,
              },
            ],
          },
          detailPanels: [
            {
              id: "reverse-run-order",
              label: "Order",
              target: { moduleName: "order", schemaName: "order" },
              relation: {
                sourceField: "orderCode",
                targetField: "code",
                cardinality: "ONE",
              },
              summary:
                "Order header linked to this return or refund workflow run.",
            },
            {
              id: "reverse-run-return",
              label: "Fulfillment Return",
              target: {
                moduleName: "fulfillment",
                schemaName: "fulfillmentReturnRequest",
              },
              relation: {
                sourceField: "returnCode",
                targetField: "returnCode",
                cardinality: "ONE",
              },
              summary:
                "Fulfillment-owned return request, receipt, inspection, and disposition evidence coordinated by this run.",
            },
            {
              id: "reverse-run-refund-transaction",
              label: "Payment Refund",
              target: {
                moduleName: "payment",
                schemaName: "paymentTransaction",
              },
              relation: {
                sourceField: "refundTransactionCode",
                targetField: "transactionCode",
                cardinality: "ONE",
              },
              summary:
                "Payment-owned refund transaction evidence coordinated by this run.",
            },
            {
              id: "reverse-run-history",
              label: "Order History",
              target: { moduleName: "order", schemaName: "orderHistoryEntry" },
              relation: {
                sourceField: "reverseCode",
                targetField: "evidenceCode",
                cardinality: "MANY",
              },
              summary:
                "Order-centered lifecycle history entries recorded against this reverse workflow run.",
            },
          ],
          help: {
            summary:
              "Review workflow-backed reverse checkout runs, owner evidence, and recovery strategies for returns and refunds.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "carts",
          parentId: "checkout",
          label: "Carts",
          route: "/commerce/operations/checkout/carts",
          icon: "cart",
          order: 581,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["cart.backoffice.read"],
          workbenchTarget: { moduleName: "cart", schemaName: "cart" },
          detailPanels: [
            {
              id: "cart-entries",
              label: "Cart Entries",
              target: { moduleName: "cart", schemaName: "cartEntry" },
              relation: {
                sourceField: "code",
                targetField: "cartCode",
                cardinality: "MANY",
              },
              summary:
                "Line-level product, quantity, and pricing evidence currently attached to this cart.",
            },
            {
              id: "cart-delivery-groups",
              label: "Cart Delivery Groups",
              target: { moduleName: "cart", schemaName: "cartDeliveryGroup" },
              relation: {
                sourceField: "code",
                targetField: "cartCode",
                cardinality: "MANY",
              },
              summary:
                "Delivery groups that split cart-entry quantities across addresses, pickup points, digital delivery, or service destinations.",
            },
            {
              id: "cart-delivery-allocations",
              label: "Cart Delivery Allocations",
              target: {
                moduleName: "cart",
                schemaName: "cartDeliveryAllocation",
              },
              relation: {
                sourceField: "code",
                targetField: "cartCode",
                cardinality: "MANY",
              },
              summary:
                "Quantity-level cart-entry delivery allocations, including optional serial or inventory-unit evidence.",
            },
            {
              id: "cart-payment-groups",
              label: "Cart Payment Groups",
              target: { moduleName: "cart", schemaName: "cartPaymentGroup" },
              relation: {
                sourceField: "code",
                targetField: "cartCode",
                cardinality: "MANY",
              },
              summary:
                "Payment groups that split cart value across payment modes before order placement.",
            },
            {
              id: "cart-payment-allocations",
              label: "Cart Payment Allocations",
              target: {
                moduleName: "cart",
                schemaName: "cartPaymentAllocation",
              },
              relation: {
                sourceField: "code",
                targetField: "cartCode",
                cardinality: "MANY",
              },
              summary:
                "Quantity and amount-level cart-entry payment allocations.",
            },
          ],
          help: {
            summary:
              "Review persisted cart records through the Cart capability while checkout journey grouping stays in Commerce Operations.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "cart-entries",
          parentId: "checkout",
          label: "Cart Entries",
          route: "/commerce/operations/checkout/cart-entries",
          icon: "cart",
          order: 582,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["cart.backoffice.read"],
          workbenchTarget: { moduleName: "cart", schemaName: "cartEntry" },
          help: {
            summary:
              "Review cart line entries with product, quantity, unit, currency, and line price evidence.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "order-entries",
          parentId: "checkout",
          label: "Order Entries",
          route: "/commerce/operations/checkout/order-entries",
          icon: "commerce",
          order: 583,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["order.backoffice.read"],
          workbenchTarget: { moduleName: "order", schemaName: "orderEntry" },
          help: {
            summary:
              "Review immutable order line entries with product, quantity, pricing, tax, discount, and inventory evidence.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "cart-delivery-groups",
          parentId: "checkout",
          label: "Cart Delivery Groups",
          route: "/commerce/operations/checkout/cart-delivery-groups",
          icon: "commerce",
          order: 584,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["cart.backoffice.read"],
          workbenchTarget: {
            moduleName: "cart",
            schemaName: "cartDeliveryGroup",
          },
          help: {
            summary:
              "Review cart delivery groups used to split entry quantities across delivery destinations.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "cart-delivery-allocations",
          parentId: "checkout",
          label: "Cart Delivery Allocations",
          route: "/commerce/operations/checkout/cart-delivery-allocations",
          icon: "commerce",
          order: 585,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["cart.backoffice.read"],
          workbenchTarget: {
            moduleName: "cart",
            schemaName: "cartDeliveryAllocation",
          },
          help: {
            summary:
              "Review quantity-level delivery allocations for cart entries, including optional serial evidence.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "cart-payment-groups",
          parentId: "checkout",
          label: "Cart Payment Groups",
          route: "/commerce/operations/checkout/cart-payment-groups",
          icon: "commerce",
          order: 586,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["cart.backoffice.read"],
          workbenchTarget: {
            moduleName: "cart",
            schemaName: "cartPaymentGroup",
          },
          help: {
            summary:
              "Review cart payment groups used to split payment responsibility before order placement.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "cart-payment-allocations",
          parentId: "checkout",
          label: "Cart Payment Allocations",
          route: "/commerce/operations/checkout/cart-payment-allocations",
          icon: "commerce",
          order: 587,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["cart.backoffice.read"],
          workbenchTarget: {
            moduleName: "cart",
            schemaName: "cartPaymentAllocation",
          },
          help: {
            summary:
              "Review cart payment allocations that assign exact amounts to allocated entry quantities.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "order-delivery-groups",
          parentId: "checkout",
          label: "Order Delivery Groups",
          route: "/commerce/operations/checkout/order-delivery-groups",
          icon: "commerce",
          order: 588,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["order.backoffice.read"],
          workbenchTarget: {
            moduleName: "order",
            schemaName: "orderDeliveryGroup",
          },
          help: {
            summary:
              "Review order delivery groups that become shipment or consignment inputs for fulfillment.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "order-delivery-allocations",
          parentId: "checkout",
          label: "Order Delivery Allocations",
          route: "/commerce/operations/checkout/order-delivery-allocations",
          icon: "commerce",
          order: 589,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["order.backoffice.read"],
          workbenchTarget: {
            moduleName: "order",
            schemaName: "orderDeliveryAllocation",
          },
          help: {
            summary:
              "Review quantity-level delivery allocations for order entries, including optional serial evidence.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "order-payment-groups",
          parentId: "checkout",
          label: "Order Payment Groups",
          route: "/commerce/operations/checkout/order-payment-groups",
          icon: "commerce",
          order: 590,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["order.backoffice.read"],
          workbenchTarget: {
            moduleName: "order",
            schemaName: "orderPaymentGroup",
          },
          help: {
            summary:
              "Review order payment groups that coordinate payment modes and transaction evidence.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "order-payment-allocations",
          parentId: "checkout",
          label: "Order Payment Allocations",
          route: "/commerce/operations/checkout/order-payment-allocations",
          icon: "commerce",
          order: 591,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["order.backoffice.read"],
          workbenchTarget: {
            moduleName: "order",
            schemaName: "orderPaymentAllocation",
          },
          help: {
            summary:
              "Review order payment allocations that assign exact payment amounts to allocated entry quantities.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "order-history",
          parentId: "checkout",
          label: "Order History",
          route: "/commerce/operations/checkout/order-history",
          icon: "audit",
          order: 592,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["order.backoffice.read"],
          workbenchTarget: {
            moduleName: "order",
            schemaName: "orderHistoryEntry",
          },
          help: {
            summary:
              "Review order lifecycle events, status changes, actors, reason codes, and operational evidence.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "order-statuses",
          parentId: "checkout",
          label: "Order Statuses",
          route: "/commerce/operations/checkout/order-statuses",
          icon: "commerce",
          order: 593,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["order.backoffice.read"],
          workbenchTarget: { moduleName: "order", schemaName: "orderstatus" },
          help: {
            summary:
              "Maintain order-status reference records and sequencing used by order lifecycle flows.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "payment-statuses",
          parentId: "checkout",
          label: "Payment Statuses",
          route: "/commerce/operations/checkout/payment-statuses",
          icon: "commerce",
          order: 594,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["order.backoffice.read"],
          workbenchTarget: { moduleName: "order", schemaName: "paymentstatus" },
          help: {
            summary:
              "Maintain payment-status reference records used by order payment lifecycle tracking.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "shipping-statuses",
          parentId: "checkout",
          label: "Shipping Statuses",
          route: "/commerce/operations/checkout/shipping-statuses",
          icon: "commerce",
          order: 595,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "PREVIEW",
          requiredPermissions: ["order.backoffice.read"],
          workbenchTarget: {
            moduleName: "order",
            schemaName: "shippingstatus",
          },
          help: {
            summary:
              "Maintain shipping-status reference records used by fulfillment and shipping lifecycle tracking.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "shipments",
          parentId: "checkout",
          label: "Shipments",
          route: "/commerce/operations/checkout/shipments",
          icon: "commerce",
          order: 597,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "DISABLED",
          help: {
            summary:
              "Planned workspace for shipment records once the shipping backend model is introduced.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "returns",
          parentId: "checkout",
          label: "Returns",
          route: "/commerce/operations/checkout/returns",
          icon: "commerce",
          order: 598,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "DISABLED",
          help: {
            summary:
              "Planned workspace for return requests and return lines once the backend model is introduced.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "consignments",
          parentId: "checkout",
          label: "Consignments",
          route: "/commerce/operations/checkout/consignments",
          icon: "commerce",
          order: 600,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "DISABLED",
          help: {
            summary:
              "Planned workspace for consignment and fulfillment split records once the backend model is introduced.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "delivery-modes",
          parentId: "checkout",
          label: "Delivery Modes",
          route: "/commerce/operations/checkout/delivery-modes",
          icon: "commerce",
          order: 601,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "DISABLED",
          help: {
            summary:
              "Planned workspace for delivery-mode records once the backend model is introduced.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "tax-records",
          parentId: "checkout",
          label: "Tax Records",
          route: "/commerce/operations/checkout/tax-records",
          icon: "commerce",
          order: 603,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "DISABLED",
          help: {
            summary:
              "Planned workspace for tax calculation evidence once the backend model is introduced.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
        {
          id: "fraud-checks",
          parentId: "checkout",
          label: "Fraud Checks",
          route: "/commerce/operations/checkout/fraud-checks",
          icon: "commerce",
          order: 604,
          group: { id: "commerce", label: "Commerce", order: 300 },
          perspectives: ["operations", "commerce"],
          contexts: ["environment", "tenant", "enterprise"],
          featureState: "DISABLED",
          help: {
            summary:
              "Planned workspace for fraud-check evidence once the backend model is introduced.",
            documentationRoute: "/docs/capabilities/commerce/end-to-end",
          },
        },
      ],
    },
  },
};
