/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */
/** @module order/service/lifecycle/DefaultOrderRefundExecutionService @description Delegates an approved exact Refund plan to Payment owner without executing provider logic in Order. @layer service @owner order */
module.exports = {
    init: function () { return Promise.resolve(true); }, postInit: function () { return Promise.resolve(true); }, config: function () { return (((CONFIG.get('order') || {}).orderLifecycle || {}).refundExecution) || {}; },
    error: function (message) { let error = new Error(message); error.code = 'ERR_ORD_00064'; return error; },
    input: function (request) { return request.refundExecution || request.body || {}; },
    validate: function (request) { let input = this.input(request); let evidence = (input.request || {}).evidence || {}; if (!request.tenant || !request.authData || request.authData.tokenType !== 'service' || !input.request || input.request.requestType !== 'REFUND' || input.request.state !== 'APPROVED' || !evidence.calculation || !Array.isArray(evidence.calculation.paymentCalculation.allocationEvidence)) throw this.error('Refund execution requires internally approved immutable allocation evidence'); return input; },
    validateExecution: function (request, response, process) { try { response.refundExecutionInput = this.validate(request); process.nextSuccess(request, response); } catch (error) { process.error(request, response, error); } },
    executeProductLifecycleActions: async function (request, response, process) { try { let input = response.refundExecutionInput, items = [].concat(input.items || []), evidenceService = SERVICE[this.config().productEvidenceService], lifecycleService = SERVICE[this.config().productLifecycleService]; if (!evidenceService || typeof evidenceService.resolve !== 'function' || !lifecycleService || typeof lifecycleService.execute !== 'function') throw this.error('Refund Product lifecycle owner services are unavailable'); let evidence = await evidenceService.resolve({ tenant: request.tenant, authData: request.authData, entCode: input.request.entCode, orderCode: input.request.orderCode, items: items }); let byEntry = new Map([].concat(evidence.items || []).map(item => [item.orderEntryCode, item])), results = []; for (let item of items) { let owner = byEntry.get(item.orderEntryCode); if (!owner) throw this.error('Refund Product lifecycle evidence is incomplete'); results.push(await lifecycleService.execute({ tenant: request.tenant, authData: request.authData, productLifecycleCancellation: { lifecycleRequestCode: input.request.requestCode, requestVersion: input.request.version, orderCode: input.request.orderCode, orderEntryCode: item.orderEntryCode, lifecycleType: owner.lifecycleType, entitlementReference: owner.entitlementReference, entitlementState: owner.entitlementState, providerActionRequired: owner.providerActionRequired === true, providerActionCode: owner.providerActionCode } })); } response.productLifecycleExecution = results; process.nextSuccess(request, response); } catch (error) { process.error(request, response, error); } },
    executePaymentRefund: async function (request, response, process) { try { let input = response.refundExecutionInput; let calculation = input.request.evidence.calculation; let service = SERVICE[this.config().paymentExecutionService]; if (!service || typeof service.execute !== 'function') throw this.error('Payment refund execution owner is unavailable'); response.paymentRefundExecution = await service.execute({ tenant: request.tenant, authData: request.authData, refundExecution: { enterpriseCode: input.request.entCode, refundCode: input.request.requestCode, orderCode: input.request.orderCode, requestVersion: input.request.version, allocations: calculation.paymentCalculation.allocationEvidence } }); response.refundExecution = { productLifecycle: response.productLifecycleExecution, payment: response.paymentRefundExecution }; process.nextSuccess(request, response); } catch (error) { process.error(request, response, error); } },
    handleSuccessEnd: function (request, response, process) { process.resolve(response.refundExecution); }, handleErrorEnd: function (request, response, process) { process.reject(response.error || this.error('Refund execution Pipeline failed')); },
};
