/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */
/**
 * @module order/service/lifecycle/DefaultOrderCancellationIntentService
 * @description Secured customer and support intent boundary for cancellation creation, submission, status, and draft cancellation.
 * @layer service
 * @owner order
 * @override Projects may replace identity mapping while preserving authenticated ownership, immutable Order snapshots, idempotency, and private persistence.
 */
module.exports = {
    init: function () { return Promise.resolve(true); }, postInit: function () { return Promise.resolve(true); },
    config: function () { return (((CONFIG.get('order') || {}).orderLifecycle || {}).intents) || {}; },
    error: function (message, code) { if (typeof CLASSES !== 'undefined' && CLASSES.NodicsError) return new CLASSES.NodicsError(message, null, code || 'ERR_ORD_00055'); let error = new Error(message); error.code = code || 'ERR_ORD_00055'; return error; },
    items: function (value) { if (!value) return []; if (Array.isArray(value)) return value; if (Array.isArray(value.result)) return value.result; if (Array.isArray(value.items)) return value.items; return [value]; },
    principal: function (request) { let auth = (request || {}).authData || {}; return auth.customerCode || auth.principalId || auth.userCode || auth.code; },
    rateLimit: function (request, input) { let policy = this.config().rateLimit || {}; if (policy.enabled === false) return Promise.resolve({ allowed: true, enabled: false }); if (!SERVICE.DefaultOrderLifecycleRateLimitService || typeof SERVICE.DefaultOrderLifecycleRateLimitService.assertAllowed !== 'function') return Promise.reject(this.error('Customer lifecycle rate limit service is unavailable', 'ERR_ORD_00067')); return SERVICE.DefaultOrderLifecycleRateLimitService.assertAllowed(request, input); },
    enterprise: function (request, value) { let auth = request.authData || {}; let scoped = auth.entCode || auth.enterpriseCode; let allowed = [].concat(auth.enterpriseCodes || []).filter(Boolean); if (scoped && scoped !== value || allowed.length && !allowed.includes(value)) throw this.error('Cancellation enterprise is outside authenticated scope', 'ERR_ORD_00056'); return value; },
    loadOrder: async function (request, input) { let response = await SERVICE.DefaultOrderService.get({ tenant: request.tenant, authData: request.authData, query: { entCode: input.entCode, code: input.orderCode }, searchOptions: { limit: 2 } }); let records = this.items(response); if (records.length !== 1) throw this.error('Cancellation Order is unavailable'); return records[0]; },
    customerCode: function (request, order, support) { let auth = request.authData || {}; if (auth.tokenType !== 'access') throw this.error('Cancellation intent requires an authenticated access principal', 'ERR_ORD_00056'); if (support) { let code = (request.body || {}).customerCode || order.customerCode; if (!code || code !== order.customerCode) throw this.error('Support cancellation customer does not match Order', 'ERR_ORD_00056'); return code; } let code = auth.customerCode || this.principal(request); if (!code || order.customerCode !== code) throw this.error('Customer can access only their own Order', 'ERR_ORD_00056'); return code; },
    entries: async function (request, input) { let response = await SERVICE.DefaultOrderEntryService.get({ tenant: request.tenant, authData: request.authData, query: { entCode: input.entCode, orderCode: input.orderCode }, searchOptions: { limit: Number(this.config().maximumEntries || 500) + 1 } }); let records = this.items(response); if (records.length > Number(this.config().maximumEntries || 500)) throw this.error('Cancellation Order Entry evidence exceeds bounds'); return records; },
    snapshotItems: async function (request, input) { let records = await this.entries(request, input); let byCode = new Map(records.map(value => [value.entryCode, value])); return [].concat(input.items || []).map(selection => { let entry = byCode.get(selection.orderEntryCode); if (!entry) throw this.error('Cancellation selection does not belong to Order', 'ERR_ORD_00056'); return { orderEntryCode: entry.entryCode, requestedQuantity: selection.requestedQuantity, unitCode: entry.unitCode, serialNumbers: selection.serialNumbers || [], immutableEvidence: { orderedQuantity: entry.quantity, alreadyCancelledQuantity: entry.cancelledQuantity || '0', catalogCode: entry.catalogCode, itemType: entry.itemType, itemCode: entry.itemCode, lifecycleType: entry.lifecycleType || 'PHYSICAL', entitlementReference: entry.entitlementReference, entitlementState: entry.entitlementState, allocationCode: entry.allocationCode, reservationCode: entry.reservationCode, orderEntryLifecycleRevision: Number(entry.lifecycleRevision || 0) } }; }); },
    create: async function (request, support) { let input = Object.assign({}, request.body || {}); if (!request || !request.tenant || !request.authData || !input.entCode || !input.orderCode) throw this.error('Cancellation intent requires tenant, auth, enterprise, and Order'); this.enterprise(request, input.entCode); let order = await this.loadOrder(request, input); let customerCode = this.customerCode(request, order, support === true); if (support !== true) await this.rateLimit(request, input); let items = await this.snapshotItems(request, input); let intent = Object.assign({}, input, { requestType: 'CANCELLATION', customerCode: customerCode, siteCode: order.siteCode, channelCode: order.channelCode, currencyCode: order.currencyCode, locale: order.locale, countryCode: order.countryCode, requesterType: support ? 'EMPLOYEE' : 'CUSTOMER', items: items }); let created = await SERVICE.DefaultOrderLifecycleOrchestrationService.createDraft(Object.assign({}, request, { orderLifecycle: intent })); let submitted = await SERVICE.DefaultOrderLifecycleOrchestrationService.submit(Object.assign({}, request, { orderLifecycle: { requestCode: created.request.requestCode, entCode: input.entCode } })); await SERVICE.DefaultOrderLifecycleAuditService.record(request, submitted.request, 'CANCELLATION_SUBMITTED', submitted.request.workflowCarrierCode || submitted.request.requestCode, support ? 'Support submitted cancellation on behalf of customer' : 'Customer submitted cancellation'); return Object.assign({}, submitted, { createdIdempotently: created.idempotent === true }); },
    loadRequest: async function (request) { let input = Object.assign({}, request.query || {}, request.params || {}, request.body || {}); let entCode = input.entCode || request.entCode || (request.authData || {}).entCode || (request.authData || {}).enterpriseCode; let requestCode = input.requestCode; if (!entCode || !requestCode) throw this.error('Cancellation request identity is required'); this.enterprise(request, entCode); let model = await SERVICE.DefaultOrderLifecycleOrchestrationService.loadRequest(request, { entCode: entCode, requestCode: requestCode }); if (!model || model.requestType !== 'CANCELLATION') throw this.error('Cancellation request is unavailable'); return model; },
    status: async function (request, support) { let model = await this.loadRequest(request); let order = await this.loadOrder(request, { entCode: model.entCode, orderCode: model.orderCode }); let customerCode = this.customerCode(request, order, support === true); if (model.customerCode && model.customerCode !== customerCode) throw this.error('Cancellation request customer scope mismatch', 'ERR_ORD_00056'); let items = await SERVICE.DefaultOrderLifecycleOrchestrationService.loadItems(request, model.requestCode); return SERVICE.DefaultOrderLifecycleStatusProjectionService.project({ request: model, items: items }); },
    cancelDraft: async function (request, support) { let aggregate = await this.status(request, support); if (aggregate.request.state === 'CANCELLED') return Object.assign({ idempotent: true }, aggregate); if (!['DRAFT', 'SUBMISSION_FAILED'].includes(aggregate.request.state)) throw this.error('Only a non-submitted cancellation draft can be cancelled', 'ERR_ORD_00057'); let updated = await SERVICE.DefaultOrderLifecycleOrchestrationService.updateState(request, aggregate.request, [aggregate.request.state], { state: 'CANCELLED', evidence: Object.assign({}, aggregate.request.evidence || {}, { cancelledBy: this.principal(request), cancelledAt: new Date() }) }); await SERVICE.DefaultOrderLifecycleAuditService.record(request, updated, 'CANCELLATION_DRAFT_CANCELLED', updated.version, 'Cancellation draft cancelled'); return { request: updated, items: aggregate.items }; },
};
