/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */

/* Nodics - governed by the root LICENSE. */
/** @module order/service/lifecycle/DefaultOrderLifecycleSupportService @description Records scoped support recommendations and configured customer Notification intents. @layer service @owner order */
module.exports={init:function(){return Promise.resolve(true);},postInit:function(){return Promise.resolve(true);},error:function(message){let error=new Error(message);error.code='ERR_ORD_00069';return error;},input:function(request){return Object.assign({},request.body||{},request.params||{},{tenant:request.tenant,authData:request.authData});},scope:async function(request){let input=this.input(request),auth=request.authData||{};if(!request.tenant||auth.tokenType!=='access'||!input.requestCode)throw this.error('Support lifecycle operation requires authenticated request identity');let entCode=input.entCode||auth.entCode||auth.enterpriseCode;if(!entCode)throw this.error('Support lifecycle operation requires enterprise scope');let helper=SERVICE.DefaultOrderCancellationIntentService;helper.enterprise(request,entCode);let model=await SERVICE.DefaultOrderLifecycleOrchestrationService.loadRequest(request,{entCode:entCode,requestCode:input.requestCode});if(!model)throw this.error('Lifecycle request is unavailable');let order=await helper.loadOrder(request,{entCode:entCode,orderCode:model.orderCode}),sites=[].concat(auth.siteCodes||[]).filter(Boolean),channels=[].concat(auth.channelCodes||[]).filter(Boolean);if(sites.length&&!sites.includes(order.siteCode)||channels.length&&!channels.includes(order.channelCode))throw this.error('Lifecycle request is outside support scope');if(Number(input.expectedVersion)!==Number(model.version))throw this.error('Support lifecycle evidence version is stale');return{input:input,model:model,order:order};},recommend:async function(request){let context=await this.scope(request),input=context.input;if(!['APPROVE','REJECT'].includes(input.recommendation)||!input.recommendationCode||!input.reasonCode)throw this.error('Support recommendation requires decision, stable identity, and reason');let history=await SERVICE.DefaultOrderLifecycleAuditService.record(request,context.model,'SUPPORT_RECOMMENDATION_'+input.recommendation,input.recommendationCode,'Support recommendation: '+input.reasonCode);return{requestCode:context.model.requestCode,requestVersion:context.model.version,recommendation:input.recommendation,reasonCode:input.reasonCode,historyCode:history.historyCode,idempotent:history.idempotent===true};},message:async function(request){let context=await this.scope(request),input=context.input;if(!input.messageCode)throw this.error('Support customer message requires stable message identity');let history=await SERVICE.DefaultOrderLifecycleAuditService.record(request,context.model,'SUPPORT_CUSTOMER_MESSAGE_REQUESTED',input.messageCode,'Configured customer lifecycle message requested');let published=await SERVICE.DefaultOrderLifecycleEventService.publishSupportMessage(request,context.model,history,input);return{requestCode:context.model.requestCode,requestVersion:context.model.version,historyCode:history.historyCode,notification:published,idempotent:history.idempotent===true};}};
