/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */
/** @module order/service/lifecycle/DefaultOrderLifecycleReviewWorkflowService @description Handles Workflow-authorized information requests and escalation without bypassing human tasks. @layer service @owner order */
module.exports = {
    init: function () { return Promise.resolve(true); }, postInit: function () { return Promise.resolve(true); }, error: function (message) { let error = new Error(message); error.code = 'ERR_ORD_00067'; return error; },
    context: async function (request) { let carrier = request.workflowCarrier || {}, source = carrier.sourceDetail || {}; if (!carrier.code || source.processType !== 'orderLifecycleRequest' || !['CANCELLATION', 'RETURN', 'REFUND'].includes(source.requestType)) throw this.error('Lifecycle review Workflow source is incomplete'); let current = await SERVICE.DefaultOrderLifecycleOrchestrationService.loadRequest(request, { requestCode: source.requestCode, entCode: source.entCode }); if (!current || Number(current.version) !== Number(source.requestVersion)) throw this.error('Lifecycle review request version is stale'); return { carrier: carrier, source: source, current: current }; },
    actor: function (request) { let auth = request.authData || {}, code = auth.principalId || auth.code; if (auth.tokenType !== 'access' || !code) throw this.error('Lifecycle review requires an authenticated human actor'); return code; },
    requestInformation: async function (request) { let context = await this.context(request), actor = this.actor(request), input = request.workflowDecision || request.body || {}; if (!['APPROVAL_PENDING', 'AUTHORIZATION_PENDING'].includes(context.current.state)) throw this.error('Lifecycle request is not awaiting review'); let message = String(input.message || input.reason || '').trim(); if (!message || message.length > 2000) throw this.error('Information request message is required and bounded'); let updated = await SERVICE.DefaultOrderLifecycleOrchestrationService.updateState(request, context.current, [context.current.state], { state: 'INFORMATION_REQUESTED', evidence: Object.assign({}, context.current.evidence || {}, { informationRequest: { message: message, requestedBy: actor, requestedAt: new Date() } }) }); await SERVICE.DefaultOrderLifecycleAuditService.record(request, updated, context.source.requestType + '_INFORMATION_REQUESTED', updated.version, 'Reviewer requested more information'); return { decision: 'SUCCESS', type: 'SUCCESS', feedback: { requestCode: updated.requestCode, state: updated.state } }; },
    escalate: async function (request) { let context = await this.context(request), actor = this.actor(request), input = request.workflowDecision || request.body || {}; if (!['APPROVAL_PENDING', 'AUTHORIZATION_PENDING'].includes(context.current.state)) throw this.error('Lifecycle request is not awaiting review'); let updated = await SERVICE.DefaultOrderLifecycleOrchestrationService.updateState(request, context.current, [context.current.state], { state: 'ESCALATED', evidence: Object.assign({}, context.current.evidence || {}, { escalation: { reason: String(input.reason || 'REVIEW_ESCALATION').slice(0, 500), escalatedBy: actor, escalatedAt: new Date() } }) }, false); await SERVICE.DefaultOrderLifecycleAuditService.record(request, updated, context.source.requestType + '_ESCALATED', updated.version, 'Reviewer escalated lifecycle request'); return { decision: 'SUCCESS', type: 'SUCCESS', feedback: { requestCode: updated.requestCode, state: updated.state } }; },
};
