/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is the confidential and proprietary information of Nodics ("Confidential Information").
    You shall not disclose such Confidential Information and shall use it only in accordance with the
    terms of the license agreement you entered into with Nodics.

 */

const crypto = require('crypto');
/** @module product/service/publication/DefaultProductPublicationTargetService @description Idempotently imports immutable Product releases and atomically activates Online Catalog pointers. @layer service @owner product */
module.exports = {
    /** Initializes the Product target. */ init: function () { return Promise.resolve(true); },
    /** Completes target initialization. */ postInit: function () { return Promise.resolve(true); },
    /** Extracts generated-service items. */ items: function (response) { return response && Array.isArray(response.result) ? response.result : []; },
    /** Removes source database and version metadata. */ targetModel: function (source) { let model = Object.assign({}, source); ['_id', 'versionId', 'created', 'updated', 'createdBy', 'updatedBy', 'ownerId', 'ownerType'].forEach(property => delete model[property]); return model; },
    /** Binds integrity-checked enterprise scope to target interceptors. */ bindEnterprise: function (request, enterpriseCode) { if (!enterpriseCode) throw new CLASSES.NodicsError('ERR_PRODUCT_00001', 'Product publication enterprise context is required'); request.authData = Object.assign({}, request.authData, { enterprise: { code: enterpriseCode } }); return request; },
    /** Returns Product publication configuration. */ config: function () { return (CONFIG.get('product') || {}).publication || {}; },
    /** Requires a distinct non-versioned Online role. */ assertOnline: function () { if (this.config().runtimeRole !== 'ONLINE' || CONFIG.get('publishEnabled') === true) throw new CLASSES.NodicsError('ERR_PRODUCT_00050', 'Product target requires a non-versioned Online runtime'); },
    /** Normalizes affected-record counts. */ affected: function (response) { let value = response && response.result !== undefined ? response.result : response; return Number(value && (value.modifiedCount || value.nModified || value.n) || 0); },
    /** Loads the current Online pointer. */ pointer: async function (scope, request) { return this.items(await SERVICE.DefaultProductOnlinePointerService.get({ tenant: request.tenant, authData: request.authData, query: { enterpriseCode: scope.enterpriseCode, catalogCode: scope.catalogCode }, searchOptions: { limit: 1 } }))[0]; },
    /** Loads an accepted Online manifest. */ manifest: async function (code, request) { return this.items(await SERVICE.DefaultProductReleaseManifestService.get({ tenant: request.tenant, authData: request.authData, query: { code: code }, searchOptions: { limit: 1 } }))[0]; },
    /** Imports an integrity-checked manifest idempotently. */ importManifest: async function (manifest, request) { SERVICE.DefaultProductPublicationManifestService.verify(manifest); let existing = await this.manifest(manifest.code, request); if (existing) { if (existing.contentHash !== manifest.contentHash) throw new CLASSES.NodicsError('ERR_PRODUCT_00047', 'Product manifest identity conflict'); return existing; } let target = Object.assign(this.targetModel(manifest), { active: true }), response = await SERVICE.DefaultProductReleaseManifestService.save({ tenant: request.tenant, authData: request.authData, model: target }); return this.items(response)[0] || response.result || target; },
    /** Upserts all non-versioned Product Online records. */ importRecords: async function (manifest, request) { for (let record of manifest.snapshot.records || []) { let service = SERVICE.DefaultProductPublicationManifestService.serviceFor(record.schema), model = this.targetModel(record.model), existing = this.items(await service.get({ tenant: request.tenant, authData: request.authData, query: { code: model.code }, searchOptions: { limit: 1 } }))[0]; if (existing) await service.update({ tenant: request.tenant, authData: request.authData, query: { code: model.code }, model: model }); else await service.save({ tenant: request.tenant, authData: request.authData, model: model }); } return true; },
    /** Atomically changes the active Product Catalog pointer. */ activate: async function (manifest, request) { let scope = manifest.snapshot, current = await this.pointer(scope, request); if (current && current.manifestCode === manifest.code) return { version: manifest.code, previousOnlineVersion: current.previousManifestCode }; let patch = { manifestCode: manifest.code, previousManifestCode: current && current.manifestCode, revision: Number(current && current.revision || 0) + 1, correlationId: request.correlationId || request.requestId }; if (current) { let response = await SERVICE.DefaultProductOnlinePointerService.update({ tenant: request.tenant, authData: request.authData, query: { code: current.code, revision: Number(current.revision || 0) }, model: patch }); if (this.affected(response) !== 1) throw new CLASSES.NodicsError('ERR_PRODUCT_00051', 'Product Online pointer revision conflict'); } else { let code = crypto.createHash('sha256').update(scope.enterpriseCode + '|' + scope.catalogCode).digest('hex'); await SERVICE.DefaultProductOnlinePointerService.save({ tenant: request.tenant, authData: request.authData, model: Object.assign({ code: code, active: true, enterpriseCode: scope.enterpriseCode, catalogCode: scope.catalogCode }, patch) }); } return { version: manifest.code, previousOnlineVersion: current && current.manifestCode }; },
    /** Persists one idempotent deployment receipt. */ receipt: async function (operation, manifest, result, request) { let code = operation + '_' + manifest.code, existing = this.items(await SERVICE.DefaultProductPublicationReceiptService.get({ tenant: request.tenant, authData: request.authData, query: { code: code }, searchOptions: { limit: 1 } }))[0]; if (existing) return existing; let model = { code: code, active: true, manifestCode: manifest.code, operation: operation, status: 'ONLINE', targetVersion: result.version, previousOnlineVersion: result.previousOnlineVersion, correlationId: request.correlationId || request.requestId }, response = await SERVICE.DefaultProductPublicationReceiptService.save({ tenant: request.tenant, authData: request.authData, model: model }); return this.items(response)[0] || model; },
    /** Deploys and activates one accepted Product manifest. */ deploy: async function (request) { this.assertOnline(); let input = request.body || request, manifest = input.manifest, target = this.config().target || {}; if (!manifest || Buffer.byteLength(JSON.stringify(manifest), 'utf8') > Number(target.maxManifestBytes || 20971520)) throw new CLASSES.NodicsError('ERR_PRODUCT_00052', 'Product manifest is missing or exceeds target bounds'); if (![].concat(target.supportedContractVersions || [1]).includes(manifest.snapshot && manifest.snapshot.contractVersion)) throw new CLASSES.NodicsError('ERR_PRODUCT_00053', 'Product publication contract is unsupported'); SERVICE.DefaultProductPublicationManifestService.verify(manifest); this.bindEnterprise(request, manifest.snapshot.enterpriseCode); manifest = await this.importManifest(manifest, request); await this.importRecords(manifest, request); let result = await this.activate(manifest, request); await this.receipt('DEPLOY', manifest, result, request); if (SERVICE.DefaultProductOnlineProjectionService) await SERVICE.DefaultProductOnlineProjectionService.afterActivate({ domain: 'product' }, result, request); return result; },
    /** Gets the active Product Catalog release. */ getStatus: async function (request) { this.assertOnline(); let input = request.body || request, scope = input.scope || {}; this.bindEnterprise(request, scope.enterpriseCode); let pointer = await this.pointer(scope, request); return pointer && { version: pointer.manifestCode, previousOnlineVersion: pointer.previousManifestCode }; },
    /** Reactivates a previously accepted Online Product manifest. */ rollback: async function (request) { this.assertOnline(); let input = request.body || request; this.bindEnterprise(request, input.enterpriseCode); let manifest = await this.manifest(input.manifestCode, request); if (!manifest) throw new CLASSES.NodicsError('ERR_PRODUCT_00054', 'Rollback Product manifest is unavailable Online'); await this.importRecords(manifest, request); let result = await this.activate(manifest, request); await this.receipt('ROLLBACK', manifest, result, request); if (SERVICE.DefaultProductOnlineProjectionService) await SERVICE.DefaultProductOnlineProjectionService.afterRollback({ domain: 'product' }, result, request); return result; }
};
