/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is the confidential and proprietary information of Nodics ("Confidential Information").
    You shall not disclose such Confidential Information and shall use it only in accordance with the
    terms of the license agreement you entered into with Nodics.

 */

/** @module product/service/publication/DefaultProductPublicationAdapterService @description Freezes one exact, bounded Product Catalog graph for the existing nPublish lifecycle. @layer service @owner product */
module.exports = {
    /** Initializes the Product publication adapter. */ init: function () { return Promise.resolve(true); },
    /** Completes adapter initialization. */ postInit: function () { return Promise.resolve(true); },
    /** Extracts generated-service items. */ items: function (response) { return response && Array.isArray(response.result) ? response.result : []; },
    /** Selects the latest immutable version for every stable record code. */ latestByCode: function (records) { return Array.from((records || []).reduce((map, record) => { let current = map.get(record.code); if (!current || Number(record.versionId || 0) > Number(current.versionId || 0)) map.set(record.code, record); return map; }, new Map()).values()); },
    /** Returns the Product schema/service release catalog. */ descriptors: function () { return { productItem: 'DefaultProductItemService', productIdentifier: 'DefaultProductIdentifierService', productCategory: 'DefaultProductCategoryService', productCategoryAssignment: 'DefaultProductCategoryAssignmentService', productAttributeDefinition: 'DefaultProductAttributeDefinitionService', productAttributeValue: 'DefaultProductAttributeValueService', productClassificationClass: 'DefaultProductClassificationClassService', productClassificationAssignment: 'DefaultProductClassificationAssignmentService', productVariantAxis: 'DefaultProductVariantAxisService', productVariantAssignment: 'DefaultProductVariantAssignmentService', productRelation: 'DefaultProductRelationService', productBundleEntry: 'DefaultProductBundleEntryService', productPackaging: 'DefaultProductPackagingService', productMediaReference: 'DefaultProductMediaReferenceService' }; },
    /** Loads the exact active root Product Item version. */ getVersion: async function (publication, request) { let response = await SERVICE.DefaultProductItemService.get({ tenant: request.tenant, authData: request.authData, query: { code: publication.rootCode, versionId: Number(publication.sourceVersion), active: true, status: 'ACTIVE' }, searchOptions: { limit: 1 } }), root = this.items(response)[0]; if (!root) throw new CLASSES.NodicsError('ERR_PRODUCT_00040', 'Active Product publication source version was not found'); return root; },
    /** Creates one exact dependency identity. */ identity: function (schema, model) { return { schema: schema, code: model.code, version: String(model.versionId) }; },
    /** Resolves the latest exact version of every business-active Product record in the root Catalog. */ resolveDependencies: async function (publication, root, request) { let dependencies = [], max = Number(((CONFIG.get('product') || {}).publication || {}).maxDependencies || 20000); for (let entry of Object.entries(this.descriptors())) { let records = this.latestByCode(this.items(await SERVICE[entry[1]].get({ tenant: request.tenant, authData: request.authData, query: { enterpriseCode: root.enterpriseCode, catalogCode: root.catalogCode, active: true, status: 'ACTIVE' }, searchOptions: { sort: { versionId: -1 } } }))); records.forEach(model => dependencies.push(this.identity(entry[0], model))); } let rootIdentity = this.identity('productItem', root); if (!dependencies.some(item => item.schema === rootIdentity.schema && item.code === rootIdentity.code && item.version === rootIdentity.version)) dependencies.push(rootIdentity); let unique = Array.from(dependencies.reduce((map, item) => { map.set(item.schema + ':' + item.code + ':' + item.version, item); return map; }, new Map()).values()).sort((left, right) => (left.schema + ':' + left.code + ':' + left.version).localeCompare(right.schema + ':' + right.code + ':' + right.version)); if (unique.length > max) throw new CLASSES.NodicsError('ERR_PRODUCT_00041', 'Product publication exceeds configured dependency bounds'); return unique; },
    /** Validates the frozen Product dependency graph. */ validate: function (publication, root, request, dependencies) { let keys = (dependencies || []).map(item => item.schema + ':' + item.code + ':' + item.version), rootKey = 'productItem:' + root.code + ':' + root.versionId; return Promise.resolve({ valid: Boolean(root.enterpriseCode && root.catalogCode && keys.includes(rootKey) && keys.length === new Set(keys).size), rootVersion: root.versionId, dependencyCount: keys.length }); },
    /** Leaves cache/search follow-up to configured Product Online hooks. */ afterActivate: function (publication, activation, request) { return SERVICE.DefaultProductOnlineProjectionService && SERVICE.DefaultProductOnlineProjectionService.afterActivate ? SERVICE.DefaultProductOnlineProjectionService.afterActivate(publication, activation, request) : Promise.resolve(true); },
    /** Leaves rollback projection follow-up to the same replaceable hook. */ afterRollback: function (publication, activation, request) { return SERVICE.DefaultProductOnlineProjectionService && SERVICE.DefaultProductOnlineProjectionService.afterRollback ? SERVICE.DefaultProductOnlineProjectionService.afterRollback(publication, activation, request) : Promise.resolve(true); }
};
