/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */

/* Nodics - governed by the root LICENSE. */
/** @module payment/service/refund/DefaultPaymentRefundDiagnosticsService @description Reports bounded Payment-owned Refund amount, latency, retry, failure, correlation, orphan, and over-refund diagnostics. @layer service @owner payment */
module.exports = { init: function () { return Promise.resolve(true); }, postInit: function () { return Promise.resolve(true); }, items: value => value && Array.isArray(value.result) ? value.result : [], scale: value => String(value).includes('.') ? String(value).split('.')[1].length : 0, greater: function (left, right) { let exact = SERVICE.DefaultExactUnitsService, a = exact.parse(left), b = exact.parse(right), scale = Math.max(a.scale, b.scale); return a.unscaled * 10n ** BigInt(scale - a.scale) > b.unscaled * 10n ** BigInt(scale - b.scale); }, scan: async function (request) { let result = await SERVICE.DefaultPaymentTransactionService.get({ tenant: request.tenant, authData: request.authData, query: { enterpriseCode: request.enterpriseCode, operation: 'REFUND' }, searchOptions: { limit: 501, sort: { requestedAt: -1 } } }), items = this.items(result); if (items.length > 500) throw new Error('Payment Refund diagnostics scan bound exceeded'); if (!SERVICE.DefaultExactUnitsService) throw new Error('Exact Units authority is unavailable'); let total = '0', failures = 0, retries = 0, latencies = [], correlations = {}, findings = []; items.forEach(item => { if (typeof item.amount === 'string') total = SERVICE.DefaultExactUnitsService.add(total, item.amount, Math.max(this.scale(total), this.scale(item.amount)), 'UNNECESSARY'); retries += Number(item.retryCount || 0); if (item.failureCode || ['FAILED', 'RECONCILIATION_REQUIRED'].includes(item.status)) { failures += 1; findings.push({ severity: 'HIGH', findingCode: 'FAILED_PROVIDER_REFUND', owner: 'payment', transactionCode: item.transactionCode, failureCode: item.failureCode, nextActions: ['RETRY_OR_RECONCILE_PROVIDER_REFUND'] }); } let start = new Date(item.requestedAt), end = new Date(item.completedAt); if (Number.isFinite(start.getTime()) && Number.isFinite(end.getTime()) && end >= start) latencies.push(end - start); if (item.refundCode) correlations[item.refundCode] = item.transactionCode; else findings.push({ severity: 'HIGH', findingCode: 'ORPHAN_PAYMENT_REFUND', owner: 'payment', transactionCode: item.transactionCode, nextActions: ['REVIEW_PAYMENT_REFUND_AUTHORITY'] }); if (typeof item.amount === 'string' && typeof item.authorizedAmount === 'string' && this.greater(item.amount, item.authorizedAmount)) findings.push({ severity: 'CRITICAL', findingCode: 'OVER_REFUND_RISK', owner: 'payment', transactionCode: item.transactionCode, nextActions: ['BLOCK_AND_RECONCILE_REFUND'] }); }); return { metrics: { refundCount: items.length, refundAmount: total, failureCount: failures, retryCount: retries, averageProviderLatencyMs: latencies.length ? Math.round(latencies.reduce((a, b) => a + b, 0) / latencies.length) : 0 }, correlations, findings }; } };
