/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is the confidential and proprietary information of Nodics ("Confidential Information").
    You shall not disclose such Confidential Information and shall use it only in accordance with the
    terms of the license agreement you entered into with Nodics.

 */

/** @module product/test/ProductOnlineDeliveryAndProjectionContract @description Proves active-manifest reads, bounded expansions, release-qualified caching, tenant/enterprise isolation, nSearch delegation, durable partial failure, retry, and restricted operations. @layer test @owner product */
const assert = require('assert'), configuration = require('../config/properties'), routers = require('../src/router/routers').product, authConfiguration = require('../../../gFramework/nAuth/config/properties'), groups = require('../../../gCore/profile/data/init/data/groups/defaultUserGroupsData');
class NodicsError extends Error { constructor(code, message) { super(message || code); this.code = code; } }
let publishEnabled = false; global.CLASSES = { NodicsError }; global.CONFIG = { get: key => key === 'publishEnabled' ? publishEnabled : configuration[key] }; global.SERVICE = {};
SERVICE.DefaultProductEnterpriseScopeService = require('../src/service/foundation/defaultProductEnterpriseScopeService');
let item = { code: 'item-1', enterpriseCode: 'entA', catalogCode: 'retail', itemType: 'SKU', itemCode: 'phone-red', name: 'Phone Red', description: 'Red phone', sellable: true, stockManaged: true, status: 'ACTIVE' }, manifest = { code: 'manifest-1', contentHash: '', snapshot: { contractVersion: 1, enterpriseCode: 'entA', catalogCode: 'retail', records: [{ schema: 'productItem', model: item }, { schema: 'productAttributeValue', model: { itemType: 'SKU', itemCode: 'phone-red', attributeCode: 'color', stringValue: 'RED', status: 'ACTIVE' } }, { schema: 'productMediaReference', model: { itemType: 'SKU', itemCode: 'phone-red', mediaType: 'IMAGE', role: 'PRIMARY', uri: 'https://media.example/phone.webp', position: 1, status: 'ACTIVE' } }] } };
const manifestService = require('../src/service/publication/defaultProductPublicationManifestService'); manifest.contentHash = manifestService.hash([], manifest.snapshot); manifest.dependencies = [];
SERVICE.DefaultProductPublicationManifestService = manifestService;
const matches = (model, query) => Object.keys(query || {}).every(key => query[key] && query[key].$in ? query[key].$in.includes(model[key]) : model[key] === query[key]);
let pointers = [{ code: 'pointer-1', enterpriseCode: 'entA', catalogCode: 'retail', manifestCode: 'manifest-1', previousManifestCode: 'manifest-0', revision: 2 }], manifests = [manifest], jobs = [], receipts = [{ targetVersion: 'manifest-1', operation: 'DEPLOY', status: 'ONLINE', correlationId: 'corr-1' }];
const mutable = list => ({ get: async request => ({ result: list.filter(model => matches(model, request.query)) }), save: async request => { list.push(Object.assign({}, request.model)); return { result: [request.model] }; }, update: async request => { let found = list.find(model => matches(model, request.query)); if (found) Object.assign(found, request.model); return { result: { modifiedCount: found ? 1 : 0 } }; } });
SERVICE.DefaultProductOnlinePointerService = mutable(pointers); SERVICE.DefaultProductReleaseManifestService = mutable(manifests); SERVICE.DefaultProductProjectionJobService = mutable(jobs); SERVICE.DefaultProductPublicationReceiptService = mutable(receipts);
const readService = require('../src/service/delivery/defaultProductOnlineReadService'); SERVICE.DefaultProductOnlineReadService = readService;
let cache = new Map(), cacheGets = 0, cachePuts = 0, invalidations = 0; SERVICE.DefaultCacheService = { get: async request => { cacheGets++; if (!cache.has(request.key)) throw new Error('MISS'); return cache.get(request.key); }, put: async request => { cachePuts++; cache.set(request.key, request.value); return true; }, invalidateResource: async request => { assert.strictEqual(request.resourceName, 'productDelivery'); invalidations++; cache.clear(); return true; } };
const cacheService = require('../src/service/delivery/defaultProductDeliveryCacheService'); SERVICE.DefaultProductDeliveryCacheService = cacheService;
(async () => {
    configuration.product.publication.runtimeRole = 'ONLINE'; let authData = { tokenType: 'access', principalId: 'customer-1', enterprise: { code: 'entA' } }, request = { tenant: 't1', authData, params: { itemType: 'SKU', itemCode: 'phone-red' }, query: { catalogCode: 'retail', localeCode: 'en-AE', expand: 'attributes,media' } };
    assert.strictEqual(routers.online.readItem.authTokenTypes[0], 'access'); assert.strictEqual(routers.online.readItem.permission, 'product.online.read'); assert.strictEqual(routers.publicationTarget.deploy.permissionConfig, 'authSecurity.internalToken.routePermission'); assert.strictEqual(routers.operations.reconcile.permission, 'product.operations.manage');
    ['product.online.read', 'product.operations.read', 'product.operations.manage'].forEach(permission => assert(authConfiguration.identityGovernance.permissionCatalog.includes(permission))); assert(Object.values(groups).find(group => group.code === 'customerUserGroup').permissions.includes('product.online.read'));
    let first = await cacheService.resolve(request), second = await cacheService.resolve(request); assert.strictEqual(first.item.itemCode, 'phone-red'); assert.strictEqual(first.releaseVersion, 'manifest-1'); assert.strictEqual(first.attributes[0].stringValue, 'RED'); assert.strictEqual(second.item.itemCode, 'phone-red'); assert.strictEqual(cacheGets, 2); assert.strictEqual(cachePuts, 1);
    await assert.rejects(cacheService.resolve(Object.assign({}, request, { authData: { tokenType: 'access', principalId: 'other', enterprise: { code: 'entB' } } })), error => error.code === 'ERR_PRODUCT_00061');
    await assert.rejects(readService.resolve(Object.assign({}, request, { query: { catalogCode: 'retail', expand: 'unknown' } })), error => error.code === 'ERR_PRODUCT_00060');
    configuration.product.searchProjection.enabled = true; let indexAttempts = 0; SERVICE.DefaultIndexerService = { prepareIndexer: async input => { indexAttempts++; assert.strictEqual(input.indexName, 'productOnline'); assert.strictEqual(input.models[0].releaseVersion, 'manifest-1'); if (indexAttempts === 1) throw new NodicsError('SEARCH_DOWN'); return true; } };
    let searchProvider = require('../src/service/projection/defaultProductSearchProjectionProviderService'); SERVICE.DefaultProductSearchProjectionProviderService = searchProvider; let projection = require('../src/service/projection/defaultProductProjectionOrchestrationService'); SERVICE.DefaultProductProjectionOrchestrationService = projection;
    let partial = await projection.afterActivation('ACTIVATE', 'manifest-1', { tenant: 't1', authData, correlationId: 'corr-1' }); assert.strictEqual(partial.state, 'PARTIAL'); assert.strictEqual(partial.cacheState, 'COMPLETE'); assert.strictEqual(partial.searchState, 'FAILED'); assert.strictEqual(invalidations, 1);
    let retry = await projection.reconcile({ tenant: 't1', authData, catalogCode: 'retail' }); assert.strictEqual(retry.completed, 1); assert.strictEqual(jobs[0].state, 'COMPLETE'); assert.strictEqual(indexAttempts, 2); assert.strictEqual(invalidations, 1, 'completed cache projection must not repeat during search retry');
    SERVICE.DefaultProductManagementService = { authorize: input => { if (input.authData.tokenType === 'service') throw new NodicsError('ERR_PRODUCT_00022'); return 'entA'; } }; let operations = require('../src/service/operations/defaultProductOperationsService'), diagnostics = await operations.diagnostics({ tenant: 't1', authData, params: { catalogCode: 'retail' } }); assert.strictEqual(diagnostics.activeRelease, 'manifest-1'); assert.strictEqual(diagnostics.manifest.recordCount, 3); assert.strictEqual(diagnostics.projections[0].state, 'COMPLETE');
    console.log('Product P3 Online delivery and projection resilience contract validated');
})().catch(error => { console.error(error); process.exit(1); });
