/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */

/** @module notifySchema/src/schemas/schemas @description Private multi-tenant notification, template, provider, delivery, suppression, verification, and in-app evidence schemas. @layer schema @owner notifySchema @override Later modules may extend definitions while preserving stable identities, private mutation, redaction, and owner boundaries. */
const model = (definition, common, individual) => ({ super: 'base', model: true, service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, search: { enabled: false }, event: { enabled: false }, definition, indexes: { common: common || {}, individual: individual || {} } });
const scoped = () => ({ tenantCode: { type: 'string', required: true, searchOptions: { enabled: true } }, enterpriseCode: { type: 'string', required: true, searchOptions: { enabled: true } }, siteCode: { type: 'string', required: false, searchOptions: { enabled: true } } });
const identity = (name, description) => ({ [name]: { type: 'string', required: true, searchOptions: { enabled: true }, description } });
const commonIndexes = { tenantCode: { enabled: true, name: 'tenantCode' }, enterpriseCode: { enabled: true, name: 'enterpriseCode' }, siteCode: { enabled: true, name: 'siteCode' }, status: { enabled: true, name: 'status' } };
const unique = name => ({ [name]: { enabled: true, name, options: { unique: true } } });
module.exports = { notifySchema: {
  notifyChannel: model(Object.assign({}, scoped(), identity('channelCode', 'Stable delivery surface identity'), { label: { type: 'string', required: true }, contentFields: { type: 'array', required: true }, supportedContentTypes: { type: 'array', required: true }, constraints: { type: 'object', required: true }, renderHints: { type: 'object', required: false }, compatibleProviderCodes: { type: 'array', required: false }, retentionDays: { type: 'int', required: true }, safePreview: { type: 'bool', required: true, default: true }, status: { type: 'string', required: true, default: 'DRAFT' }, version: { type: 'int', required: true, default: 1 } }), commonIndexes, unique('channelCode')),
  notifyScenario: model(Object.assign({}, scoped(), identity('scenarioCode', 'Stable business communication purpose'), { label: { type: 'string', required: true }, ownerModule: { type: 'string', required: true }, defaultAudience: { type: 'array', required: true }, requiredVariables: { type: 'array', required: true }, allowedChannels: { type: 'array', required: true }, allowedMessageTypes: { type: 'array', required: true }, policyCodes: { type: 'array', required: false }, documentationRoute: { type: 'string', required: true }, riskLevel: { type: 'string', required: true }, status: { type: 'string', required: true, default: 'DRAFT' }, version: { type: 'int', required: true, default: 1 } }), commonIndexes, unique('scenarioCode')),
  notifyMessageType: model(Object.assign({}, scoped(), identity('messageTypeCode', 'Governance classification identity'), { label: { type: 'string', required: true }, consentRequired: { type: 'bool', required: true }, approvalRequired: { type: 'bool', required: true }, riskLevel: { type: 'string', required: true }, retentionDays: { type: 'int', required: true }, auditMode: { type: 'string', required: true }, retryPolicyCode: { type: 'string', required: false }, recipientRestrictions: { type: 'array', required: false }, complianceClassifications: { type: 'array', required: false }, status: { type: 'string', required: true, default: 'DRAFT' }, version: { type: 'int', required: true, default: 1 } }), commonIndexes, unique('messageTypeCode')),
  notifyDeliveryPolicy: model(Object.assign({}, scoped(), identity('policyCode', 'Layered notification delivery policy identity'), { priority: { type: 'int', required: true }, channelCodes: { type: 'array', required: false }, scenarioCodes: { type: 'array', required: false }, messageTypeCodes: { type: 'array', required: false }, consentRequired: { type: 'bool', required: false }, quietHours: { type: 'object', required: false }, retryPolicyCode: { type: 'string', required: false }, fallbackAllowed: { type: 'bool', required: false }, providerCodes: { type: 'array', required: false }, maximumPerWindow: { type: 'int', required: false }, windowMs: { type: 'int', required: false }, effectiveFrom: { type: 'date', required: false }, effectiveUntil: { type: 'date', required: false }, status: { type: 'string', required: true, default: 'DRAFT', searchOptions: { enabled: true } }, version: { type: 'int', required: true, default: 1 }, approvalEvidence: { type: 'object', required: false } }), Object.assign({}, commonIndexes, { priority: { enabled: true, name: 'priority' } }), unique('policyCode')),
  notifyTemplate: model(Object.assign({}, scoped(), identity('templateCode', 'Stable centralized template identity'), { channelCode: { type: 'string', required: true, searchOptions: { enabled: true } }, scenarioCode: { type: 'string', required: true, searchOptions: { enabled: true } }, messageTypeCode: { type: 'string', required: true, searchOptions: { enabled: true } }, locale: { type: 'string', required: true, searchOptions: { enabled: true } }, ownerModule: { type: 'string', required: true }, activeVersionCode: { type: 'string', required: false }, policyCodes: { type: 'array', required: false }, axisPresentation: { type: 'object', required: false }, status: { type: 'string', required: true, default: 'DRAFT', searchOptions: { enabled: true } }, version: { type: 'int', required: true, default: 1 }, updatedByPrincipalId: { type: 'string', required: false }, approvalEvidence: { type: 'object', required: false }, rollbackEvidence: { type: 'object', required: false } }), commonIndexes, unique('templateCode')),
  notifyTemplateVersion: model(Object.assign({}, scoped(), identity('templateVersionCode', 'Immutable template revision identity'), { templateCode: { type: 'string', required: true, searchOptions: { enabled: true } }, version: { type: 'int', required: true }, content: { type: 'object', required: true }, variableBindings: { type: 'array', required: true }, status: { type: 'string', required: true, default: 'DRAFT', searchOptions: { enabled: true } }, approvalState: { type: 'string', required: true, default: 'NOT_REQUIRED' }, createdByPrincipalId: { type: 'string', required: true }, publishEvidence: { type: 'object', required: false }, rollbackEvidence: { type: 'object', required: false }, retiredAt: { type: 'date', required: false } }), Object.assign({}, commonIndexes, { templateCode: { enabled: true, name: 'templateCode' } }), unique('templateVersionCode')),
  notifyVariableDefinition: model(Object.assign({}, scoped(), identity('variableCode', 'Allowed backend context variable'), { scenarioCode: { type: 'string', required: true, searchOptions: { enabled: true } }, valueType: { type: 'string', required: true }, required: { type: 'bool', required: true }, sensitive: { type: 'bool', required: true }, protected: { type: 'bool', required: true }, sampleValue: { type: 'string', required: false }, maskingRule: { type: 'string', required: false }, loggingRule: { type: 'string', required: true }, previewRule: { type: 'string', required: true }, builderService: { type: 'string', required: false }, status: { type: 'string', required: true, default: 'DRAFT' }, version: { type: 'int', required: true, default: 1 } }), Object.assign({}, commonIndexes, { scenarioCode: { enabled: true, name: 'scenarioCode' } }), unique('variableCode')),
  notifyMessageContext: model(Object.assign({}, scoped(), identity('contextCode', 'Bounded resolved value evidence identity'), { requestCode: { type: 'string', required: true, searchOptions: { enabled: true } }, scenarioCode: { type: 'string', required: true }, valueEvidence: { type: 'object', required: true, description: 'Masked or reference-only evidence; protected resolved values are prohibited' }, sensitiveVariableCodes: { type: 'array', required: false }, status: { type: 'string', required: true }, expiresAt: { type: 'date', required: false } }), Object.assign({}, commonIndexes, { requestCode: { enabled: true, name: 'requestCode' } }), unique('contextCode')),
  notifyProvider: model(Object.assign({}, scoped(), identity('providerCode', 'Provider-neutral sender registration'), { label: { type: 'string', required: true }, adapterService: { type: 'string', required: true }, supportedChannels: { type: 'array', required: true }, supportedScenarios: { type: 'array', required: false }, capabilities: { type: 'object', required: true }, maturity: { type: 'string', required: true }, sandboxSupported: { type: 'bool', required: true }, productionReady: { type: 'bool', required: true }, idempotencySupported: { type: 'bool', required: true }, webhookSupported: { type: 'bool', required: true }, rateLimits: { type: 'object', required: false }, retryableErrorCodes: { type: 'array', required: false }, nonRetryableErrorCodes: { type: 'array', required: false }, timeoutMs: { type: 'int', required: true }, healthStatus: { type: 'string', required: true, default: 'UNKNOWN' }, lastOutcomeCode: { type: 'string', required: false }, status: { type: 'string', required: true, default: 'DRAFT' }, version: { type: 'int', required: true, default: 1 } }), commonIndexes, unique('providerCode')),
  notifyProviderAccount: model(Object.assign({}, scoped(), identity('providerAccountCode', 'Scoped provider account identity'), { providerCode: { type: 'string', required: true, searchOptions: { enabled: true } }, channelCodes: { type: 'array', required: true }, environment: { type: 'string', required: true }, senderIdentity: { type: 'string', required: false }, secretReference: { type: 'string', required: false, description: 'Reference only; raw credentials are prohibited' }, configurationReference: { type: 'string', required: false }, priority: { type: 'int', required: true }, fallbackProviderAccountCodes: { type: 'array', required: false }, status: { type: 'string', required: true, default: 'DRAFT' }, version: { type: 'int', required: true, default: 1 }, updatedByPrincipalId: { type: 'string', required: false }, approvalEvidence: { type: 'object', required: false } }), Object.assign({}, commonIndexes, { providerCode: { enabled: true, name: 'providerCode' } }), unique('providerAccountCode')),
  notifyDeliveryRequest: model(Object.assign({}, scoped(), identity('requestCode', 'Immutable idempotent delivery request identity'), { idempotencyKey: { type: 'string', required: true, searchOptions: { enabled: true } }, scenarioCode: { type: 'string', required: true, searchOptions: { enabled: true } }, channelCode: { type: 'string', required: true, searchOptions: { enabled: true } }, messageTypeCode: { type: 'string', required: true }, templateCode: { type: 'string', required: true }, templateVersionCode: { type: 'string', required: true }, contextCode: { type: 'string', required: true }, recipientType: { type: 'string', required: true }, recipientReference: { type: 'string', required: true, description: 'Owner reference, not raw recipient destination' }, maskedRecipient: { type: 'string', required: true }, locale: { type: 'string', required: true }, correlationId: { type: 'string', required: true, searchOptions: { enabled: true } }, ownerModule: { type: 'string', required: true }, ownerReferenceType: { type: 'string', required: false }, ownerReferenceCode: { type: 'string', required: false }, workflowCarrierCode: { type: 'string', required: false }, testSend: { type: 'bool', required: true, default: false }, status: { type: 'string', required: true, default: 'REQUESTED', searchOptions: { enabled: true } }, retryCount: { type: 'int', required: true, default: 0 }, providerAccountCode: { type: 'string', required: false }, renderedEvidence: { type: 'object', required: false, description: 'Hash, lengths, and field names only; resolved sensitive content is prohibited' }, requestedAt: { type: 'date', required: true }, terminalAt: { type: 'date', required: false }, expiresAt: { type: 'date', required: false } }), Object.assign({}, commonIndexes, { scenarioCode: { enabled: true, name: 'scenarioCode' }, channelCode: { enabled: true, name: 'channelCode' }, correlationId: { enabled: true, name: 'correlationId' } }), Object.assign({}, unique('requestCode'), unique('idempotencyKey'))),
  notifyDeliveryAttempt: model(Object.assign({}, scoped(), identity('attemptCode', 'One immutable provider attempt identity'), { requestCode: { type: 'string', required: true, searchOptions: { enabled: true } }, providerCode: { type: 'string', required: true }, providerAccountCode: { type: 'string', required: true }, attemptNumber: { type: 'int', required: true }, idempotencyKey: { type: 'string', required: true }, status: { type: 'string', required: true, searchOptions: { enabled: true } }, providerMessageReference: { type: 'string', required: false }, normalizedResultCode: { type: 'string', required: false }, failureCode: { type: 'string', required: false }, retryable: { type: 'bool', required: false }, latencyMs: { type: 'int', required: false }, startedAt: { type: 'date', required: true }, completedAt: { type: 'date', required: false }, safeEvidence: { type: 'object', required: false, description: 'Normalized bounded provider evidence only' } }), Object.assign({}, commonIndexes, { requestCode: { enabled: true, name: 'requestCode' }, providerCode: { enabled: true, name: 'providerCode' } }), unique('attemptCode')),
  notifyDeliverySuppression: model(Object.assign({}, scoped(), identity('suppressionCode', 'Immutable denied-delivery evidence'), { requestCode: { type: 'string', required: true, searchOptions: { enabled: true } }, scenarioCode: { type: 'string', required: true }, channelCode: { type: 'string', required: true }, messageTypeCode: { type: 'string', required: true }, recipientReference: { type: 'string', required: true }, maskedRecipient: { type: 'string', required: true }, reasonCode: { type: 'string', required: true }, policyCode: { type: 'string', required: false }, consentEvidenceCode: { type: 'string', required: false }, suppressedAt: { type: 'date', required: true }, status: { type: 'string', required: true, default: 'SUPPRESSED' } }), Object.assign({}, commonIndexes, { requestCode: { enabled: true, name: 'requestCode' } }), unique('suppressionCode')),
  notifyVerificationChallenge: model(Object.assign({}, scoped(), identity('challengeCode', 'Business verification journey identity'), { challengeType: { type: 'string', required: true }, mode: { type: 'string', required: true, description: 'NODICS_OTP or configured provider-managed verification' }, scenarioCode: { type: 'string', required: true }, channelCode: { type: 'string', required: true }, subjectType: { type: 'string', required: true }, subjectReference: { type: 'string', required: true }, recipientReference: { type: 'string', required: true }, maskedRecipient: { type: 'string', required: true }, otpKeyReference: { type: 'string', required: false }, deliveryRequestCode: { type: 'string', required: false }, correlationId: { type: 'string', required: true }, status: { type: 'string', required: true, default: 'CREATED', searchOptions: { enabled: true } }, attemptCount: { type: 'int', required: true, default: 0 }, resendCount: { type: 'int', required: true, default: 0 }, createdAt: { type: 'date', required: true }, expiresAt: { type: 'date', required: true }, verifiedAt: { type: 'date', required: false }, failureCode: { type: 'string', required: false } }), Object.assign({}, commonIndexes, { correlationId: { enabled: true, name: 'correlationId' } }), unique('challengeCode')),
  notifyInAppNotification: model(Object.assign({}, scoped(), identity('notificationCode', 'Persistence-backed in-app inbox identity'), { requestCode: { type: 'string', required: true }, recipientReference: { type: 'string', required: true, searchOptions: { enabled: true } }, scenarioCode: { type: 'string', required: true }, title: { type: 'string', required: true }, body: { type: 'string', required: true }, priority: { type: 'string', required: true }, groupCode: { type: 'string', required: false }, actionDefinitions: { type: 'array', required: false }, actionState: { type: 'object', required: false }, status: { type: 'string', required: true, default: 'UNREAD', searchOptions: { enabled: true } }, deliveredAt: { type: 'date', required: true }, readAt: { type: 'date', required: false }, expiresAt: { type: 'date', required: false }, acknowledgedAt: { type: 'date', required: false } }), Object.assign({}, commonIndexes, { recipientReference: { enabled: true, name: 'recipientReference' } }), unique('notificationCode')),
} };
