/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */

/** @module notifyCore/config/properties @description Configuration-first notification channels, scenarios, governance, rendering, provider selection, resilience, abuse, audit, and extension contracts. @layer configuration @owner notifyCore @override Customer modules may contribute or replace the smallest policy/provider/value-builder key through normal layered configuration. */
module.exports = { backofficeCapabilities: { notifyCore: { enabled: true, capabilityId: 'notifications-messaging', displayName: 'Notifications & Messaging', category: 'operations', icon: 'notifications', contractVersion: 1, minimumClientContractVersion: 1, roles: ['FUNCTIONAL_CAPABILITY_PROVIDER'], discovery: { openApiPath: '/nodics/system/v0/contract/openapi/internal', contractVersion: 1 }, requiredPermissions: ['notify.backoffice.read'], navigation: [
  { id: 'notify-templates', label: 'Templates', route: '/notifications/templates', icon: 'notifications', order: 700, group: { id: 'operations', label: 'Operations', order: 400 }, perspectives: ['operations', 'security', 'commerce'], contexts: ['environment', 'tenant', 'enterprise'], featureState: 'ACTIVE', requiredPermissions: ['notify.backoffice.read'], workbenchTarget: { moduleName: 'notifySchema', schemaName: 'notifyTemplate' }, lifecycleActions: [
    { id: 'preview', label: 'Preview', intent: 'VALIDATE', featureState: 'ACTIVE', permission: 'notify.template.preview', ownerModule: 'notifyApi', operationRoute: '/nodics/notifyApi/v0/operations/templates/preview', inputFields: [{ name: 'sampleValues', label: 'Safe sample values', type: 'JSON', required: false }] },
    { id: 'publish', label: 'Publish', intent: 'APPROVE', featureState: 'ACTIVE', permission: 'notify.template.publish', ownerModule: 'notifyApi', operationRoute: '/nodics/notifyApi/v0/operations/templates/publish', inputFields: [{ name: 'expectedVersion', label: 'Expected version', type: 'TEXT', required: true }, { name: 'approvalEvidence', label: 'Workflow approval evidence', type: 'JSON', required: false }] },
    { id: 'rollback', label: 'Rollback', intent: 'RECONCILE', featureState: 'ACTIVE', permission: 'notify.template.rollback', ownerModule: 'notifyApi', operationRoute: '/nodics/notifyApi/v0/operations/templates/rollback', inputFields: [{ name: 'targetTemplateVersionCode', label: 'Target version code', type: 'TEXT', required: true }, { name: 'reason', label: 'Reason', type: 'MULTILINE', required: true }, { name: 'expectedVersion', label: 'Expected version', type: 'TEXT', required: true }] },
  ], help: { summary: 'Browse and govern centralized message templates by channel and scenario.', documentationRoute: '/docs/capabilities/notifications' } },
  { id: 'notify-scenarios', parentId: 'notify-templates', label: 'Scenarios', route: '/notifications/scenarios', icon: 'notifications', order: 701, perspectives: ['operations'], contexts: ['tenant', 'enterprise'], featureState: 'ACTIVE', requiredPermissions: ['notify.backoffice.read'], workbenchTarget: { moduleName: 'notifySchema', schemaName: 'notifyScenario' } },
  { id: 'notify-channels', parentId: 'notify-templates', label: 'Channels', route: '/notifications/channels', icon: 'notifications', order: 702, perspectives: ['operations'], contexts: ['tenant', 'enterprise'], featureState: 'ACTIVE', requiredPermissions: ['notify.backoffice.read'], workbenchTarget: { moduleName: 'notifySchema', schemaName: 'notifyChannel' } },
  { id: 'notify-types', parentId: 'notify-templates', label: 'Message Types', route: '/notifications/message-types', icon: 'policy', order: 703, perspectives: ['security'], contexts: ['tenant', 'enterprise'], featureState: 'ACTIVE', requiredPermissions: ['notify.backoffice.read'], workbenchTarget: { moduleName: 'notifySchema', schemaName: 'notifyMessageType' } },
  { id: 'notify-policies', parentId: 'notify-templates', label: 'Policies', route: '/notifications/policies', icon: 'policy', order: 704, perspectives: ['security'], contexts: ['tenant', 'enterprise'], featureState: 'ACTIVE', requiredPermissions: ['notify.backoffice.read'], workbenchTarget: { moduleName: 'notifySchema', schemaName: 'notifyDeliveryPolicy' }, help: { summary: 'Govern layered scenario, channel, consent, quiet-hour, retry, fallback, provider, and rate policy.', documentationRoute: '/docs/capabilities/notifications/configuration' } },
  { id: 'notify-providers', parentId: 'notify-templates', label: 'Providers', route: '/notifications/providers', icon: 'cloud', order: 704, perspectives: ['operations'], contexts: ['environment', 'tenant', 'enterprise'], featureState: 'ACTIVE', requiredPermissions: ['notify.backoffice.read'], workbenchTarget: { moduleName: 'notifySchema', schemaName: 'notifyProvider' } },
  { id: 'notify-accounts', parentId: 'notify-providers', label: 'Provider Accounts', route: '/notifications/provider-accounts', icon: 'key', order: 705, perspectives: ['security'], contexts: ['environment', 'tenant', 'enterprise'], featureState: 'ACTIVE', requiredPermissions: ['notify.backoffice.read'], workbenchTarget: { moduleName: 'notifySchema', schemaName: 'notifyProviderAccount' } },
  { id: 'notify-deliveries', parentId: 'notify-templates', label: 'Delivery Logs', route: '/notifications/delivery-logs', icon: 'receipt_long', order: 706, perspectives: ['operations'], contexts: ['tenant', 'enterprise'], featureState: 'ACTIVE', requiredPermissions: ['notify.backoffice.read'], workbenchTarget: { moduleName: 'notifySchema', schemaName: 'notifyDeliveryRequest' } },
  { id: 'notify-attempts', parentId: 'notify-deliveries', label: 'Delivery Attempts', route: '/notifications/delivery-attempts', icon: 'history', order: 707, perspectives: ['operations'], contexts: ['tenant', 'enterprise'], featureState: 'ACTIVE', requiredPermissions: ['notify.backoffice.read'], workbenchTarget: { moduleName: 'notifySchema', schemaName: 'notifyDeliveryAttempt' } },
  { id: 'notify-suppressions', parentId: 'notify-deliveries', label: 'Suppressions', route: '/notifications/suppressions', icon: 'block', order: 708, perspectives: ['security'], contexts: ['tenant', 'enterprise'], featureState: 'ACTIVE', requiredPermissions: ['notify.backoffice.read'], workbenchTarget: { moduleName: 'notifySchema', schemaName: 'notifyDeliverySuppression' } },
  { id: 'notify-verification', parentId: 'notify-templates', label: 'Verification', route: '/notifications/verification', icon: 'verified', order: 709, perspectives: ['security'], contexts: ['tenant', 'enterprise'], featureState: 'ACTIVE', requiredPermissions: ['notify.backoffice.read'], workbenchTarget: { moduleName: 'notifySchema', schemaName: 'notifyVerificationChallenge' } },
  { id: 'notify-in-app', parentId: 'notify-templates', label: 'In-App Inbox', route: '/notifications/in-app', icon: 'inbox', order: 710, perspectives: ['operations'], contexts: ['tenant', 'enterprise'], featureState: 'ACTIVE', requiredPermissions: ['notify.backoffice.read'], workbenchTarget: { moduleName: 'notifySchema', schemaName: 'notifyInAppNotification' } },
  { id: 'notify-test-console', parentId: 'notify-templates', label: 'Test Console', route: '/notifications/test-console', icon: 'science', order: 711, perspectives: ['operations'], contexts: ['environment', 'tenant', 'enterprise'], featureState: 'ACTIVE', requiredPermissions: ['notify.test.send'], workbenchTarget: { moduleName: 'notifySchema', schemaName: 'notifyTemplate' }, lifecycleActions: [{ id: 'test-send', label: 'Send sandbox test', intent: 'TEST', permission: 'notify.test.send', ownerModule: 'notifyApi', operationRoute: '/nodics/notifyApi/v0/operations/test-send', targetStatuses: ['ACTIVE'], order: 10, inputFields: [{ name: 'scenarioCode', label: 'Scenario', type: 'TEXT', required: true }, { name: 'channelCode', label: 'Channel', type: 'SELECT', required: true, options: ['email', 'sms', 'inApp'] }, { name: 'messageTypeCode', label: 'Message type', type: 'TEXT', required: true }, { name: 'recipientReference', label: 'Allowlisted test recipient', type: 'TEXT', required: true }, { name: 'maskedRecipient', label: 'Masked recipient', type: 'TEXT', required: true }, { name: 'values', label: 'Safe sample values', type: 'JSON', required: false }] }], help: { summary: 'Execute an allowlisted non-production test through the full delivery lifecycle.', documentationRoute: '/docs/capabilities/notifications/operations' } },
] } }, notify: {
  contractVersion: 1,
  lifecycle: { templateStates: ['DRAFT', 'PENDING_APPROVAL', 'ACTIVE', 'RETIRED', 'ARCHIVED'], providerStates: ['DRAFT', 'PENDING_APPROVAL', 'ACTIVE', 'SUSPENDED', 'RETIRED'], deliveryStates: ['REQUESTED', 'RESOLVING', 'SUPPRESSED', 'SENDING', 'SENT', 'DELIVERED', 'FAILED', 'RETRY_SCHEDULED', 'BOUNCED', 'ACKNOWLEDGED', 'EXPIRED'], makerCheckerRequired: true, highRiskApprovalOnly: true },
  content: { supportedFormats: ['TEXT', 'HTML', 'JSON_BLOCKS', 'PROVIDER_TEMPLATE_ID'], initialFormats: ['TEXT', 'HTML', 'PROVIDER_TEMPLATE_ID'], markdownEnabled: false, mjmlEnabled: false, arbitraryHtmlEnabled: false, maximumTemplateBytes: 262144, maximumVariables: 100, maximumAttachments: 10 },
  channels: {
    email: { contentFields: ['subject', 'plainTextBody', 'htmlBody', 'attachments', 'unsubscribeFooter'], supportedContentTypes: ['TEXT', 'HTML'], maximumSubjectLength: 998, maximumBodyBytes: 262144, attachmentsAllowed: true, safePreview: true, defaultRetentionDays: 90 },
    sms: { contentFields: ['text', 'senderId'], supportedContentTypes: ['TEXT'], maximumCharacters: 1600, unicodeAllowed: true, maximumSegments: 10, linkShorteningAllowed: false, safePreview: true, defaultRetentionDays: 30 },
    whatsapp: { contentFields: ['approvedTemplateId', 'body', 'mediaHeader', 'quickReplies'], supportedContentTypes: ['TEXT', 'PROVIDER_TEMPLATE_ID'], maximumBodyCharacters: 4096, providerApprovalRequired: true, safePreview: true, defaultRetentionDays: 30 },
    telegram: { contentFields: ['text', 'media', 'actionButtons'], supportedContentTypes: ['TEXT'], maximumCharacters: 4096, safePreview: true, defaultRetentionDays: 30 },
    push: { contentFields: ['title', 'body', 'image', 'deepLink', 'payload'], supportedContentTypes: ['TEXT', 'JSON_BLOCKS'], maximumPayloadBytes: 4096, safePreview: true, defaultRetentionDays: 30 },
    inApp: { contentFields: ['title', 'body', 'priority', 'groupCode', 'actionButtons'], supportedContentTypes: ['TEXT', 'JSON_BLOCKS'], maximumBodyBytes: 32768, persistenceBacked: true, readState: true, expiration: true, actionState: true, safePreview: true, defaultRetentionDays: 90 },
  },
  scenarios: {
    otpVerification: { ownerModule: 'notifyVerification', defaultAudience: ['SUBJECT'], requiredVariables: ['otpCode', 'expiryMinutes', 'brandName', 'supportContact'], allowedChannels: ['email', 'sms'], allowedMessageTypes: ['verification'], riskLevel: 'HIGH', policyCodes: ['OTP_ABUSE_POLICY'], documentationRoute: '/docs/capabilities/notifications/verification' },
    orderConfirmation: { ownerModule: 'order', defaultAudience: ['CUSTOMER'], requiredVariables: ['customerName', 'orderCode', 'orderTotal', 'deliveryAddressSummary', 'estimatedDeliveryDate', 'orderDetailsUrl', 'supportContact'], allowedChannels: ['email', 'sms', 'inApp'], allowedMessageTypes: ['transactional'], riskLevel: 'LOW', documentationRoute: '/docs/capabilities/notifications/commerce' },
    refundApproval: { ownerModule: 'order', defaultAudience: ['APPROVER'], requiredVariables: ['approverName', 'refundRequestCode', 'orderCode', 'refundAmount', 'reason', 'riskLevel', 'approvalUrl'], allowedChannels: ['email', 'inApp'], allowedMessageTypes: ['workflow', 'transactional'], riskLevel: 'HIGH', documentationRoute: '/docs/capabilities/notifications/commerce' },
    shipmentUpdate: { ownerModule: 'fulfillment', defaultAudience: ['CUSTOMER'], requiredVariables: ['customerName', 'orderCode', 'shipmentCode', 'shipmentStatus', 'trackingUrl'], allowedChannels: ['email', 'sms', 'whatsapp', 'push', 'inApp'], allowedMessageTypes: ['transactional'], riskLevel: 'LOW', documentationRoute: '/docs/capabilities/notifications/commerce' },
    deliveryFailure: { ownerModule: 'notifyCore', defaultAudience: ['OPERATOR'], requiredVariables: ['requestCode', 'scenarioCode', 'providerCode', 'failureCode', 'operationsUrl'], allowedChannels: ['email', 'inApp'], allowedMessageTypes: ['operational'], riskLevel: 'MEDIUM', documentationRoute: '/docs/capabilities/notifications/operations' },
    kycVerification: { ownerModule: 'kyc', defaultAudience: ['SUBJECT'], requiredVariables: ['otpCode', 'expiryMinutes', 'brandName', 'supportContact'], allowedChannels: ['email', 'sms'], allowedMessageTypes: ['verification'], riskLevel: 'HIGH', documentationRoute: '/docs/capabilities/notifications/verification' },
    passwordReset: { ownerModule: 'profile', defaultAudience: ['SUBJECT'], requiredVariables: ['otpCode', 'expiryMinutes', 'brandName', 'supportContact'], allowedChannels: ['email', 'sms'], allowedMessageTypes: ['security'], riskLevel: 'CRITICAL', documentationRoute: '/docs/capabilities/notifications/verification' },
    workflowTaskAssigned: { ownerModule: 'workflow', defaultAudience: ['ASSIGNEE'], requiredVariables: ['taskCode', 'taskLabel', 'assignedAt', 'taskUrl'], allowedChannels: ['email', 'push', 'inApp'], allowedMessageTypes: ['workflow'], riskLevel: 'MEDIUM', documentationRoute: '/docs/capabilities/notifications/workflow' },
    supportEscalation: { ownerModule: 'order', defaultAudience: ['SUPPORT'], requiredVariables: ['requestCode', 'orderCode', 'reason', 'taskUrl'], allowedChannels: ['email', 'inApp'], allowedMessageTypes: ['operational', 'workflow'], riskLevel: 'MEDIUM', documentationRoute: '/docs/capabilities/notifications/commerce' },
  },
  messageTypes: {
    transactional: { consentRequired: false, approvalRequired: false, riskLevel: 'LOW', retentionDays: 90, auditMode: 'FULL_SAFE_EVIDENCE', retryPolicyCode: 'STANDARD_RETRY' },
    verification: { consentRequired: false, approvalRequired: true, riskLevel: 'HIGH', retentionDays: 30, auditMode: 'REFERENCE_ONLY', retryPolicyCode: 'SENSITIVE_RETRY', recipientRestrictions: ['SUBJECT_ONLY'] },
    marketing: { consentRequired: true, approvalRequired: true, riskLevel: 'HIGH', retentionDays: 365, auditMode: 'FULL_SAFE_EVIDENCE', retryPolicyCode: 'MARKETING_RETRY' },
    operational: { consentRequired: false, approvalRequired: false, riskLevel: 'MEDIUM', retentionDays: 90, auditMode: 'FULL_SAFE_EVIDENCE', retryPolicyCode: 'STANDARD_RETRY' },
    workflow: { consentRequired: false, approvalRequired: false, riskLevel: 'MEDIUM', retentionDays: 90, auditMode: 'FULL_SAFE_EVIDENCE', retryPolicyCode: 'STANDARD_RETRY' },
    security: { consentRequired: false, approvalRequired: true, riskLevel: 'CRITICAL', retentionDays: 90, auditMode: 'REFERENCE_ONLY', retryPolicyCode: 'SENSITIVE_RETRY', recipientRestrictions: ['SUBJECT_ONLY'] },
  },
  rendering: { placeholderPattern: '\\{\\{([A-Za-z][A-Za-z0-9._-]{0,127})\\}\\}', maximumDepth: 4, localeFallbacks: { 'en-AE': ['en', 'default'], en: ['default'] }, forbiddenKeys: ['password', 'token', 'credential', 'secret', 'cvv', 'pan', 'providerPayload', 'rawPayload'], protectedVariableCodes: ['otpCode', 'passwordResetToken'], previewProtectedSamples: { otpCode: '123456', passwordResetToken: 'sample-token' }, evidenceHashAlgorithm: 'sha256' },
  consent: { providerService: 'DefaultNotifyConsentEvidenceProviderService', failClosed: true, essentialMessageTypes: ['transactional', 'verification', 'operational', 'workflow', 'security'] },
  policy: { service: 'DefaultNotifyPolicyService', allowedRequesterTokenTypes: ['access', 'service'], maximumRecipients: 100, testRecipientPolicy: 'ALLOWLIST_ONLY', productionArbitraryDestinationAllowed: false, highRiskManualResendRequiresWorkflow: true },
  providerSelection: { providersByChannel: { email: ['localNotify'], sms: ['localNotify'], whatsapp: ['localNotify'], telegram: ['localNotify'], push: ['localNotify'], inApp: ['localNotify'] }, bootstrapProviders: { localNotify: { providerCode: 'localNotify', adapterService: 'DefaultLocalNotifyProviderAdapterService', supportedChannels: ['email', 'sms', 'whatsapp', 'telegram', 'push', 'inApp'], healthStatus: 'UP', status: 'ACTIVE', productionReady: false } }, bootstrapAccounts: { localNotify: { providerAccountCode: 'localNotify-default', providerCode: 'localNotify', channelCodes: ['email', 'sms', 'whatsapp', 'telegram', 'push', 'inApp'], priority: 100, environment: 'local', status: 'ACTIVE' } }, allowBootstrapAccounts: true, accountService: 'DefaultNotifyProviderAccountService', healthService: 'DefaultNotifyProviderHealthService', failClosed: true },
  resilience: { timeoutMs: 10000, circuitBreakerFailureThreshold: 5, circuitBreakerResetMs: 60000, retryPolicies: { STANDARD_RETRY: { maximumAttempts: 3, delaysMs: [1000, 5000], fallbackAllowed: true }, SENSITIVE_RETRY: { maximumAttempts: 2, delaysMs: [30000], fallbackAllowed: false }, MARKETING_RETRY: { maximumAttempts: 1, delaysMs: [], fallbackAllowed: false } }, retryableFailureCodes: ['TIMEOUT', 'RATE_LIMITED', 'TEMPORARY_PROVIDER_FAILURE'], nonRetryableFailureCodes: ['INVALID_DESTINATION', 'CONSENT_DENIED', 'TEMPLATE_REJECTED', 'AUTHENTICATION_FAILED'] },
  abuse: { windowMs: 60000, maximumRequestsPerPrincipalRecipientScenario: 5, otpCooldownMs: 30000, otpMaximumResends: 3, otpMaximumValidationAttempts: 5, suspiciousDestinationPatterns: [], rateLimitService: 'DefaultNotifyRateLimitService' },
  persistence: { mutationFlag: '_notifyMutationAuthorized', maximumScanRecords: 500, hardDeleteAllowed: false },
  audit: { eventPrefix: 'notify.delivery', maximumSafeEvidenceBytes: 65536, maximumCorrelationReferences: 50, forbiddenEvidenceKeys: ['resolvedContent', 'otpCode', 'password', 'token', 'credential', 'secret', 'recipient', 'providerPayload', 'rawPayload'] },
  testSend: { enabled: true, environmentAllowlist: ['local', 'dev', 'test'], approvedRecipientReferences: ['test-email', 'test-mobile', 'test-inapp'], maximumPerMinute: 10 },
  verification: { modes: ['NODICS_OTP', 'PROVIDER_MANAGED'], defaultMode: 'NODICS_OTP', providerManagedEnabled: false, otpService: 'DefaultOtpService', expirySeconds: 300, attemptLimit: 5, singleUseToken: true },
} };
