/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is the confidential and proprietary information of Nodics ("Confidential Information").
    You shall not disclose such Confidential Information and shall use it only in accordance with the
    terms of the license agreement you entered into with Nodics.

 */

/** @module product/foundation/DefaultProductVariantService @description Validates Product variant axes, base-to-variant graphs, and canonical combinations by composing existing Product Item, Attribute Definition, and Attribute Value authorities. @layer service @owner product */
module.exports = {
    /** Initializes Product variant validation. */ init: function () { return Promise.resolve(true); },
    /** Completes Product variant initialization. */ postInit: function () { return Promise.resolve(true); },
    /** Returns layered variant policy. */ policy: function () { return (CONFIG.get('product') || {}).variant || {}; },
    /** Creates a stable Product error. */ error: function (code, message) { return SERVICE.DefaultProductEnterpriseScopeService.error(code, message); },
    /** Extracts generated-service result items. */ items: function (response) { return response && Array.isArray(response.result) ? response.result : []; },
    /** Loads exactly one non-retired Product Item. */ loadItem: async function (model, typeProperty, codeProperty, request) { let response = await SERVICE.DefaultProductItemService.get({ tenant: request.tenant, authData: request.authData, query: { enterpriseCode: model.enterpriseCode, catalogCode: model.catalogCode, itemType: model[typeProperty], itemCode: model[codeProperty] }, searchOptions: { limit: 2 } }), items = this.items(response); return items.length === 1 && items[0].status !== 'RETIRED' ? items[0] : undefined; },
    /** Loads exactly one non-retired Attribute Definition. */ loadDefinition: async function (model, request) { let response = await SERVICE.DefaultProductAttributeDefinitionService.get({ tenant: request.tenant, authData: request.authData, query: { enterpriseCode: model.enterpriseCode, catalogCode: model.catalogCode, attributeCode: model.attributeCode }, searchOptions: { limit: 2 } }), items = this.items(response); return items.length === 1 && items[0].status !== 'RETIRED' ? items[0] : undefined; },
    /** Validates and scopes one variant axis using an existing single-valued Attribute Definition. */ prepareAxis: async function (request) {
        let model = request.model || {}, policy = this.policy();
        SERVICE.DefaultProductEnterpriseScopeService.scopeNewModel(request, 'variantAxis', ['catalogCode', 'axisCode']); model = request.model;
        if (!(policy.baseItemTypes || []).includes(model.baseItemType) || !(policy.statuses || []).includes(model.status || 'DRAFT') || !Number.isInteger(Number(model.position)) || Number(model.position) < 0) throw this.error('ERR_PRODUCT_00028', 'Variant axis identity, type, position, or status is invalid');
        await SERVICE.DefaultProductReferenceService.validate('catalog', model.catalogCode, request);
        let base = await this.loadItem(model, 'baseItemType', 'baseItemCode', request), definition = await this.loadDefinition(model, request);
        if (!base || !definition || definition.localized || definition.multiValued || !(policy.axisValueTypes || []).includes(definition.valueType) || (model.status || 'DRAFT') === 'ACTIVE' && (base.status !== 'ACTIVE' || definition.status !== 'ACTIVE')) throw this.error('ERR_PRODUCT_00028', 'Variant axis requires available base Item and non-localized single-valued Attribute Definition');
        let response = await SERVICE.DefaultProductVariantAxisService.get({ tenant: request.tenant, authData: request.authData, query: { enterpriseCode: model.enterpriseCode, catalogCode: model.catalogCode, baseItemType: model.baseItemType, baseItemCode: model.baseItemCode, status: { $ne: 'RETIRED' } }, searchOptions: { limit: Number(policy.maximumAxesPerBase || 20) + 1 } }), axes = this.items(response).filter(item => item.code !== model.code);
        if (axes.length >= Number(policy.maximumAxesPerBase || 20) || axes.some(item => item.attributeCode === model.attributeCode || Number(item.position) === Number(model.position))) throw this.error('ERR_PRODUCT_00029', 'Variant axis limit, Attribute, or position conflicts with an existing axis');
        return model;
    },
    /** Loads active axes for one base Item in deterministic order. */ loadAxes: async function (model, request) { let response = await SERVICE.DefaultProductVariantAxisService.get({ tenant: request.tenant, authData: request.authData, query: { enterpriseCode: model.enterpriseCode, catalogCode: model.catalogCode, baseItemType: model.baseItemType, baseItemCode: model.baseItemCode, status: 'ACTIVE' }, searchOptions: { limit: Number(this.policy().maximumAxesPerBase || 20), sort: { position: 1, axisCode: 1 } } }); return this.items(response).sort((left, right) => Number(left.position) - Number(right.position) || left.axisCode.localeCompare(right.axisCode)); },
    /** Proves that adding a base-to-variant edge remains bounded and acyclic. */ assertGraph: async function (model, request) { let target = model.baseItemType + '::' + model.baseItemCode, queue = [{ type: model.variantItemType, code: model.variantItemCode, depth: 0 }], visited = new Set(), maximumDepth = Number(this.policy().maximumHierarchyDepth || 8); while (queue.length) { let current = queue.shift(), key = current.type + '::' + current.code; if (key === target) throw this.error('ERR_PRODUCT_00029', 'Variant assignment creates a cycle'); if (visited.has(key)) continue; visited.add(key); if (current.depth >= maximumDepth) throw this.error('ERR_PRODUCT_00029', 'Variant hierarchy exceeds configured depth'); let response = await SERVICE.DefaultProductVariantAssignmentService.get({ tenant: request.tenant, authData: request.authData, query: { enterpriseCode: model.enterpriseCode, catalogCode: model.catalogCode, baseItemType: current.type, baseItemCode: current.code, status: { $ne: 'RETIRED' } }, searchOptions: { limit: Number(this.policy().maximumVariantsPerBase || 10000) + 1 } }); this.items(response).forEach(item => queue.push({ type: item.variantItemType, code: item.variantItemCode, depth: current.depth + 1 })); } return true; },
    /** Converts an existing typed Attribute Value into a stable semantic axis value. */ canonicalValue: function (value) { let fields = ['stringValue', 'booleanValue', 'integerValue', 'decimalValue', 'dateValue', 'referenceType', 'referenceItemType', 'referenceCode', 'unitCode'], parts = fields.filter(field => value[field] !== undefined && value[field] !== null).map(field => field + ':' + String(value[field])); return parts.join('|'); },
    /** Validates axis/value pairs and derives the canonical semantic combination key. */ prepareCombination: async function (model, axes, request) { let pairs = model.axisValues; if (!Array.isArray(pairs) || !pairs.length || pairs.some(pair => !pair || typeof pair !== 'object' || Array.isArray(pair) || typeof pair.axisCode !== 'string' || typeof pair.valueCode !== 'string' || Object.keys(pair).some(key => !['axisCode', 'valueCode'].includes(key)))) throw this.error('ERR_PRODUCT_00029', 'Variant axis values are invalid'); let byAxis = new Map(axes.map(axis => [axis.axisCode, axis])); if (new Set(pairs.map(pair => pair.axisCode)).size !== pairs.length || pairs.some(pair => !byAxis.has(pair.axisCode)) || axes.some(axis => axis.required && !pairs.some(pair => pair.axisCode === axis.axisCode))) throw this.error('ERR_PRODUCT_00029', 'Variant axis coverage is invalid'); let resolved = {}; for (let pair of pairs) { let axis = byAxis.get(pair.axisCode), response = await SERVICE.DefaultProductAttributeValueService.get({ tenant: request.tenant, authData: request.authData, query: { enterpriseCode: model.enterpriseCode, catalogCode: model.catalogCode, valueCode: pair.valueCode, itemType: model.variantItemType, itemCode: model.variantItemCode, attributeCode: axis.attributeCode }, searchOptions: { limit: 2 } }), values = this.items(response); if (values.length !== 1 || values[0].status === 'RETIRED' || (model.status || 'DRAFT') === 'ACTIVE' && values[0].status !== 'ACTIVE') throw this.error('ERR_PRODUCT_00029', 'Variant axis value does not belong to the variant Item and axis Attribute'); resolved[pair.axisCode] = this.canonicalValue(values[0]); if (!resolved[pair.axisCode]) throw this.error('ERR_PRODUCT_00029', 'Variant axis value has no canonical typed content'); }
        model.axisValues = pairs.slice().sort((left, right) => left.axisCode.localeCompare(right.axisCode)); model.combinationKey = model.axisValues.map(pair => encodeURIComponent(pair.axisCode) + '=' + encodeURIComponent(resolved[pair.axisCode])).join('&'); return model.combinationKey; },
    /** Validates and scopes one base-to-sellable-variant assignment. */ prepareAssignment: async function (request) {
        let model = request.model || {}, policy = this.policy();
        SERVICE.DefaultProductEnterpriseScopeService.scopeNewModel(request, 'variantAssignment', ['catalogCode', 'assignmentCode']); model = request.model;
        if (!(policy.baseItemTypes || []).includes(model.baseItemType) || !(policy.variantItemTypes || []).includes(model.variantItemType) || !(policy.statuses || []).includes(model.status || 'DRAFT') || model.baseItemType === model.variantItemType && model.baseItemCode === model.variantItemCode) throw this.error('ERR_PRODUCT_00029', 'Variant assignment identity, item types, or status is invalid');
        await SERVICE.DefaultProductReferenceService.validate('catalog', model.catalogCode, request);
        let base = await this.loadItem(model, 'baseItemType', 'baseItemCode', request), variant = await this.loadItem(model, 'variantItemType', 'variantItemCode', request);
        if (!base || !variant || policy.requireSellableVariant && !variant.sellable || (model.status || 'DRAFT') === 'ACTIVE' && (base.status !== 'ACTIVE' || variant.status !== 'ACTIVE')) throw this.error('ERR_PRODUCT_00029', 'Base or sellable variant Product Item is unavailable');
        let axes = await this.loadAxes(model, request); if (!axes.length) throw this.error('ERR_PRODUCT_00029', 'Base Product Item has no active variant axes'); await this.prepareCombination(model, axes, request); await this.assertGraph(model, request);
        let response = await SERVICE.DefaultProductVariantAssignmentService.get({ tenant: request.tenant, authData: request.authData, query: { enterpriseCode: model.enterpriseCode, catalogCode: model.catalogCode, baseItemType: model.baseItemType, baseItemCode: model.baseItemCode, status: { $ne: 'RETIRED' } }, searchOptions: { limit: Number(policy.maximumVariantsPerBase || 10000) + 1 } }), assignments = this.items(response).filter(item => item.code !== model.code);
        if (assignments.length >= Number(policy.maximumVariantsPerBase || 10000) || assignments.some(item => item.variantItemType === model.variantItemType && item.variantItemCode === model.variantItemCode || item.combinationKey === model.combinationKey)) throw this.error('ERR_PRODUCT_00029', 'Variant Item or combination already exists for this base Item'); return model;
    },
    /** Rejects axis retirement while non-retired assignments still use it. */ assertAxisRetirable: async function (current, request) { let response = await SERVICE.DefaultProductVariantAssignmentService.get({ tenant: request.tenant, authData: request.authData, query: { enterpriseCode: current.enterpriseCode, catalogCode: current.catalogCode, baseItemType: current.baseItemType, baseItemCode: current.baseItemCode, status: { $ne: 'RETIRED' } }, searchOptions: { limit: Number(this.policy().maximumVariantsPerBase || 10000) + 1 } }); if (this.items(response).some(item => (item.axisValues || []).some(pair => pair.axisCode === current.axisCode))) throw this.error('ERR_PRODUCT_00029', 'Retire dependent variant assignments before the axis'); return true; },
    /** Validates immutable identity and lifecycle on variant updates. */ update: async function (request, serviceName, identities, prepareName, retirementCheck) { await SERVICE.DefaultProductEnterpriseScopeService.scopeQuery(request); let response = await SERVICE[serviceName].get({ tenant: request.tenant, authData: request.authData, query: request.query, searchOptions: { limit: 2 } }), items = this.items(response); if (items.length !== 1) throw this.error('ERR_PRODUCT_00012', 'Variant update target must resolve exactly one record'); let current = items[0], patch = request.model || {}; ['code', 'enterpriseCode'].concat(identities).forEach(property => { if (patch[property] !== undefined && JSON.stringify(patch[property]) !== JSON.stringify(current[property])) throw this.error('ERR_PRODUCT_00011', 'Variant identity or structure is immutable'); }); if (patch.status && patch.status !== current.status) { let allowed = (this.policy().allowedTransitions || {})[current.status] || []; if (!allowed.includes(patch.status)) throw this.error('ERR_PRODUCT_00011', 'Variant lifecycle transition is invalid'); } if (retirementCheck && patch.status === 'RETIRED' && current.status !== 'RETIRED') await this[retirementCheck](current, request); let validationRequest = Object.assign({}, request, { model: Object.assign({}, current, patch) }); await this[prepareName](validationRequest); request.model = patch; return true; },
    /** Validates variant-axis updates. */ prepareAxisUpdate: function (request) { return this.update(request, 'DefaultProductVariantAxisService', ['catalogCode', 'axisCode', 'baseItemType', 'baseItemCode', 'attributeCode'], 'prepareAxis', 'assertAxisRetirable'); },
    /** Validates variant-assignment updates. */ prepareAssignmentUpdate: function (request) { return this.update(request, 'DefaultProductVariantAssignmentService', ['catalogCode', 'assignmentCode', 'baseItemType', 'baseItemCode', 'variantItemType', 'variantItemCode', 'axisValues', 'combinationKey'], 'prepareAssignment'); }
};
