/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is the confidential and proprietary information of Nodics ("Confidential Information").
    You shall not disclose such Confidential Information and shall use it only in accordance with the
    terms of the license agreement you entered into with Nodics.

 */

/** @module product/foundation/DefaultProductClassificationService @description Validates declarative classification classes, typed Product values, localization, cardinality, exact decimals, and Units-owned measurements. @layer service @owner product */
module.exports = {
    /** Initializes classification validation. */ init: function () { return Promise.resolve(true); },
    /** Completes classification initialization. */ postInit: function () { return Promise.resolve(true); },
    /** Returns layered Product policy. */ config: function () { return CONFIG.get('product') || {}; },
    /** Creates a stable Product error. */ error: function (code, message) { return SERVICE.DefaultProductEnterpriseScopeService.error(code, message); },
    /** Extracts result items from a generated-service response. */ items: function (response) { return response && Array.isArray(response.result) ? response.result : []; },
    /** Validates an optional effective-date range. */ assertDates: function (model) { if (model.effectiveFrom && model.effectiveTo && new Date(model.effectiveFrom).getTime() > new Date(model.effectiveTo).getTime()) throw this.error('ERR_PRODUCT_00026', 'Classification effective date range is invalid'); },
    /** Validates a canonical signed exact decimal string. */ exactDecimal: function (value) { let policy = this.config().attribute || {}, text = String(value === undefined ? '' : value); if (!/^-?(0|[1-9][0-9]*)(\.[0-9]+)?$/.test(text)) throw this.error('ERR_PRODUCT_00019', 'Attribute decimal value must be an exact decimal string'); let unsigned = text.replace('-', ''), parts = unsigned.split('.'); if ((parts[0] + (parts[1] || '')).length > Number(policy.maximumDigits || 38) || (parts[1] || '').length > Number(policy.maximumScale || 18)) throw this.error('ERR_PRODUCT_00019', 'Attribute decimal value exceeds configured precision'); return text; },
    /** Loads exactly one non-retired Attribute Definition. */ loadDefinition: async function (model, request) { let response = await SERVICE.DefaultProductAttributeDefinitionService.get({ tenant: request.tenant, authData: request.authData, query: { enterpriseCode: model.enterpriseCode, catalogCode: model.catalogCode, attributeCode: model.attributeCode }, searchOptions: { limit: 2 } }), items = this.items(response); return items.length === 1 && items[0].status !== 'RETIRED' ? items[0] : undefined; },
    /** Loads exactly one non-retired Product Item. */ loadItem: async function (model, request) { let response = await SERVICE.DefaultProductItemService.get({ tenant: request.tenant, authData: request.authData, query: { enterpriseCode: model.enterpriseCode, catalogCode: model.catalogCode, itemType: model.itemType, itemCode: model.itemCode }, searchOptions: { limit: 2 } }), items = this.items(response); return items.length === 1 && items[0].status !== 'RETIRED' ? items[0] : undefined; },
    /** Validates and scopes an Attribute Definition. */ prepareDefinition: async function (request) {
        let model = request.model || {}, policy = this.config().attribute || {};
        SERVICE.DefaultProductEnterpriseScopeService.scopeNewModel(request, 'attributeDefinition', ['catalogCode', 'attributeCode']); model = request.model;
        if (!model.name || typeof model.name !== 'string' || !(policy.valueTypes || []).includes(model.valueType) || !(policy.statuses || []).includes(model.status || 'DRAFT')) throw this.error('ERR_PRODUCT_00018', 'Attribute definition name, type, or status is invalid');
        let minimum = Number(model.minimumValues === undefined ? model.required ? 1 : 0 : model.minimumValues), maximum = Number(model.maximumValues === undefined ? model.multiValued ? policy.maximumValues : 1 : model.maximumValues);
        if (!Number.isInteger(minimum) || !Number.isInteger(maximum) || minimum < 0 || maximum < 1 || minimum > maximum || maximum > Number(policy.maximumValues || 1000) || !model.multiValued && maximum !== 1 || model.required && minimum < 1) throw this.error('ERR_PRODUCT_00018', 'Attribute cardinality definition is invalid');
        model.minimumValues = minimum; model.maximumValues = maximum;
        let values = model.enumerationValues || []; if (!Array.isArray(values) || values.length > Number(policy.maximumEnumValues || 1000) || values.some(value => typeof value !== 'string' || !value.trim()) || new Set(values).size !== values.length || model.valueType === 'ENUM' && !values.length || model.valueType !== 'ENUM' && values.length) throw this.error('ERR_PRODUCT_00018', 'Attribute enumeration definition is invalid');
        if (Boolean(model.unitRequired) !== (model.valueType === 'MEASURED')) throw this.error('ERR_PRODUCT_00018', 'Only measured attributes require a Unit');
        await SERVICE.DefaultProductReferenceService.validate('catalog', model.catalogCode, request); return model;
    },
    /** Validates locale presence according to the Definition. */ validateLocale: function (definition, model) { let pattern = new RegExp(((this.config().attribute || {}).locales || {}).pattern || '^[A-Za-z]{2,3}(?:[-_][A-Za-z0-9]{2,8})*$'); if (definition.localized && (!model.localeCode || !pattern.test(model.localeCode)) || !definition.localized && model.localeCode) throw this.error('ERR_PRODUCT_00019', 'Attribute locale does not match its Definition'); },
    /** Validates exactly the storage fields required by the Definition type. */ validateTypedValue: async function (definition, model, request) {
        let fields = ['stringValue', 'booleanValue', 'integerValue', 'decimalValue', 'dateValue', 'referenceType', 'referenceItemType', 'referenceCode', 'unitCode'], present = fields.filter(field => model[field] !== undefined && model[field] !== null), referenceFields = model.referenceType === 'PRODUCT_ITEM' ? ['referenceType', 'referenceItemType', 'referenceCode'] : ['referenceType', 'referenceCode'], required = { TEXT: ['stringValue'], BOOLEAN: ['booleanValue'], INTEGER: ['integerValue'], DECIMAL: ['decimalValue'], DATE: ['dateValue'], ENUM: ['stringValue'], REFERENCE: referenceFields, MEASURED: ['decimalValue', 'unitCode'] }[definition.valueType] || [];
        if (present.length !== required.length || required.some(field => !present.includes(field))) throw this.error('ERR_PRODUCT_00019', 'Attribute value fields do not match its Definition type');
        let policy = this.config().attribute || {};
        if (['TEXT', 'ENUM'].includes(definition.valueType) && (typeof model.stringValue !== 'string' || !model.stringValue.length || model.stringValue.length > Number(policy.maximumTextLength || 16384))) throw this.error('ERR_PRODUCT_00019', 'Attribute text value is invalid');
        if (definition.valueType === 'ENUM' && !(definition.enumerationValues || []).includes(model.stringValue)) throw this.error('ERR_PRODUCT_00019', 'Attribute enumeration value is not allowed');
        if (definition.valueType === 'BOOLEAN' && typeof model.booleanValue !== 'boolean') throw this.error('ERR_PRODUCT_00019', 'Attribute boolean value is invalid');
        if (definition.valueType === 'INTEGER' && !/^-?(0|[1-9][0-9]*)$/.test(String(model.integerValue))) throw this.error('ERR_PRODUCT_00019', 'Attribute integer value must be an exact integer string');
        if (['DECIMAL', 'MEASURED'].includes(definition.valueType)) this.exactDecimal(model.decimalValue);
        if (definition.valueType === 'DATE' && Number.isNaN(new Date(model.dateValue).getTime())) throw this.error('ERR_PRODUCT_00019', 'Attribute date value is invalid');
        if (definition.valueType === 'REFERENCE' && (!(policy.referenceTypes || []).includes(model.referenceType) || !SERVICE.DefaultProductEnterpriseScopeService.validateBusinessCode(model.referenceCode, 'Attribute reference'))) throw this.error('ERR_PRODUCT_00019', 'Attribute reference value is invalid');
        if (definition.valueType === 'REFERENCE' && model.referenceType === 'PRODUCT_ITEM') { if (!(this.config().item.itemTypes || []).includes(model.referenceItemType)) throw this.error('ERR_PRODUCT_00019', 'Referenced Product Item type is invalid'); let item = await this.loadItem(Object.assign({}, model, { itemType: model.referenceItemType, itemCode: model.referenceCode }), request); if (!item) throw this.error('ERR_PRODUCT_00019', 'Referenced Product Item is unavailable'); }
        if (definition.valueType === 'MEASURED') await SERVICE.DefaultProductReferenceService.validate('unit', model.unitCode, request);
    },
    /** Enforces per-Item, per-locale value cardinality. */ validateCardinality: async function (definition, model, request) { let query = { enterpriseCode: model.enterpriseCode, catalogCode: model.catalogCode, itemType: model.itemType, itemCode: model.itemCode, attributeCode: model.attributeCode, status: { $ne: 'RETIRED' } }; if (definition.localized) query.localeCode = model.localeCode; let response = await SERVICE.DefaultProductAttributeValueService.get({ tenant: request.tenant, authData: request.authData, query: query, searchOptions: { limit: Number(definition.maximumValues) + 1 } }), existing = this.items(response).filter(item => item.code !== model.code); if (existing.length >= Number(definition.maximumValues)) throw this.error('ERR_PRODUCT_00025', 'Attribute maximum cardinality is exceeded'); if (existing.some(item => Number(item.ordinal) === Number(model.ordinal))) throw this.error('ERR_PRODUCT_00025', 'Attribute value ordinal is already used'); return true; },
    /** Validates and scopes a typed Attribute Value. */ prepareValue: async function (request) {
        let model = request.model || {}, policy = this.config().attribute || {};
        SERVICE.DefaultProductEnterpriseScopeService.scopeNewModel(request, 'attributeValue', ['catalogCode', 'valueCode']); model = request.model;
        if (!(this.config().item.itemTypes || []).includes(model.itemType) || !(policy.statuses || []).includes(model.status || 'DRAFT') || !Number.isInteger(Number(model.ordinal)) || Number(model.ordinal) < 0) throw this.error('ERR_PRODUCT_00019', 'Attribute value identity, status, or ordinal is invalid');
        await SERVICE.DefaultProductReferenceService.validate('catalog', model.catalogCode, request); let definition = await this.loadDefinition(model, request), item = await this.loadItem(model, request); if (!definition || !item || (model.status || 'DRAFT') === 'ACTIVE' && (definition.status !== 'ACTIVE' || item.status !== 'ACTIVE')) throw this.error('ERR_PRODUCT_00019', 'Attribute Definition or Product Item is unavailable');
        this.validateLocale(definition, model); await this.validateTypedValue(definition, model, request); await this.validateCardinality(definition, model, request); return model;
    },
    /** Validates and scopes a classification Class and all referenced Definitions. */ prepareClass: async function (request) {
        let model = request.model || {}, policy = this.config().classification || {};
        SERVICE.DefaultProductEnterpriseScopeService.scopeNewModel(request, 'classificationClass', ['catalogCode', 'classCode']); model = request.model;
        let codes = model.attributeCodes || [], required = model.requiredAttributeCodes || [];
        if (!model.name || !Array.isArray(codes) || !codes.length || codes.length > Number(policy.maximumAttributesPerClass || 1000) || new Set(codes).size !== codes.length || !Array.isArray(required) || new Set(required).size !== required.length || required.some(code => !codes.includes(code)) || !(policy.statuses || []).includes(model.status || 'DRAFT')) throw this.error('ERR_PRODUCT_00026', 'Classification Class definition is invalid');
        await SERVICE.DefaultProductReferenceService.validate('catalog', model.catalogCode, request);
        let definitions = await Promise.all(codes.map(attributeCode => this.loadDefinition(Object.assign({}, model, { attributeCode: attributeCode }), request))); if (definitions.some(item => !item || (model.status || 'DRAFT') === 'ACTIVE' && item.status !== 'ACTIVE')) throw this.error('ERR_PRODUCT_00026', 'Classification Class references an unavailable Attribute Definition'); return model;
    },
    /** Requires all mandatory class values before an assignment becomes active. */ validateRequiredValues: async function (classification, model, request) { let definitions = await Promise.all((classification.attributeCodes || []).map(attributeCode => this.loadDefinition(Object.assign({}, model, { attributeCode: attributeCode }), request))), required = definitions.filter(definition => definition && (definition.required || (classification.requiredAttributeCodes || []).includes(definition.attributeCode))); for (let definition of required) { let response = await SERVICE.DefaultProductAttributeValueService.get({ tenant: request.tenant, authData: request.authData, query: { enterpriseCode: model.enterpriseCode, catalogCode: model.catalogCode, itemType: model.itemType, itemCode: model.itemCode, attributeCode: definition.attributeCode, status: 'ACTIVE' }, searchOptions: { limit: Number(definition.minimumValues || 1) } }); if (this.items(response).length < Number(definition.minimumValues || 1)) throw this.error('ERR_PRODUCT_00026', 'Required classification Attribute values are incomplete'); } return true; },
    /** Validates and scopes an Item-to-class assignment. */ prepareClassAssignment: async function (request) {
        let model = request.model || {}, policy = this.config().classification || {};
        SERVICE.DefaultProductEnterpriseScopeService.scopeNewModel(request, 'classificationAssignment', ['catalogCode', 'assignmentCode']); model = request.model;
        if (!(this.config().item.itemTypes || []).includes(model.itemType) || !(policy.statuses || []).includes(model.status || 'DRAFT')) throw this.error('ERR_PRODUCT_00026', 'Classification assignment type or status is invalid'); this.assertDates(model);
        await SERVICE.DefaultProductReferenceService.validate('catalog', model.catalogCode, request); let item = await this.loadItem(model, request), response = await SERVICE.DefaultProductClassificationClassService.get({ tenant: request.tenant, authData: request.authData, query: { enterpriseCode: model.enterpriseCode, catalogCode: model.catalogCode, classCode: model.classCode }, searchOptions: { limit: 2 } }), classes = this.items(response), classification = classes.length === 1 && classes[0].status !== 'RETIRED' ? classes[0] : undefined; if (!item || !classification || (model.status || 'DRAFT') === 'ACTIVE' && (item.status !== 'ACTIVE' || classification.status !== 'ACTIVE')) throw this.error('ERR_PRODUCT_00026', 'Classification assignment reference is invalid'); let assignmentResponse = await SERVICE.DefaultProductClassificationAssignmentService.get({ tenant: request.tenant, authData: request.authData, query: { enterpriseCode: model.enterpriseCode, catalogCode: model.catalogCode, itemType: model.itemType, itemCode: model.itemCode, status: { $ne: 'RETIRED' } }, searchOptions: { limit: Number(policy.maximumClassesPerItem || 100) + 1 } }), existing = this.items(assignmentResponse).filter(item => item.code !== model.code); if (existing.length >= Number(policy.maximumClassesPerItem || 100) || existing.some(item => item.classCode === model.classCode)) throw this.error('ERR_PRODUCT_00026', 'Classification assignment cardinality is invalid'); if ((model.status || 'DRAFT') === 'ACTIVE') await this.validateRequiredValues(classification, model, request); return model;
    },
    /** Rejects retirement while active classification dependants remain. */ assertRetirable: async function (kind, current, request) { let calls = kind === 'definition' ? [SERVICE.DefaultProductAttributeValueService.get({ tenant: request.tenant, authData: request.authData, query: { enterpriseCode: current.enterpriseCode, catalogCode: current.catalogCode, attributeCode: current.attributeCode, status: { $ne: 'RETIRED' } }, searchOptions: { limit: 1 } }), SERVICE.DefaultProductClassificationClassService.get({ tenant: request.tenant, authData: request.authData, query: { enterpriseCode: current.enterpriseCode, catalogCode: current.catalogCode, attributeCodes: current.attributeCode, status: { $ne: 'RETIRED' } }, searchOptions: { limit: 1 } })] : [SERVICE.DefaultProductClassificationAssignmentService.get({ tenant: request.tenant, authData: request.authData, query: { enterpriseCode: current.enterpriseCode, catalogCode: current.catalogCode, classCode: current.classCode, status: { $ne: 'RETIRED' } }, searchOptions: { limit: 1 } })]; let responses = await Promise.all(calls); if (responses.some(response => this.items(response).length)) throw this.error('ERR_PRODUCT_00027', 'Retire classification dependants first'); return true; },
    /** Validates immutable identity, lifecycle, structural fields, and references on update. */ update: async function (request, serviceName, identityProperties, structuralProperties, prepareName, policyName, retirementKind) { await SERVICE.DefaultProductEnterpriseScopeService.scopeQuery(request); let response = await SERVICE[serviceName].get({ tenant: request.tenant, authData: request.authData, query: request.query, searchOptions: { limit: 2 } }), items = this.items(response); if (items.length !== 1) throw this.error('ERR_PRODUCT_00012', 'Classification update target must resolve exactly one record'); let current = items[0], patch = request.model || {}; ['code', 'enterpriseCode'].concat(identityProperties).concat(structuralProperties || []).forEach(property => { if (patch[property] !== undefined && JSON.stringify(patch[property]) !== JSON.stringify(current[property])) throw this.error('ERR_PRODUCT_00011', 'Classification identity or structure is immutable'); }); if (patch.status && patch.status !== current.status) { let allowed = (((this.config()[policyName] || {}).allowedTransitions || {})[current.status]) || []; if (!allowed.includes(patch.status)) throw this.error('ERR_PRODUCT_00011', 'Classification lifecycle transition is invalid'); } if (retirementKind && patch.status === 'RETIRED' && current.status !== 'RETIRED') await this.assertRetirable(retirementKind, current, request); let validationRequest = Object.assign({}, request, { model: Object.assign({}, current, patch) }); await this[prepareName](validationRequest); request.model = patch; return true; },
    /** Validates Attribute Definition updates. */ prepareDefinitionUpdate: function (request) { return this.update(request, 'DefaultProductAttributeDefinitionService', ['catalogCode', 'attributeCode'], ['valueType', 'localized', 'multiValued', 'unitRequired'], 'prepareDefinition', 'attribute', 'definition'); },
    /** Validates Attribute Value updates. */ prepareValueUpdate: function (request) { return this.update(request, 'DefaultProductAttributeValueService', ['catalogCode', 'valueCode', 'itemType', 'itemCode', 'attributeCode', 'localeCode'], [], 'prepareValue', 'attribute'); },
    /** Validates classification Class updates. */ prepareClassUpdate: function (request) { return this.update(request, 'DefaultProductClassificationClassService', ['catalogCode', 'classCode'], [], 'prepareClass', 'classification', 'class'); },
    /** Validates Item-to-class assignment updates. */ prepareClassAssignmentUpdate: function (request) { return this.update(request, 'DefaultProductClassificationAssignmentService', ['catalogCode', 'assignmentCode', 'classCode', 'itemType', 'itemCode'], [], 'prepareClassAssignment', 'classification'); }
};
